### PR TITLE
[AKS] Add az aks nodepool get-upgrades command

### PR DESCRIPTION
**Pull request by gtxistxgao**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

Official CLI has already supported it. Add the same support to CLI-Extension https://github.com/Azure/azure-cli/pull/14516

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by arrownj — COMMENTED** [review]
Please also add a test for this new command.

**Review by arrownj — APPROVED** [review]
Hi @gtxistxgao , the code is good to me, please help fix the CI error, thanks.

**Comment by gtxistxgao** [comment]
> Hi @gtxistxgao , the code is good to me, please help fix the CI error, thanks.

Sure. rebased master.

**Pull request merged**
