### PR TITLE
fixing OS partition detection

### PR DESCRIPTION
**Pull request by jofrance**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jofrance** [comment]
#sing-off

**Comment by yonzhan** [comment]
vm repair

**Comment by haagha** [comment]
@zhoxing-ms I am not added as part of the automatic reviewers despite me being code-owner for this repo.

https://github.com/Azure/azure-cli-extensions/blob/main/.github/CODEOWNERS#L63

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
Could you please add description in the history notes for this change?

**Review by yanzhudd — APPROVED** [review]

**Comment by jofrance** [comment]
fixing OS partition detection for RHEL ADE encrypted VMS and changing version to 0.4.9

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
＠jofrance It is recommended to write this version change into the `HISTORY.rst`

**Comment by jofrance** [comment]
Done

/ceschi - Jose Francisco Franceschi Vargas
Escalation Engineer, Microsoft Azure Linux Support
Office: +506 411 60004
***@***.******@***.***>
0800 - 1700 GMT -6
If you have any feedback about my work, please let either me or my manager Kurt Davidson know at ***@***.******@***.***>

**Pull request merged**
