### PR TITLE
{AKS} remove image cleaner testing exceptions

### PR DESCRIPTION
**Pull request by jiashun0011**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by FumingZhang** [comment]
Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=60399787&view=results) to verify the changes.

**Comment by jiashun0011** [comment]
> Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=60399787&view=results) to verify the changes. All passed, please upload the recordings from the artifacts.

@FumingZhang Thanks and uploaded.

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
AKS

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
