### PR TITLE
az generate

### PR DESCRIPTION
**Pull request by changlong-liu**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
az generate

**Comment by haroldrandom** [comment]
Any context?

**Comment by changlong-liu** [comment]
Hi @haroldrandom , thank you. It's for onboarding AZ_DESKTOPVIRTUALIZATION https://dev.azure.com/azure-mgmt-ex/Onboarding/_boards/board/t/Onboarding%20Team/Features/?workitem=901.


Please hold review for this PR, let me check the pipeline errors first.

**Comment by haroldrandom** [comment]
The test `test_windows_virtual_desktop ` failed, you should upload recording file otherwise CI would ask you to login because CI run test on playbck mode.

**Comment by changlong-liu** [comment]
Close this PR since the extension name is changed in the speclet, so the whole extension file tree is changed.

Will start another PR for DESKTOPVIRTUALIZATION

**Pull request closed without merging**
