### PR TITLE
Update ACS Rooms Azure CLI to new version 1.1.0b1 to Support PSTN Dial-Out Feature

### PR DESCRIPTION
**Pull request by mikehang-msft**
---
Update ACS Rooms Azure CLI to new version 1.1.0b1 to Support PSTN Dial-Out Feature

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by paolamvhz — APPROVED** [review]

**Comment by mikehang-msft** [comment]
Hi @yonzhan, as we are releasing other SDKs, we are looking for a review and approval for Azure CLI as well. Can you please review this PR for us?

**Comment by mikehang-msft** [comment]
Hi @zhoxing-ms and @yanzhudd, can you please review this PR? Our team has a deadline to release the SDK on Oct 31st, 2023. Much appreciated if you can merged the change in ASAP.

**Review by jsntcy — APPROVED** [review]

**Comment by jsntcy** [comment]
> Hi @zhoxing-ms and @yanzhudd, can you please review this PR? Our team has a deadline to release the SDK on Oct 31st, 2023. Much appreciated if you can merged the change in ASAP.

Overall LGTM, please ensure the business logic is correct as we only review if the code complies with CLI conventions/styles or not.

**Comment by mikehang-msft** [comment]
thanks @jsntcy. I have also added unit tests to cover newly added functions to ensure they are working as expected. Can you please merge the change for me if there is no additional changes?

**Pull request merged**
