### PR TITLE
{Account} Bump up `azure-mgmt-subscription` SDK version to `3.1.1`

### LINKED ISSUE #23727: Azure-cli request to update for a Subscription API
**Resource Provider**
Microsoft.Subscription

**Description of Feature or Work Requested**
We have found an issue missing field for a response of "acceptOwnershipStatus" API on swagger. On the service side, it is there. So, we have corrected it on swagger specs and generated python SDK. The python SDK is released now. We would like AzureCLI to refer to latest changes.

**Minimum API Version Required**
2021-10-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json

**Python SDK**
https://pypi.org/project/azure-mgmt-subscription/3.1.0/

**Target Date**
ASAP

### PR DESCRIPTION
**Pull request by Jing-song**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

`az account`

close https://github.com/Azure/azure-cli/issues/23727

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Subscription

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@Ochirkhuyag Could you please help review this PR to see if it meets your expectations?

**Comment by Ochirkhuyag** [comment]
> @Ochirkhuyag Could you please help review this PR to see if it meets your expectations?

I am not familiar with Python and not sure to check if it is the expectation.

**Comment by zhoxing-ms** [comment]
@Ochirkhuyag OK, because the extension can be released at any time, so I merged this PR first. 
You can install the latest version of this extension for testing. If you encounter any other problems, please feel free to tell us, thanks~

**Comment by Emmanu12** [comment]
> This checklist is used to make sure that common guidelines for a pull request are followed.
> 
> ### Related command
> `az account`
> 
> close [Azure/azure-cli#23727](https://github.com/Azure/azure-cli/issues/23727)
> 
> ### General Guidelines
> * [ ]  Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
> * [ ]  Have you run `python scripts/ci/test_index.py -q` locally?
> 
> For new extensions:
> 
> * [ ]  My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
> 
> ### About Extension Publish
> There is a pipeline to automatically build, upload and publish extension wheels. Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically. The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

**Pull request merged**
