### PR TITLE
[k8s-runtime] Make `k8s-runtime` stable

### PR DESCRIPTION
**Pull request by ddadaal**
Make k8s-runtime extension stable.

1. Use stable api version `2024-03-01` for ARM APIs
2. Remove preview tags for `load-balancers` and `bgp-peers` command groups

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
k8s-runtime

**Comment by HE-Xinyu** [comment]
> ❌Azure CLI Extensions Breaking Change Test

This is by-design, as the `delete` API changes from async to sync in stable API version.

**Comment by HE-Xinyu** [comment]
hi @zhoxing-ms @yanzhudd could you please review the PR? Thanks!

**Comment by HE-Xinyu** [comment]
hi @zhoxing-ms @yanzhudd could you please review the PR or share the status? Thanks!

**Comment by yanzhudd** [comment]
It is better to rerun some related tests in live mode to validate if the change meets your expectation.

**Comment by ddadaal** [comment]
We did run the tests. [Last comment](https://github.com/Azure/azure-cli-extensions/pull/7390#discussion_r1544272398) told us to remove recording files for live tests. So how should we prove it?

**Pull request merged**
