### PR TITLE
EventGrid: Update index.json to reflect latest version.

### PR DESCRIPTION
**Pull request by kalyanaj**
---
EventGrid: Updated index.json to reflect latest version.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [X] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by kalyanaj** [comment]
@tjprescott , @williexu: Need your help with this sometime today if possible to review/merge, the only remaining issue is one CI issue which appears to be a false positive. We are looking to release this version out today if possible.

**Comment by williexu** [comment]
@kalyanaj 
- `--ids` parameter is meant to be used for the resource indicated by the command-group. ex:
For the command, `az eventgrid topic delete`, the `--ids` parameter can be used to specify multiple topics(the command-group resource) ids. In `az eventgrid topic key list` the presence of `--ids` to refer to the topic can be confusing because it is not the rightmost "resource" indicated by the command-group. Similarly, `--name` should ideally be renamed to `--topic`.
- In addition, for `az eventgrid topic key list`, what would be the reason for a user to specify multiple ids as the parameter implies? If multiple ids were provided, would you expect all the keys for each topic to be combined and then returned? Again, confusing, hence the rule.

The way to accept ONE id, which i believe is the intention, is to combine the functionality of `--topic` to accept both the topic name and topic resource id.

**Comment by kalyanaj** [comment]
Thanks for the info, that makes sense. What's the best way for me to remove the --ids parameter for these cases?  Taking the example of "domain key list", I have the following in commands.py and I didn't quite get how I can disable support for the --ids parameter?

    with self.command_group('eventgrid domain', domains_mgmt_util, client_factory=domains_factory) as g:
        g.command('key list', 'list_shared_access_keys')

**Comment by williexu** [comment]
This is done in the _params.py file. The following line: https://github.com/Azure/azure-cli-extensions/blob/master/src/eventgrid/azext_eventgrid/_params.py#L66
Adds the `--ids` parameter for all commands under that group. To disable it for the specific command, specify `id_part=None`

**Comment by kalyanaj** [comment]
Thanks @williexu for the information, I have made the changes to remove the --ids parameter from these commands.

**Pull request merged**
