### PR TITLE
Remove appconfig extension

### PR DESCRIPTION
**Pull request by shenmuxiaosen**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

As we have merged into main CLI, we don't want to release the extension anymore.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
Has the extension moved to main repo Azure/azure-cli already?

**Comment by shenmuxiaosen** [comment]
> Has the extension moved to main repo Azure/azure-cli already?
We have merged into main CLI. 
https://github.com/Azure/azure-cli/tree/dev/src/azure-cli/azure/cli/command_modules/appconfig

**Comment by jsntcy** [comment]
@shenmuxiaosen, you also need update the docs as in 
https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest, appconfig is still there.

**Comment by shenmuxiaosen** [comment]
> @shenmuxiaosen, you also need update the docs as in
> https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest, appconfig is still there.

I assume this is somehow auto generated as we didn't manually add this doc when we added our cli extension.  Do you know what is the right way to remove the doc?

**Comment by jsntcy** [comment]
> > @shenmuxiaosen
> >             
> >             Shuai Wang
> >             FTE, you also need update the docs as in
> > https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest, appconfig is still there.
> 
> I assume this is somehow auto generated as we didn't manually add this doc when we added our cli extension. Do you know what is the right way to remove the doc?

no, it is added manually as it's conceptual content, but not reference content.

**Comment by jsntcy** [comment]
> > > @shenmuxiaosen
> > > ```
> > >         Shuai Wang
> > >         FTE, you also need update the docs as in
> > > ```
> > > 
> > > 
> > > https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest, appconfig is still there.
> > 
> > 
> > I assume this is somehow auto generated as we didn't manually add this doc when we added our cli extension. Do you know what is the right way to remove the doc?
> 
> no, it is added manually as it's conceptual content, but not reference content.

@dbradish-microsoft, could you help update the doc?

**Comment by dbradish-microsoft** [comment]
The **appconfig** is also still listed in the Extensions TOC <https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/?view=azure-cli-latest> which is auto-generated by Robert Outlaw <robert.outlaw@microsoft.com> (I cannot find his alias even with Advanced Search.).

I will create an Azure DevOps work item and speak to the Azure CLI PM regarding both issues.  Looking at <https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest>, it just isn't **appconfig**.  We need to update the entire table.

**Comment by rloutlaw** [comment]
I'm always around at @rloutlaw :)

Who owns/operates the azclibot account that keeps the extension page linked up to date here:

https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest

That commit history does not look like its owned by @dbradish-microsoft  and is hand-updated at all. There's some automation running there, but it's not the same as the ones generating the actual reference pages.

**Comment by dbradish-microsoft** [comment]
@rloutlaw , Thanks for helping me find your ID.  :-)  

This markdown file is owned by me --> https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest.  I have created an Azure DevOps work item to fix it, but to get rid of the entry under Reference, https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/?view=azure-cli-latest, isn't that your team?

**Comment by shenmuxiaosen** [comment]
@dbradish-microsoft Thanks for creating the work item. Is this pr blocked until the CLI extension documents got fixed? @jsntcy

**Comment by dbradish-microsoft** [comment]
@jsntcy, I would request that this PR be just for @rloutlaw 's team.  I am speaking with @yonzhan to get a list of all needed updates in https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list, and will have a separate PR submitted hopefully this week.  Kindly, D~

**Comment by jsntcy** [comment]
@shenmuxiaosen, I think we should update documents first before this PR is merged; otherwise user will be confused that the document list the extension, but they cannot install it as you have already removed it here.

**Comment by jsntcy** [comment]
@dbradish-microsoft, I have sent you current available CLI extension list in email, please help take a look.

**Comment by dbradish-microsoft** [comment]
@shenmuxiaosen, @jsntcy, @yonzhan, **appconfig** has been removed from Available Extensions for the Azure CLI markdown file and merged.  The change should be reflected shortly.

**Comment by jsntcy** [comment]
After appconfig is removed from index.json, both https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest and  https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/?view=azure-cli-latest will be updated to latest automatically as they extract information from index.json.

**Pull request merged**
