### PR TITLE
[Deprecated][Breadth Coverage] Alertsmanagement

### PR DESCRIPTION
**Pull request by qwordy**
Alertsmanagement commands

1. az alertsmanagement action-rule create/update/show/delete/list
Done
2. az alertsmanagement alert get-history/get-by-id/get-summary/get-all
Done
2. az alertsmanagement smart-detector-alert-rule
Can't test. Detector is a required parameter of smart-detector-alert-rule. can't create detector yet
3. az alertsmanagement smart-group
Cant's test. Can't get smart group instances. Alerts are classified into smart groups automatically using ML algorithm. Smart group can't be created manually.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S165.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/12049

**Comment by yungezz** [comment]
thanks @qwordy . as we synced offline, pls split the PR to smaller one for speclet coverage only firstly, then rest change after that.

**Comment by qwordy** [comment]
> 
> 
> thanks @qwordy . as we synced offline, pls split the PR to smaller one for speclet coverage only firstly, then rest change after that.

New PR:
https://github.com/Azure/azure-cli-extensions/pull/1370

**Pull request closed without merging**
