### PR TITLE
[AKS] Improve messages for upgrade command

### PR DESCRIPTION
**Pull request by lalo**
- Inform users of specific behaviours when they try to upgrade a cluster
to the current version of that cluster.

Mirror PR of this https://github.com/Azure/azure-cli/pull/8625

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by williexu** [comment]
@zqingqing1 can you review as codeowner?

**Comment by zqingqing1** [comment]
@lalo , what about the cluster is at updating/Deleting status, should we message customer?

**Comment by lalo** [comment]
@zqingqing1 this PR is mainly to keep it in sync with the non-extension code (https://github.com/Azure/azure-cli/pull/8625). I don't think we need to notify the customer on those cases, what makes upgrading special is that there is certain logic that gets triggered only if a user upgrades a failed cluster (mainly a cluster that failed previously while upgrading) and nothing happens if its in succeeded state. In the other cases, everything should be handled correctly already.

**Comment by zqingqing1** [comment]
Got you, thanks :)

**Pull request merged**
