### PR TITLE
Reservation and Quota CLI extension 

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
Copied from : https://github.com/AzureSDKAutomation/azure-cli-extensions/pull/700/commits

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Reservation

**Comment by jsntcy** [comment]
@rahuls-microsoft, when you click the `Details` on ADO, it will tell you what the errors are, please fix them according the error information.

**Comment by rahuls-microsoft** [comment]
> @rahuls-microsoft, when you click the `Details` on ADO, it will tell you what the errors are, please fix them according to the error information.

Are we supposed to edit the generated files?
The files were picked up from - https://github.com/AzureSDKAutomation/azure-cli-extensions/pull/700/commits from @qiaozha
The build passed for that commit, why it's failing here?
I am not familiar with python. Please help.
@qiaozha Can you please take a look?
Thanks

**Comment by jsntcy** [comment]
Close this PR since it's open for about one year.

**Pull request closed without merging**
