### PR TITLE
[Release] Update index.json for extension [ webapp ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ webapp ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=652255

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/4c88d0c2c77639afdca5bcbee5fab152502c2cdd

### CODE REVIEW

**Comment by yonzhan** [comment]
webapp

**Comment by shrishrirang** [comment]
I can see there are failures blocking the merging of this PR. Are these pipeline errors or are these related to the webapp extension changes? Can you take a look and let me know if there is anything needed from me for the extension to be published?

**Comment by qwordy** [comment]
The error message:
```
Exception occurred:
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp9z_fdogg/extension/azext_webapp/custom.py", line 322
    async=None,
-- Using output directory /tmp/tmp1q2tvtfj/webapp
-- Executing "/opt/hostedtoolcache/Python/3.7.9/x64/bin/python -m pip install --target /tmp/tmp9z_fdogg/extension /tmp/tmp4_8ulbtd/webapp-0.3.0-py2.py3-none-any.whl --disable-pip-version-check --no-cache-dir"
-- Executing "sphinx-build -b xml /home/vsts/work/1/s/scripts/refdoc /tmp/tmp1q2tvtfj/webapp" with AZURE_EXTENSION_DIR set to /tmp/tmp9z_fdogg
-- Cleaned up temp directory /tmp/tmp9z_fdogg
Traceback (most recent call last):
  File "/home/vsts/work/1/s/scripts/refdoc/generate.py", line 80, in <module>
    generate(args.ext_file, args.output_dir)
  File "/home/vsts/work/1/s/scripts/refdoc/generate.py", line 42, in generate
    check_call(sphinx_cmd, env=env)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sphinx-build', '-b', 'xml', '/home/vsts/work/1/s/scripts/refdoc', '/tmp/tmp1q2tvtfj/webapp']' returned non-zero exit status 2.
ERROR

======================================================================
ERROR: test_ref_doc_webapp (__main__.IndexRefDocs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts/ci/index_ref_doc.py", line 62, in test
    check_call(script_args)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.7.9/x64/bin/python', '/home/vsts/work/1/s/scripts/refdoc/generate.py', '--extension-file', '/tmp/tmp4_8ulbtd/webapp-0.3.0-py2.py3-none-any.whl', '--output-dir', '/tmp/tmp1q2tvtfj/webapp']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/ci/index_ref_doc.py", line 64, in test
    traceback.print_exc(e)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/traceback.py", line 337, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'CalledProcessError' and 'int'

```

**Comment by shrishrirang** [comment]
Thanks for taking a look. Can you share how I can reproduce this error locally?

**Comment by shrishrirang** [comment]
Ok, I figured out the problem. I'll publish a PR with the fix.

**Pull request closed without merging**
