### PR TITLE
AMG: Backup & restore provision dashboard bug fix

### PR DESCRIPTION
**Pull request by ABZhang0**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az grafana backup -g MyResourceGroup -n MyGrafana -d c:\temp --folders-to-include "Prod" "Compute Gateway" --components datasources dashboards folders

az grafana restore -g MyResourceGroup -n MyGrafana --archive-file backup\dashboards\ServiceHealth-202307051036.tar.gz --components dashboards folders --remap-data-sources

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by ReaNAiveD** [comment]
Hi @ABZhang0 , Please fix the CI issues.

**Comment by ReaNAiveD** [comment]
Please update the Release History in `HISTORY.rst`.

**Review by ReaNAiveD — APPROVED** [review]

**Pull request merged**
