### PR TITLE
[Spring Cloud]Fix the deploy jar failure.

### PR DESCRIPTION
**Pull request by LGDoor**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by LGDoor** [comment]
Didn't bump up the version on purpose. It will be included in the next major release.

**Comment by yonzhan** [comment]
Spring Cloud

**Review by wangzelin007 — CHANGES_REQUESTED** [review]
Don't forget to update setup.py~

**Comment by LGDoor** [comment]
> Don't forget to update setup.py~

Hi, the version is left untouched on purpose. It will be changed in later PR when the new version is ready to be published.

**Review by zhoxing-ms — APPROVED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Pull request merged**
