### PR TITLE
Index.json: updated index.json for Service Bus and Event Hubs extensions

### PR DESCRIPTION
**Pull request by v-Ajnava**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [ ] Have you run `python scripts/ci/test_integration.py -q` locally?

### CODE REVIEW

**Comment by derekbekoe** [comment]
Please get CI green.

**Comment by v-Ajnava** [comment]
will record event hubs test and push.

**Comment by derekbekoe** [comment]
What changed? Why do they need to be rerecorded again?

**Comment by v-Ajnava** [comment]
CI is failing also for event hubs test with error : test_eh_alias (azext_eventhub.tests.test_eventhub_commands.EHNamespaceCURDScenarioTest) ... Please run 'az login' to setup account.

**Pull request merged**
