### PR TITLE
Update connectedvmware extension for public preview.

### PR DESCRIPTION
**Pull request by iamsantoshmishra-zz**
---

Added more features in connectedvmware az cli extension for public preview. 

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
connectedvmware

**Comment by zhoxing-ms** [comment]
You need to pull the latest code from the remote main branch to solve the CI issue

**Comment by zhoxing-ms** [comment]
Please refer to the error message from linter to fix the help related issue:
> -  FAIL - HIGH severity: faulty_help_example_parameters_rule
    Help-Entry: `connectedvmware vcenter inventory-item list` - 
	There is a violation:
	"az connectedvmware vcenter inventory-item list --resource-group "resource group name"                --vcenter-name "name of the vcenter"" is not a valid command.
	the following arguments are required: --vcenter/-v.


    Help-Entry: `connectedvmware vcenter inventory-item show` - 
	There is a violation:
	"az connectedvmware vcenter inventory-item show --inventory-item-name "inventory item name"                --resource-group "resource group name" --vcenter-name "name of the vcenter"" is not a valid command.
	the following arguments are required: --vcenter/-v, --inventory-item/-i.

You should add missing required parameters to the example.

**Comment by zhoxing-ms** [comment]
> ======================================================================
ERROR: test_connectedvmware (azext_connectedvmware.tests.latest.test_connectedvmware_scenario.ConnectedvmwareScenarioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1215, in _dot_lookup
    return getattr(thing, comp)
AttributeError: module 'azure.cli.core.auth' has no attribute 'identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure_devtools/scenario_tests/base.py", line 146, in setUp
    patch(self)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/testsdk/patches.py", line 76, in patch_retrieve_token_for_user
    mock_in_unit_test(unit_test, 'azure.cli.core.auth.identity.UserCredential', UserCredentialMock)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure_devtools/scenario_tests/patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1377, in __enter__
    self.target = self.getter()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1552, in <lambda>
    getter = lambda: _importer(target)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1228, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1217, in _dot_lookup
    __import__(import_path)
ModuleNotFoundError: No module named 'azure.cli.core.auth.identity'

It seems that there are problems related to dependent packages. Please take a look~

**Comment by jiasli** [comment]
The extension shouldn't rely on `azure-cli-core`: https://github.com/Azure/azure-cli-extensions/blob/ba160f9655ab76a5b6226d1f6971635bda348958/src/connectedvmware/setup.py#L38

Otherwise, it will install the public version of `azure-cli-core` and override the edge build, causing failure:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1151604&view=logs&j=b91d5b15-5807-5220-2a74-dca0b2e5db7b&t=eb4058c2-c320-540b-4788-cb9224578609&l=773

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/unittest/mock.py", line 1075, in _dot_lookup
    return getattr(thing, comp)
AttributeError: module 'azure.cli.core.auth' has no attribute 'identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/azure_devtools/scenario_tests/base.py", line 146, in setUp
    patch(self)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/azure/cli/testsdk/patches.py", line 76, in patch_retrieve_token_for_user
    mock_in_unit_test(unit_test, 'azure.cli.core.auth.identity.UserCredential', UserCredentialMock)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/azure_devtools/scenario_tests/patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/unittest/mock.py", line 1231, in __enter__
    self.target = self.getter()
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/unittest/mock.py", line 1401, in <lambda>
    getter = lambda: _importer(target)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/unittest/mock.py", line 1088, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/unittest/mock.py", line 1077, in _dot_lookup
    __import__(import_path)
ModuleNotFoundError: No module named 'azure.cli.core.auth.identity'
```

**Pull request merged**
