### PR TITLE
Update `aks kollect` command to use Periscope version 0.0.10

### PR DESCRIPTION
**Pull request by peterbom**
This updates the `aks kollect` command so that it uses the latest Periscope version, which includes enhanced support for Windows log collection (amongst other quality updates).

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
aks

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by Tatsinnit** [comment]
❤️❤️☕️🪄 thank you so much for this @peterbom , and hiya @FumingZhang can you please help us to identify why this test is failing. ❤️🙏 thank you.

**Comment by yonzhan** [comment]
aks

**Review by FumingZhang — APPROVED** [review]
LGTM, not sure if the test case needs to be updated as well.

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@peterbom Could you please resolve those conflicts?

**Pull request merged**
