### PR TITLE
Adding Partner Center Extension

### PR DESCRIPTION
**Pull request by kevinhillinger**
CLI extension for the Partner Center. Currently, experimentally supporting Marketplace management commands, commissioned by Global Partner Services US division.

### Authors
- @kevinhillinger 
- @bobjac 

### Source
- Type: External repository
- URL: https://github.com/Azure/partnercenter-cli-extension

### CODE REVIEW

**Comment by kevinhillinger** [comment]
whl file should have all dependencies. Closed and reopened to trigger another build verification.

**Comment by yonzhan** [comment]
Partner Center

**Comment by kevinhillinger** [comment]
@yonzhan @kairu-ms it's not clear why the build is failing for this PR. 

In `Verify Ref Docs` it's reporting a failure in `ERROR: test_ref_doc_vmware (__main__.IndexRefDocs)` which seems to be a pre-existing failure in the source?

**Comment by wangzelin007** [comment]
> @yonzhan @kairu-ms it's not clear why the build is failing for this PR.
> 
> In `Verify Ref Docs` it's reporting a failure in `ERROR: test_ref_doc_vmware (__main__.IndexRefDocs)` which seems to be a pre-existing failure in the source?

Hi kevinhillinger,
Verify Ref Docs fetches the latest extension and executes the tests. 
Because vmware 5.0.0 misses the __init__.py file, an error will be reported while import. 
So, we released a new version of vmware == 5.0.1.
After a new version of vmware is released, this problem can be solved by simply re-running the CI tests.
But it is true that vmware 5.0.0 should be deleted in case users specify this version to download.

**Comment by kevinhillinger** [comment]
@wangzelin007 confirming, will this get merged as part of the Jan 10, 2023 release?

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
