### PR TITLE
az ml 2.0.1a1 release

### PR DESCRIPTION
**Pull request by Mossaka**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by Mossaka** [comment]
@fengzhou-msft Does az cli automatically picks the newest version to generate the extension tree?

**Comment by yonzhan** [comment]
Add @kairu-ms to help with

**Comment by kairu-ms** [comment]
> @fengzhou-msft Does az cli automatically picks the newest version to generate the extension tree?

Yes, cli will use the latest version to generate the extension tree.

**Comment by kairu-ms** [comment]
Please fix CI issues. Thanks.

**Comment by Mossaka** [comment]
@kairu-ms  Can we get this PR to merge in?

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
