### PR TITLE
{AKS} Refine tests for azurekeyvaultkms

### PR DESCRIPTION
**Pull request by bingosummer**
* Add test to rotate key for public cluster + public/private key vault
* Add test to create private cluster with private key vault, and rotate key

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by bingosummer** [comment]
https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=58092571&view=results

**Review by karataliu — APPROVED** [review]

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by bingosummer** [comment]
@zhoxing-ms could you please review and merge the PR? Thanks

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
