### PR TITLE
[AKS] BREAKING CHANGE: `az aks create`: Remove legacy AAD related parameters when creating AKS cluster

### PR DESCRIPTION
**Pull request by bingosummer**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

```
az aks create --resource-group={resource_group} --name={name} \
  --aad-server-app-id 00000000-0000-0000-0000-000000000001 \
  --aad-server-app-secret fake-secret \
  --aad-client-app-id 00000000-0000-0000-0000-000000000002
```

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by fseldow — APPROVED** [review]

**Comment by karataliu** [comment]
update all including linter exclusions?  https://github.com/search?q=repo%3AAzure%2Fazure-cli-extensions%20aad_server_app_secret&type=code

**Review by FumingZhang — APPROVED** [review]

**Review by karataliu — APPROVED** [review]
lgtm

**Comment by bingosummer** [comment]
@yanzhudd I rebased and re-ran the test.

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
