### PR TITLE
Update MySQL and PostgreSQL help text and sku-name parameter.

### PR DESCRIPTION
**Pull request by rohit-joy**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [x] Have you run `python scripts/ci/test_integration.py -q` locally?

### CODE REVIEW

**Comment by rohit-joy** [comment]
@QingqingYuan, please review.

**Comment by QingqingYuan** [comment]
Looks good to me

**Comment by derekbekoe** [comment]
@rohit-joy Let me know if you'd like to merge this now.

**Comment by rohit-joy** [comment]
@derekbekoe Yes, please merge it.

**Pull request merged**
