### PR TITLE
Allow alternate ssh distributions

### PR DESCRIPTION
**Pull request by jkroepke**
Our company does not have the windows 10 ssh client installed. As user we not allowed to install such windows features. But we are able to provide ssh-keygen.exe on different ways. The ssh-keygen.exe command is inside our path, but the az cli forcefully look into C:\SysNative\OpenSSH.

This PR add a fallback on Windows systems, in case `C:\SysNative\OpenSSH` is not present, the ssh command from the PATH should be used.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jkroepke** [comment]
Please let me know, if the code solution is fine. If yes, I take a look at the ITs

**Comment by yonzhan** [comment]
ssh

**Comment by jkroepke** [comment]
Any update to this?

**Comment by jkroepke** [comment]
@jiasli @N6UDP any Feedback for me?

**Comment by jkroepke** [comment]
Hi, did we miss the milestone again? :/

**Comment by jkroepke** [comment]
Superseeded by https://github.com/Azure/azure-cli-extensions/pull/4570

**Pull request closed without merging**
