### PR TITLE
Update compatible release version for setproctitle to support Python 3.11

### PR DESCRIPTION
**Pull request by ambrahma**
Update compatible release version for setproctitle to support Python 3.11

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by ambrahma** [comment]
@evelyn-ys can you help with failures for Build Tests ?

**Comment by bebound** [comment]
I can't find a workaround for this dependency conflict unless `pycli` unpins `cryptography`: https://github.com/dbcli/mycli/pull/1109

**Review by evelyn-ys — APPROVED** [review]

**Comment by jiasli** [comment]
The PR title should contain `{rdbms-connect}` tag.

**Pull request merged**
