### PR TITLE
Include the fzf extension in the index

### PR DESCRIPTION
**Pull request by phealy**
This is a new extension I've written to automate some of the tasks I find most repetitive with azure CLI: specifying my resource group, location, and subscription. It provides four new commands:

* `az fzf group` - select your default resource group
* `az fzf location` - select your default location
* `az fzf subscription` - select your current subscription
* `az fzf install` - download a copy of fzf if you don't have it

These commands make use of [FZF](https://github.com/junegunn/fzf), a command line fuzzy finder. When you install the extension and run them, they pop up a nice text interface that allows for searching and selecting from a list of objects via keyboard or mouse.

While I am a Microsoft employee, this is something I created on my off time and not something I did as a job duty. I will not be able to provide support during business hours, so I've marked it as experimental per Feng Zhou's guidance. I will answer issues as I can on the source repository: https://github.com/phealy/azure-cli-fzf/

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
fzf

**Comment by yungezz** [comment]
@fengzhou-msft is working witht @phealy via email on this.

**Review by fengzhou-msft — APPROVED** [review]

**Comment by phealy** [comment]
Is there anything else I need to do for this to merge now that it's approved?

**Comment by yungezz** [comment]
> Is there anything else I need to do for this to merge now that it's approved?

HI @phealy thanks for contribution. we're doing local testing for the extension. Once it's finished will merge it. thanks.

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
