### PR TITLE
aks-preview extension release v0.4.19

### PR DESCRIPTION
**Pull request by bingosummer**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by bingosummer** [comment]
@zikalino @zqingqing1 please have a look.

**Comment by zikalino** [comment]
@bingosummer no need to have 2 entries in index.json, you can remove the old one

**Comment by bingosummer** [comment]
> @bingosummer no need to have 2 entries in index.json, you can remove the old one
> just to make sure you can compare them to make sure there's nothing specific the new entry is using.
> 
> we usually can have 2 entries, if the new release doesn't support some older version of Azure CLI core, and I think it's not the case here.

Got your point. Have removed the old one.

**Comment by bingosummer** [comment]
@zikalino Thanks for your kindly review!
Just out of curiosity, if we keep only the latest version in index.json, can customers install the old versions of extension?

**Pull request merged**
