### PR TITLE
[db-up] Fix repeated typo in help strings

### PR DESCRIPTION
**Pull request by nachoalonsoportillo**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
`az mysql|postgres|sql up --help`

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [X] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [X] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by ambrahma — APPROVED** [review]

**Review by yonzhan — APPROVED** [review]

**Review by calvinhzy — CHANGES_REQUESTED** [review]
Please update the version in setup.py and history.srt to 1.0.0b1(we are following this new style of versioning) as otherwise this typo fix would not be published. Thanks.
image

**Comment by nachoalonsoportillo** [comment]
> Please update the version in setup.py and history.srt to 1.0.0b1(we are following this new style of versioning) as otherwise this typo fix would not be published. Thanks. image

Done in the latest commit. Thanks @calvinhzy!

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
@calvinhzy Can you review this PR again?

**Review by calvinhzy — APPROVED** [review]

**Pull request merged**
