### PR TITLE
Datta/set subscription reset nic

### PR DESCRIPTION
**Pull request by dkulkarni-ms**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

Updated command to set subscription for internal calls:
az vm repair reset-nic

Sample call:
az vm repair reset-nic -g -n --subscription --verbose

### General Guidelines

- [V] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [V] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [NA] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
vm repair

**Review by haagha — APPROVED** [review]
Looks good.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
