### PR TITLE
update index.json to vmware 0.7.2

### PR DESCRIPTION
**Pull request by ctaggart**
See https://github.com/Azure/az-vmware-cli/releases

### CODE REVIEW

**Comment by yonzhan** [comment]
vmware

**Comment by yungezz** [comment]
hi @qwordy, could you pls help to review?

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Please fix linter error

**Comment by ctaggart** [comment]
The fixed those lint errors in pull request #2047 to move the code here. If these lint errors need to be fixed, can we get that pull request merged and released? I can close this one.

```
Run custom pylint rules.
Running pylint on extensions...
************* Module azext_vmware.commands
/home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:17:8: E5001: Show command must use show_command or custom_show_command. (show-command)
/home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:31:8: E5001: Show command must use show_command or custom_show_command. (show-command)
/home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:37:8: E5001: Show command must use show_command or custom_show_command. (show-command)
/home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:43:8: E5001: Show command must use show_command or custom_show_command. (show-command)
```

**Comment by qwordy** [comment]
> 
> 
> The fixed those lint errors in pull request #2047 to move the code here. If these lint errors need to be fixed, can we get that pull request merged and released? I can close this one.
> 
> ```
> Run custom pylint rules.
> Running pylint on extensions...
> ************* Module azext_vmware.commands
> /home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:17:8: E5001: Show command must use show_command or custom_show_command. (show-command)
> /home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:31:8: E5001: Show command must use show_command or custom_show_command. (show-command)
> /home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:37:8: E5001: Show command must use show_command or custom_show_command. (show-command)
> /home/vsts/.azure/cliextensions/vmware/azext_vmware/commands.py:43:8: E5001: Show command must use show_command or custom_show_command. (show-command)
> ```

Yes. OK.

**Comment by ctaggart** [comment]
@qwordy, I fixed the pylint errors and made a new release. Please merge this first. Then let's work on getting the extension moved #2047.

**Pull request merged**
