### PR TITLE
Fix 'az webapp config ssl bind' for web apps in kubernetes environments 

### PR DESCRIPTION
**Pull request by StrawnSC**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [X] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
webapp

**Review by wangzelin007 — COMMENTED** [review]
Please update setup.py to release the new extension version.
And may I ask you to add some scenario tests for those new commands?

**Comment by panchagnula** [comment]
@StrawnSC is this PR ready for review & if so can we get this released on the extension soon. Thanks!

**Comment by StrawnSC** [comment]
@panchagnula sorry for the hold up -- I was taking some time to test and make sure that certificate binding was working for lima web apps and lima web app slots. I'm marking the PR ready for review 

@wangzelin007 thanks, I just updated the `setup.py`. About scenario tests, as we mentioned [here](https://github.com/Azure/azure-cli-extensions/pull/3934#discussion_r736787930), the process of setting up an AKS cluster to put kubernetes environments in is quite lengthy/time-consuming and doesn't lend itself well to automated testing. So far, we've been manually testing the commands. We're planning on finding a way to add scenario tests before integrating this into the core CLI

**Review by wangzelin007 — APPROVED** [review]

**Review by panchagnula — APPROVED** [review]
LGTM

**Pull request merged**
