### PR TITLE
[AKS] Cluster Autoscaler Profile

### PR DESCRIPTION
**Pull request by marwanad**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by yungezz** [comment]
similiar with https://github.com/Azure/azure-cli/pull/12139. Not ready for merge, reviewing only.

**Comment by marwanad** [comment]
updated PR, this is pending new 2020-02-01 SDK merge.

**Comment by qwordy** [comment]
Thanks for resolving comment https://github.com/Azure/azure-cli/pull/12139/files/8abfcad8ed2c9ada773d10e37f619bae6a87e573#diff-482f0023abb5b38daf295c1499448145

**Comment by qwordy** [comment]
Do we have test cases? I notice that in another same PR Azure/azure-cli#12139, there are test cases.

**Comment by marwanad** [comment]
> Do we have test cases? I notice that in another same PR [Azure/azure-cli#12139](https://github.com/Azure/azure-cli/pull/12139), there are test cases.

good catch, i'll add those.

**Pull request merged**
