### PR TITLE
Revert "spring-cloud: add support to enable/disable MSI (#1523)"

### PR DESCRIPTION
**Pull request by leonard520**
This reverts commit 666bab74e6a748f0ceb83dab8c8d4ba01adcce95.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S169

**Comment by qwordy** [comment]
Is there any reason?

**Comment by leonard520** [comment]
> Is there any reason?

We have another spring cloud feature whose backend is ready and want to deliver soon. 
https://github.com/Azure/azure-cli-extensions/pull/1419
In the meanwhile, our feature backend will be ready in another 3 weeks. 
That's why I need to revert the CLI part for ours so that my teammate can release theirs in time.
Sorry fro the inconvenience brought.

**Comment by yungezz** [comment]
> > Is there any reason?
> 
> We have another spring cloud feature whose backend is ready and want to deliver soon.
> #1419
> In the meanwhile, our feature backend will be ready in another 3 weeks.
> That's why I need to revert the CLI part for ours so that my teammate can release theirs in time.
> Sorry fro the inconvenience brought.

HI @leonard520 in future if you have features under development, not ready to release, you can still work on your Azure CLI PR at same time, just label Azure CLI PR with `do-not-merge`, we'll review it but not merge it.

**Pull request merged**
