### PR TITLE
{CI} pip Install testsdk remove the `--no-deps` parameter

### PR DESCRIPTION
**Pull request by wangzelin007**
---
CI raise error：
image
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1569165&view=logs&j=9c80867e-ccda-50f1-65bc-e11447f3cda9&t=8e28b004-aba6-5a56-67c2-9d40a66e3ed9

- Fix: Install testsdk with requirements.

CI raise error:
image

- Fix: pip Install azure-cli with `--editable` to include tests directory.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by wangzelin007** [comment]
Use #4822 to test Azure.azure-cli-extensions (Integration Tests):

**Review by FumingZhang — COMMENTED** [review]
Based on a trivial modification ([PR #4822](https://github.com/Azure/azure-cli-extensions/pull/4822)) to test if the fix works?

**Comment by wangzelin007** [comment]
> Based on a trivial modification ([PR #4822](https://github.com/Azure/azure-cli-extensions/pull/4822)) to test if the fix works?



> Based on a trivial modification ([PR #4822](https://github.com/Azure/azure-cli-extensions/pull/4822)) to test if the fix works?

Because integration test is a diff test，will use multiple pull requests to make sure it works.
Any suggestion ?

**Comment by FumingZhang** [comment]
No problem for me, just a little curious

**Comment by FumingZhang** [comment]
From [error log](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1569274&view=logs&j=9c80867e-ccda-50f1-65bc-e11447f3cda9&t=8e28b004-aba6-5a56-67c2-9d40a66e3ed9&l=1455), the tests folder from cli was not included?

image

**Comment by wangzelin007** [comment]
Use #4711  to test Azure.azure-cli-extensions (Integration Tests):

**Comment by wangzelin007** [comment]
> From [error log](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1569274&view=logs&j=9c80867e-ccda-50f1-65bc-e11447f3cda9&t=8e28b004-aba6-5a56-67c2-9d40a66e3ed9&l=1455), the tests folder from cli was not included? It was included before.
> 
> image

Becasue we wanted to be consistent with the azure-cli repo, we modified this script in [PR](https://github.com/Azure/azure-cli-extensions/pull/4811).

**Review by jiasli — APPROVED** [review]

**Pull request merged**
