### PR TITLE
Defaulting to rsa-sha2-256-cert-v01@openssh.com cert type

### PR DESCRIPTION
**Pull request by harshavmb**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az ssh

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by harshavmb** [comment]
This PR fixes [#4026](https://github.com/Azure/azure-cli-extensions/issues/4026). 
SHA-1 got deprecated & Newer Operating Systems removed the support (example RHEL9, Ubuntu 22.04, Mac Ventura 13.2). 

The current workaround `az ssh vm -n myvm -g mygroup -- -o PubkeyAcceptedKeyTypes=+ssh-rsa-cert-v01@openssh.com` defeats the safeguards put by OS as `rsa-sha2-256-cert-v01@openssh.com` is supposed to be safer than `ssh-rsa-cert-v01@openssh.com` & recommended by OpenSSH [here](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.certkeys#rev1.15) & [here](https://www.openssh.com/releasenotes.html). 

All in all, AAD login should default to the recommended cert type by OpenSSH or even better if it can be made configurable (not in the scope of this PR).

**Comment by yonzhan** [comment]
ssh

**Comment by harshavmb** [comment]
Having tested this locally, don't think it's going to work unless Azure AD supports certificate generation of this type. 
Correct me if my understanding is wrong..

**Comment by harshavmb** [comment]
Closing this PR as it's the problem with SSH server versions 7.4.. More details [here](https://bugzilla.mindrot.org/show_bug.cgi?id=3351).

**Pull request closed without merging**
