### PR TITLE
[AEM] Fix sig

### PR DESCRIPTION
**Pull request by MSSedusch**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by MSSedusch** [comment]
fixes #3019

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
@MSSedusch 
1. Can you fix the error in Github checks?
2. If you expect the change to take effect, please update history notes and version number.

**Comment by MSSedusch** [comment]
I'll have a look at the checks. @qwordy what do you mean by history notes? Can you send me a link to the file I need to update?

**Comment by MSSedusch** [comment]
@qwordy GitHub checks are green now and I updated the AEM version

**Comment by qwordy** [comment]
@MSSedusch Example file: src/blueprint/HISTORY.rst
I find `aem` does not have `HISTORY.rst`. No problem. If you have time, you can add one. Great software always has release notes. Do you want to merge now?

**Comment by MSSedusch** [comment]
@qwordy  I added the history. Thanks

**Pull request merged**
