### PR TITLE
CI conversion

### PR DESCRIPTION
**Pull request by tjprescott**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by haroldrandom** [comment]
Are this PR still active?

**Comment by tjprescott** [comment]
The purpose was to convert the Travis-based CI stages to use ADO. It seems like there may be some merge issues in there that aren't core to the conversion. You may want to preserve the PR in a separate branch if you plan to continue these efforts.

**Comment by haroldrandom** [comment]
Thanks @tjprescott 

We have a plan to migrate Trvais to ADO. Your efforts did inspire us.

Planning in the next Sprint S163

**Comment by haroldrandom** [comment]
Closed as all jobs done.

**Pull request closed without merging**
