### PR TITLE
multiple fixes for event grid cli modules + re-reocrding for tests

### PR DESCRIPTION
**Pull request by ahamad-MS**
---
Multiple fixes for Event Grid Extension module:
1. Fix issue #1268 (https://github.com/Azure/azure-cli-extensions/issues/1268) when trying to update event subscription that are not webhook .
2. Fix issue #11589 (https://github.com/Azure/azure-cli/issues/11589)
2. Remove old test cases that handled arguments that are expired by now.
3. re-record tests

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by ahamad-MS** [comment]
Hello qwordy @engzhou-msft @ zikalino .. Can we get someone assigned to review this work ASAP. thanks

**Comment by qwordy** [comment]
@jiasli Can you help review this PR. It's has something to do with subscription and tenant.

**Comment by fengzhou-msft** [comment]
@ahamad-MS there are multiple parameters that will be deprecated after current azure-cli verison 2.1.0 (If you search `expiration='2.1.0'` [here](https://github.com/Azure/azure-cli-extensions/blob/6d26538d7e02f45e75c8f355939b47aedcecaa03/src/eventgrid/azext_eventgrid/_params.py#L75)). Please confirm whether they can really be deprecated when we release azure-cli 2.2.0 on 3/10/2020. 

If not, please help change the expiration version to `3.0.0` using this ongoing PR. Thanks.

**Comment by ahamad-MS** [comment]
@qwordy @fengzhou-msft Can you please help with the remaining failure here? I removed all expired parameters and the test/validation is still failing indicate they exist which is not the case. Is this tool/infra issue ? Can you plz provide some feedback on what is needed from my side to suppress/fix this? Otherwise, can you please help merge this change? thanks

**Comment by ahamad-MS** [comment]
@qwordy .. @fengzhou-msft  Can you please help merge this PR?

thanks

**Comment by fengzhou-msft** [comment]
@ahamad-MS CI failed, you may need to update the sha256sum.

**Comment by ahamad-MS** [comment]
@fengzhou-msft All checks have passed.

**Pull request merged**
