### PR TITLE
Azure Cli Extensions - Cosmos DB Restore New Parameter

### PR DESCRIPTION
**Pull request by mayankkatwal**
---

### Background:

This pr is to add a parameter (--enable-public-network) to the az cosmos db restore cli command. This change requires NO sdk/api changes as this parameter is already existing and used by (create cosmos db cli command). The change is very minor and I have updated one of our tests to take in the parameter & captured its recording. 

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az cosmosdb restore --target-database-account-name <restore account name> --account-name <src account name> --restore-timestamp <restore ts> -g <resource group> --location <region> --enable-public-network <TRUE/FALSE>

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by mayankkatwal** [comment]
TODO: Capture new recording on modified test

**Comment by yonzhan** [comment]
Cosmos DB

**Comment by mayankkatwal** [comment]
@evelyn-ys I am noticing some of the pipeline tests failing. The one i modified and a few other restore tests are passing. Do you have any insight on why the rest of the pipeline tests are failing?

**Comment by kavskalyan** [comment]
Cosmos DB

**Pull request merged**
