### PR TITLE
[Spring Cloud] Update index manually for a hotfix.

### PR DESCRIPTION
**Pull request by LGDoor**
---
Update the hotfix release for this #4273 manually. 

It's built and uploaded separately since the latest changes on the main branch aren't expected to publish this time.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Spring Cloud

**Comment by yuwzho** [comment]
I am not sure this is a valid method to release a hotfix version. The problem we are facing is the main branch code contains some features under development and which should be released on Jan 17th with an official announcement. Thus @LGDoor forks the `2.12.2` version and applies the fix. 

The fix is on a critical path that make customer cannot deploy their apps to Azure Spring Cloud. 

Issues are 4267, 4269, 4270, 4271

**Comment by zhoxing-ms** [comment]
@LGDoor @yuwzho  May I ask what is the change in version `2.12.3`? Why can't the version `2.12.2` meet your requirements?

**Comment by zhoxing-ms** [comment]
In addition, if you want to release a new version for this extension, do not directly modify `index.json`. Instead, please modify `setup.py` and `HISTORY.rst` to trigger our CI pipeline to automatically generate the new version for `index.json`

**Comment by LGDoor** [comment]
> In addition, if you want to release a new version for this extension, please do not directly modify `index.json`. Instead, you should modify `setup.py` and `HISTORY.rst` to trigger our CI pipeline to automatically generate the new version for `index.json`

It's a manual release for this PR #4273. We can't trigger your pipeline since it will release the latest changes on the main branch which are still in development. So just made an local hotfix build for the online version following your [self-publish process](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md#publish)

**Comment by zhoxing-ms** [comment]
> > In addition, if you want to release a new version for this extension, please do not directly modify `index.json`. Instead, you should modify `setup.py` and `HISTORY.rst` to trigger our CI pipeline to automatically generate the new version for `index.json`
> 
> It's a manual release for this PR #4273. We can't trigger your pipeline since it will release the latest changes on the main branch which are still in development. So just made an local hotfix build for the online version following your [self-publish process](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md#publish)

I see, thanks~ By the way, may I ask could you guarantee the stability of this link? https://ascprivatecli.blob.core.windows.net/cli-extension/spring_cloud-2.12.3-py3-none-any.whl

**Comment by LGDoor** [comment]
> > > In addition, if you want to release a new version for this extension, please do not directly modify `index.json`. Instead, you should modify `setup.py` and `HISTORY.rst` to trigger our CI pipeline to automatically generate the new version for `index.json`
> > 
> > 
> > It's a manual release for this PR #4273. We can't trigger your pipeline since it will release the latest changes on the main branch which are still in development. So just made an local hotfix build for the online version following your [self-publish process](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md#publish)
> 
> I see, thanks~ By the way, may I ask could you guarantee the stability of this link? https://ascprivatecli.blob.core.windows.net/cli-extension/spring_cloud-2.12.3-py3-none-any.whl

Definitely. This storage is used for our private releases and kept available all the time.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
