### PR TITLE
Support new api version for resource-graph module

### PR DESCRIPTION
**Pull request by fenwickt**
- Updated sdk with the new track2 python package
- Added new param management_groups for querying the management groups
- Added new param allow_partial_scopes for not failing the query and returning partial results when query overreaches max scopes allowed by server
- Added new param skip_token so that users can paginate through the query
- Modified max value of top to be 1000 instead of 5000
- Changed cmdl output to dictionary format and extended the output with skip_token, count, total_results fields

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
resource-graph

**Comment by fenwickt** [comment]
Hi @jsntcy, the builds are failing with the access denied failure which doesn't seem to be related to this PR changes. Could you or someone from CLI team please help to understand what's wrong?

File "/home/vsts/work/1/s/scripts/ci/util.py", line 85, in get_whl_from_url
AssertionError: Request to https://pahealy.blob.core.windows.net/azext-fzf/fzf-1.0.2-py2.py3-none-any.whl failed with 403

**Comment by fenwickt** [comment]
@kairu-ms looks like jsntcy is OOF this week, could you please take a look at the changes?

The changes are from this PR https://github.com/Azure/azure-cli-extensions/pull/3213 , this time rebased with master properly :)

**Comment by kairu-ms** [comment]
@fenwickt Please don't use master branch. You should create a feature branch instead.

**Comment by fenwickt** [comment]
> @fenwickt Please don't use master branch. You should create a feature branch instead.

Thans for the feedback! Sorry, I thought it doesn't matter since no one else is adding changes to my cloned repo. Will use the feature branch from now on!

**Pull request closed without merging**
