### PR TITLE
[AKS] Remove preview from azure policy addon for cli extension

### PR DESCRIPTION
**Pull request by ruchikaguptaa**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Review by robbiezhang — APPROVED** [review]

**Comment by yonzhan** [comment]
AKS

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
hi @arrownj could you pls review the PR?

**Comment by ruchikaguptaa** [comment]
Please don't merge this PR as of now. There are an open question for GA. I will update by tomorrow.

**Comment by ruchikaguptaa** [comment]
Update on the above comment - gtg from AKS side. Pending merge from CLI.

**Review by arrownj — COMMENTED** [review]
no `is_preview=True` in source code ?

**Comment by ruchikaguptaa** [comment]
@arrownj we don't have `is_preview=True` for azure policy addon. I see it only for node public ip feature. Is there a problem due to that? I think that might be a new flag.

**Comment by arrownj** [comment]
> @arrownj Xiaojian Xu FTE we don't have `is_preview=True` for azure policy addon. I see it only for node public ip feature. Is there a problem due to that? I think that might be a new flag.

It's just a reminder that we also need to remove `is_preview` flag if it exists before. I'm OK with it now, thanks.

**Review by arrownj — APPROVED** [review]

**Pull request merged**
