### PR TITLE
[Release] Update index.json for extension [ vmware ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ vmware ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=745089

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/1c4e526df91709053ca539b0201486f76376f36b

### CODE REVIEW

**Review by qwordy — APPROVED** [review]

**Comment by yonzhan** [comment]
vmware

**Comment by qwordy** [comment]
PR: https://github.com/Azure/azure-cli-extensions/pull/2998

**Comment by qwordy** [comment]
@ctaggart Can you have a look at the error?
https://dev.azure.com/azure-sdk/public/_build/results?buildId=745095&view=logs&j=a49103b8-20d1-5a8c-534b-bda9ab69fa51&t=f07883fb-9b2e-5ef1-366a-e8e57e798ca5&l=3548

**Comment by ctaggart** [comment]
@qwordy, looks like the 2.0.0 is missing stuff:

image

The downloads are from:
- https://azcliprod.blob.core.windows.net/cli-extensions/vmware-2.0.0-py2.py3-none-any.whl
- https://azcliprod.blob.core.windows.net/cli-extensions/vmware-1.0.0-py2.py3-none-any.whl
- https://github.com/virtustream/az-vmware-cli/releases/download/0.7.2/vmware-0.7.2-py2.py3-none-any.whl

This produces the error locally for me:
```
python .\scripts\refdoc\generate.py --extension-file C:\Users\cataggar\Downloads\vmware-2.0.0-py2.py3-none-any.whl
```

There are no problems when I build locally:
```
cd src/vwmare
python setup.py bdist_wheel -d ../../dist
python .\scripts\refdoc\generate.py --extension-file .\dist\vmware-2.0.0-py2.py3-none-any.whl
```

Any idea what went wrong with the vmware-2.0.0-py2.py3-none-any.whl build?

**Comment by qwordy** [comment]
@ctaggart I am finding out what happened.

**Comment by cjain85** [comment]
@qwordy Can we have ETA for this please ? We require this for our Ignite Private preview . We would like to keep couple of days buffer to test everything with new cli released as well

**Comment by yungezz** [comment]
hi @qwordy @fengzhou-msft is the extension installation issue resolved? is this extension ready to release? thanks

**Comment by fengzhou-msft** [comment]
@ctaggart you need a `__init__.py` file like this [one](https://github.com/Azure/azure-cli-extensions/blob/master/src/healthbot/azext_healthbot/vendored_sdks/__init__.py) under `vendored_sdks` folder, otherwise it will not be packaged into the wheel.

**Pull request closed without merging**
