### PR TITLE
Init commit for new version of CLI commands of self-help extensions.

### PR DESCRIPTION
**Pull request by kenabd**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
image

- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
image

- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by jsntcy** [comment]
> ❌Azure CLI Extensions Breaking Change Test

@kenabd, please follow [deprecate arguments](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments) to add deprecation message for the removed argument in this change without removing it and remove the argument in breaking change window (next month), so that customers can have buffer time to adjust their scripts for breaking changes.

**Comment by kenabd** [comment]
> > ❌Azure CLI Extensions Breaking Change Test
> 
> @kenabd, please follow [deprecate arguments](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments) to add deprecation message for the removed argument in this change without removing it and remove the argument in breaking change window (next month), so that customers can have buffer time to adjust their scripts for breaking changes.

I have addressed this issue and added deprecation message for the scope parameter.

**Comment by necusjz** [comment]
@kenabd could you please provide the link of the pr in aaz repo?

**Comment by kenabd** [comment]
> > ❌Azure CLI Extensions Breaking Change Test
> 
> @kenabd, please follow [deprecate arguments](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments) to add deprecation message for the removed argument in this change without removing it and remove the argument in breaking change window (next month), so that customers can have buffer time to adjust their scripts for breaking changes.

Here is the PR on AAZ repo:
https://github.com/Azure/aaz/pull/456

**Comment by kenabd** [comment]
> @kenabd could you please provide the link of the pr in aaz repo?

Here is the PR on AAZ repo:
https://github.com/Azure/aaz/pull/456

**Review by necusjz — APPROVED** [review]

**Pull request merged**
