### PR TITLE
AKS CLI Extension: revert default value change for vmss+slb

### PR DESCRIPTION
**Pull request by xuto2**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by jluk** [comment]
@ganeshatmicrosoft could you please get a fast review in since this is fixing a breaking chg?

**Comment by jluk** [comment]
@zikalino or @yugangw-msft could someone help us get this merged since we are trying to fix some incidents with this

**Comment by yugangw-msft** [comment]
CC: @yonzhan

**Comment by jluk** [comment]
Thank you very much @yugangw-msft

**Comment by seanmck** [comment]
Closes #924

**Pull request merged**
