### PR TITLE
Updating the Azure DevOps Extension version to 0.19.0.

### PR DESCRIPTION
**Pull request by chandrasekharmudili**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:
a
- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
devops

**Comment by chandrasekharmudili** [comment]
Created a new release for azure-devops-cli-extension. (https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=130286&view=logs&j=516a99d3-db7c-5136-ef8c-05c63e967392)

**Comment by yungezz** [comment]
hi @houk-ms could you pls help to support this release? thanks. cc @fengzhou-msft

**Comment by fengzhou-msft** [comment]
@chandrasekharmudili can you take a look at the Linter [error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=757958&view=logs&j=ccdac6d3-465a-5ada-8819-d5b4a6b3a631&t=ffdbba7d-e523-5908-c7bf-0703bafb81b0&l=438). A show command should be defined with `show_command` or `custom_show_command` to get the right exit code in case of 404.

**Comment by fengzhou-msft** [comment]
@chandrasekharmudili any update?

**Comment by gauravsaralMs** [comment]
> @chandrasekharmudili can you take a look at the Linter [error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=757958&view=logs&j=ccdac6d3-465a-5ada-8819-d5b4a6b3a631&t=ffdbba7d-e523-5908-c7bf-0703bafb81b0&l=438). A show command should be defined with `show_command` or `custom_show_command` to get the right exit code in case of 404.

@fengzhou-msft : can you please re-run the instance once again because the build mentioned here has expired.

**Comment by kairu-ms** [comment]
@gauravsaralMs Please resolve conflicts first.

**Pull request closed without merging**
