### PR TITLE
Added new stack-hci-vm cli version 0.1.11

### PR DESCRIPTION
**Pull request by damanMSFT**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
  azdev style stack-hci-vm doesn't work
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by jsntcy** [comment]
@damanMSFT, please fix the CI error first.
From the error "AssertionError: {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.5'} != {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.11'}", we can see that the metadata doesn't match between the wheel file in https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and the metadata you added to index.json this PR. 
I downloaded https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and found azext_metadata.json had the following stuff which is obviously wrong - the version should not be `0.1.5`, but should be `0.1.11`. So please fix your package first (upload a correct package to your storage)

{
    "azext.isPreview": true,
    "azext.minCliCoreVersion": "2.15.0",
    "classifiers": [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License"
    ],
    "extensions": {
        "python.details": {
            "contacts": [
                {
                    "email": "azpycli@microsoft.com",
                    "name": "Microsoft Corporation",
                    "role": "author"
                }
            ],
            "document_names": {
                "description": "DESCRIPTION.rst"
            },
            "project_urls": {
                "Home": "https://msazure.visualstudio.com/msk8s/_git/azstackhci-util?version=GBmain"
            }
        }
    },
    "generator": "bdist_wheel (0.30.0)",
    "license": "MIT",
    "metadata_version": "2.0",
    "name": "stack-hci-vm",
    "summary": "Microsoft Azure Command-Line Tools AzureStackHCIClient Extension ",
    "version": **"0.1.5"**
}

**Comment by hvedati** [comment]
> @damanMSFT, please fix the CI error first. From the error "AssertionError: {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.5'} != {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.11'}", we can see that the metadata doesn't match between the wheel file in https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and the metadata you added to index.json this PR. I downloaded https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and found azext_metadata.json had the following stuff which is obviously wrong - the version should not be `0.1.5`, but should be `0.1.11`. So please fix your package first (upload a correct package to your storage)
> 
> { "azext.isPreview": true, "azext.minCliCoreVersion": "2.15.0", "classifiers": [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "License :: OSI Approved :: MIT License" ], "extensions": { "python.details": { "contacts": [ { "email": "[azpycli@microsoft.com](mailto:azpycli@microsoft.com)", "name": "Microsoft Corporation", "role": "author" } ], "document_names": { "description": "DESCRIPTION.rst" }, "project_urls": { "Home": "https://msazure.visualstudio.com/msk8s/_git/azstackhci-util?version=GBmain" } } }, "generator": "bdist_wheel (0.30.0)", "license": "MIT", "metadata_version": "2.0", "name": "stack-hci-vm", "summary": "Microsoft Azure Command-Line Tools AzureStackHCIClient Extension ", "version": **"0.1.5"** }

@jsntcy if we want to make this version no longer a preview version should we remove this tag entirely azext.isPreview or set it to false?

**Comment by jsntcy** [comment]
> > @damanMSFT
> >             
> >             Daman Tekchandani
> >             FTE, please fix the CI error first. From the error "AssertionError: {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.5'} != {'aze[745 chars]ine Tools AzureStackHCIClient Extension ', 'version': '0.1.11'}", we can see that the metadata doesn't match between the wheel file in https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and the metadata you added to index.json this PR. I downloaded https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/stack_hci_vm-0.1.11-py3-none-any.whl" and found azext_metadata.json had the following stuff which is obviously wrong - the version should not be `0.1.5`, but should be `0.1.11`. So please fix your package first (upload a correct package to your storage)
> > { "azext.isPreview": true, "azext.minCliCoreVersion": "2.15.0", "classifiers": [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "License :: OSI Approved :: MIT License" ], "extensions": { "python.details": { "contacts": [ { "email": "[azpycli@microsoft.com](mailto:azpycli@microsoft.com)", "name": "Microsoft Corporation", "role": "author" } ], "document_names": { "description": "DESCRIPTION.rst" }, "project_urls": { "Home": "https://msazure.visualstudio.com/msk8s/_git/azstackhci-util?version=GBmain" } } }, "generator": "bdist_wheel (0.30.0)", "license": "MIT", "metadata_version": "2.0", "name": "stack-hci-vm", "summary": "Microsoft Azure Command-Line Tools AzureStackHCIClient Extension ", "version": **"0.1.5"** }
> 
> @jsntcy Yu Chen FTE if we want to make this version no longer a preview version should we remove this tag entirely azext.isPreview or set it to false?

Which tag?

**Comment by damanMSFT** [comment]
@jsntcy Harika was asking about the parameter "azext.isPreview". 

Also can you approve the PR. Checks are passing now.

**Review by pathuang-sia — APPROVED** [review]

**Comment by jsntcy** [comment]
Yes, you can remove that tag as long as you change the version of your extension as well.
We will support new versioning for extension and `0.x.x` is not recommended any longer. The version will start from `1.0.0` (stable) or `1.0.0b1` (preview). You can find more details in https://github.com/Azure/azure-cli/blob/dev/doc/extensions/versioning_guidelines.md.
You can update version according for your next release.

**Review by jsntcy — APPROVED** [review]

**Comment by damanMSFT** [comment]
@jsntcy can you merge the branch as well? As it says I am not an authorized user to do it.

**Review by necusjz — APPROVED** [review]

**Pull request merged**
