### PR TITLE
[azure-iot] IoT extension version 0.9.8

### PR DESCRIPTION
**Pull request by digimaun**
Content for this release https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.9.8

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by digimaun** [comment]
The verify extension index job failure is from an unrelated issue (log analytics solution)
image

**Comment by yonzhan** [comment]
add to S174

**Comment by yungezz** [comment]
hi @yonzhan Iot extensions are supported by your team right?

**Comment by yonzhan** [comment]
@yungezz feng and jianhui mentioned before that they will rotate to support new extension release. I just changed assignee to jianhui for this.

**Comment by yungezz** [comment]
thanks will sync with @fengzhou-msft offline

**Comment by yungezz** [comment]
hi @haroldrandom is this PR ok to merge? thanks.

**Pull request merged**
