### PR TITLE
[quantum] Assign "Storage account contributor" role to workspace for linked StorageAccount

### PR DESCRIPTION
**Pull request by ashwinmayya**
Previously, we assigned a contributor role to the storage account for the workspace. This PR changes it to the "storage account contributor" role. This is done in order to be compatible with the new "Quantum Workspace Owner" built-in role that allows constrained role assignment of storage account contributor.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
quantum

**Review by kikomiss — APPROVED** [review]
LGTM

**Comment by jsntcy** [comment]
Do we have any tests to cover this change?

**Comment by ashwinmayya** [comment]
> Do we have any tests to cover this change?

Yes these changes are covered by existing tests that create the workspace and submit jobs. There should be no change in  functionality for existing users, hence no new tests.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
