### PR TITLE
Support library panels for dashboard sync command

### PR DESCRIPTION
**Pull request by ABZhang0**
### Related command
```az grafana dashboard sync```

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by ABZhang0** [comment]
Hi @AllyW, fixed the CI tests on my local machine but looks like the build pipeline has expired login creds and so the tests are unable to run. Am I able to restart the process myself or can you do it?

**Comment by wangzelin007** [comment]
@ABZhang0
You should replace those old recording files with the latest recording files in your local machine, not delete all of them.
We need those recording files to check all your test cases in recording mode.
Recording mode will not create Azure resources, but once you deleted all recording files, test framework will try to create Azure resources, and finally failed in the `az login` steps.
image

**Comment by ABZhang0** [comment]
> @ABZhang0 You should replace those old recording files with the latest recording files in your local machine, not delete all of them. We need those recording files to check all your test cases in recording mode. Recording mode will not create Azure resources, but once you deleted all recording files, test framework will try to create Azure resources, and finally failed in the `az login` steps. image

Hi @wangzelin007, that makes sense! However, some of the tests are executing CLI commands to show sensitive information (API key, service account token). The test recordings are flagged for exposing secrets - is there a way to scrub them from the recordings, or is it an accepted practice to upload everything in the recordings to source control?

**Comment by AllyW** [comment]
> > > ## ⚠️ Release Suggestions
> > > ### Module: amg
> > > 
> > > * ⚠️ Please update `VERSION` to be `1.3.3` in `src/amg/setup.py`
> > > 
> > > #### Notes
> > > 
> > > * Stable/preview tag is inherited from last release. If needed, please add `stable`/`preview` label to modify it.
> > > * Major/minor/patch/pre increment of version number is calculated by pull request code changes automatically. If needed, please add `major`/`minor`/`patch`/`pre` label to adjust it.
> > > * For more info about extension versioning, please refer to [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)
> > 
> > 
> > @ABZhang0 please fix CI failed tests and correct version number as suggested above, thanks
> 
> Hi @AllyW, fixed the CI tests on my local machine but looks like the build pipeline has expired login creds and so the tests are unable to run. Am I able to restart the process myself or can you do it?

the pipeline can be automatically run once your make any change to this pr's branch.

**Review by wangzelin007 — APPROVED** [review]

**Comment by ABZhang0** [comment]
Hi @AllyW, can you review the changes? It should be good to check in now

**Review by AllyW — APPROVED** [review]

**Pull request merged**
