### PR TITLE
aks: add `--binding-selector` to `pod-identity add` command

### PR DESCRIPTION
**Pull request by bcho**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Review by levimm — APPROVED** [review]

**Comment by yungezz** [comment]
both this one and PR https://github.com/Azure/azure-cli-extensions/pull/3254/files upgrades aks-preview to 0.5.9. Pls coordinate on release. suggest to make version bump in seperate PR, to allow all new feature for new release has chance to checkin

**Comment by bcho** [comment]
> There're 3 PRs requesting new release: this one, https://github.com/Azure/azure-cli-extensions/pull/3254/files , https://github.com/Azure/azure-cli-extensions/pull/3249/files upgrades aks-preview to 0.5.9. Pls coordinate on release. suggest to make version bump in seperate PR, to allow all new feature for new release has chance to checkin

Sure, I will discuss with my team to sort out the release

**Comment by bcho** [comment]
I had dropped the version bump & history changes. I will send these changes in a follow up PR. @yungezz PTAL

**Comment by bcho** [comment]
@yungezz @fengzhou-msft could you help review t his pr? Thanks!

**Review by yungezz — APPROVED** [review]

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
