### PR TITLE
Remove enterprise-edge extension

### PR DESCRIPTION
**Pull request by StrawnSC**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by StrawnSC** [comment]
@yonzhan we've already [moved all of these commands to the core CLI ](https://github.com/Azure/azure-cli/pull/22818) and would like to prevent future customers from installing the `enterprise-edge` extension. I'm assuming that we can do that by removing the source from this repo and removing `enterprise-edge` entry from the index.json. Is that correct?

**Comment by yonzhan** [comment]
@kairu-ms @jsntcy for awareness

**Comment by zhoxing-ms** [comment]
@StrawnSC Yes, the source code can be removed directly.
But if the `az extension add -n enterprise-edge` command is used in some users' scripts to install this extension, remove index.json may cause breaking change to them, so it is recommended to remove index.json during the breaking change window of CLI (Build Event and Ignite Event)
For more details about CLI breaking change process, please refer to this doc [breakingchange_release_process.md](https://msazure.visualstudio.com/One/_git/AzureCliTools-Wiki?version=GBzhoxing-test/update-breaking-changes&path=/src/teams_docs/azps_docs/breakingchange_release_process.md)

**Comment by StrawnSC** [comment]
@zhoxing-ms are we good to merge + release this?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
