### PR TITLE
Add new commands and restructure command groups for AOSM extension

### PR DESCRIPTION
**Pull request by jddarby**
This PR adds a new command group to the AOSM extension and adds extra commands that allow users to change the state of artifact manifest, artifact version, config group schema, NFDV and NSDV resources.

The new commands have been generated using the aaz development tool.

Command groups have been changed in the following way:
- The `publisher` command group has been added.
     - e.g. can now run `az aosm publisher artifact-manifest update-state ...`    

Updated command tree:
```
aosm
    nfd
        - build
        - delete
        - generate-config
        - publish
    nsd
        - build
        - delete
        - generate-config
        - publish
    publisher
        artifact-manifest
            - list
            - list-credential
            - show
            - update-state
        artifact-store
            artifact
                - list
                version
                    - list
                    - update-state
        cg-schema
            - list
            - show
            - update-state
        nfd
            - list
            - show
            - update-state
        nsd
            - list
            - show
            - update-state
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
`az aosm`

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by Cyclam** [comment]
I don't like the inconsistent styling of the subcommands:

- artifact-manifest
- artifact-store
- cg-schema
- nfd
- nsd

This kind of thing tend to frustrate users as they have to remember which style the specific command uses. Is it possible to have long and short aliases?  e.g. 

- either `artifact-manifest` or `am`
- either `configuration-group-schema` or `cgs`
- either `network-function-definition` or `nfd`

**Comment by Cyclam** [comment]
Need to update the history file, probably as a 'breaking' change, though as we're still in preview that's OK.

Also need to be clear the version cannot be bumped (i.e. the change rolled out to end users) until the docs have been updated. I think we need to have a clear release process for this change.

**Comment by pjw711** [comment]
I'm happy with the high level splitting out of 'onboard' and 'publisher'. 

`aosm
    onboard
        nfd
            - build
            - delete
            - generate-config
            - publish
        nsd
            - build
            - delete
            - generate-config
            - publish`

I don't love that the onboarding flow is split into nfd and nsd: if I'm onboarding an NF I want to be able to deploy it. I shouldn't need to know the difference between an nfd and nsd to start with: it's the workflow I care about.  Slightly devil's advocate, but is there any workflow where you want to build/rebuild an NFD without an NSD? I'm happy to defer this debate to a future PR, though. 

Related question: when we deliver the function to upload container images separately from the publish command, where will that command go in this hierarchy?

**Comment by jddarby** [comment]
@kairu-ms @necusjz, this PR is now ready for review.

The new commands have been generated using the aaz dev tool and have been reviewed by my team (who own this extension).

I have tested these each of the new commands to verify they work but I have not written any UTs for them as this is autogenerated code.

We are not planning to release this new feature yet as we are doing more work and will release once that is completed.

Please let me know if there is anything else you need from me.

**Comment by jddarby** [comment]
@necusjz, okay. The other work is a significant refactor of the existing code. Is it preferable that we combine all changes that we want in a release into one PR, regardless of amount of change? Or would you suggest a different approach?

**Comment by necusjz** [comment]
@jddarby Let's raise another PR, thanks for your understanding.

**Pull request closed without merging**
