### PR TITLE
[AKS] Support disable local accounts

### PR DESCRIPTION
**Pull request by norshtein**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Review by zqingqing1 — CHANGES_REQUESTED** [review]
please add test for the "--disable-local-accounts"

**Comment by norshtein** [comment]
Hi @fengzhou-msft , I've updated the test for this feature. And I noticed there is no active PR for aks-preview extension, so I also bumped version. Could you please help review the PR?

**Comment by norshtein** [comment]
Hi @zqingqing1 , I just added test for the feature :D

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
@zqingqing1 can you take a look again at this PR?

**Comment by norshtein** [comment]
Rebased upon latest master. @fengzhou-msft I think we're ready to go, could you please help merge the PR? Thanks!

**Comment by fengzhou-msft** [comment]
> Rebased upon latest master. @fengzhou-msft I think we're ready to go, could you please help merge the PR? Thanks!

I'm not able the merge this PR as merging is blocked by @zqingqing1's requested change.

**Comment by norshtein** [comment]
Thanks for the explanation, I've pinged Qingqing for this.

**Review by zqingqing1 — APPROVED** [review]
lgtm

**Pull request merged**
