### PR TITLE
Renamed vmware-cs extension to csvmware (extension in preview)

### PR DESCRIPTION
**Pull request by shivam-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S167

**Comment by shivam-msft** [comment]
One of the check failed as it ran for more than 60 minutes. How can we fix that?

**Comment by yungezz** [comment]
rerunning failed one

**Comment by yungezz** [comment]
hi @shivam-msft the branch need to be sync with master

**Comment by shivam-msft** [comment]
All checks pass now!

**Comment by yungezz** [comment]
hi @shivam-msft  pls merge from master then the PR ready to go

**Comment by shivam-msft** [comment]
> hi @shivam-msft pls merge from master then the PR ready to go

Hey @yungezz, I've merged from master

**Pull request merged**
