### PR TITLE
[Serial-Console] Fix pair mapping region for eastus to westus

### PR DESCRIPTION
**Pull request by rhkodiak**
The changes in the pull request are to address a problem found in the azure cli serial-console extension where an error was being thrown for eastus connections because there wasn't a pair region mapping for westus. The code changes add the eastus to westus region mappings to fix this issue.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az serial-console connect -g MyResourceGroup -n MyVmName

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Serial-Console

**Comment by msftvito** [comment]
Can this be looked at?

**Comment by yonzhan** [comment]
Please fix CI issues first.

**Comment by msftvito** [comment]
@rhkodiak there's other changes mixed in with the one for my issue. Can you resolve the issues so the PR goes through?

**Comment by kairu-ms** [comment]
Hi @rhkodiak You may need to record the failed tests again.

**Comment by msftvito** [comment]
@rhkodiak are you able to resolve the failing tests?

**Comment by rhkodiak** [comment]
> @rhkodiak are you able to resolve the failing tests?

Yes I will resolve this today

**Comment by kairu-ms** [comment]
Hi @rhkodiak, according to the CI result, it seems the azure-mgmt-resource sdk is not the latest in your Local machine. Please pull the latest change of dev branch of `azure-cli` repo and run `azdev setup` again to update the sdks. After that you can record the tests again.

**Comment by rhkodiak** [comment]
> Hi @rhkodiak, according to the CI result, it seems the azure-mgmt-resource sdk is not the latest in your Local machine. Please pull the latest change of dev branch of `azure-cli` repo and run `azdev setup` again to update the sdks. After that you can record the tests again.

Hi @kairu-ms, I ran the instructions you provided and everything looks good now so ready for you to review.  Thanks for the help!

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
