### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by j-martens**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by haroldrandom** [comment]
Could you please take a look the error message that CI reported?

**Comment by haroldrandom** [comment]
@j-martens Is this PR still active?

**Comment by j-martens** [comment]
@haroldrandom yes it is.

**Comment by haroldrandom** [comment]
@j-martens Please take a look the CI's output and fix them first

**Comment by j-martens** [comment]
@haroldrandom I don't work on this team, thus the public PR. It wasn't making errors when I created it many months ago. I don't know what happened. @tjprescott - can you help here?

**Comment by tjprescott** [comment]
I'm no longer on the CLI team, but you'd need to pull the changes from master and fire off another build. The build is old enough that it's no longer available for inspection.

**Comment by haroldrandom** [comment]
@j-martens CI Job Verify Extensions Index is used to compare metadata info between wheel from downloadURL and index.json you provide.

You updated the project_url in index.json but didn't modify project_url corresponding in setup.py of your extensions. That's why it failed CI.

To fix this, please:
1.  update project_url in setup.py in your extension source code folder with the same value.
2.  re-build and upload a new wheel package to your container.
3. **REMEMBER to update sha256sum checksum in your index.json**
4. push changes here.

I believe this time it can work.

**Comment by haroldrandom** [comment]
Closed as long time not active.

**Pull request closed without merging**
