### PR TITLE
{all services] TOC | fixed incorrect plural product names

### PR DESCRIPTION
**Pull request by dbradish-microsoft**
In aligning with the Azure PowerShell reference TOC, _Account_ should be plural _Accounts_, and _App Services_ should be singular _App Service_.

### CODE REVIEW

**Comment by yonzhan** [comment]
all services

**Review by yonzhan — APPROVED** [review]

**Comment by dbradish-microsoft** [comment]
@jsntcy / @kairu-ms , This PR is failing on _Verify reference docs_, but I don't understand the problem.  Can you please assist?  
image

**Comment by dbradish-microsoft** [comment]
#sign-off

**Comment by dbradish-microsoft** [comment]
@jsntcy, can you kindly review and approve?  Thank you.

**Comment by dbradish-microsoft** [comment]
@yonzhan , Even though I seem to have permission to merge in this repo, I don't as I feel this is an Engineering repo.  Can you please have someone on your team merge this PR?  Thank you.

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
