### PR TITLE
Updated SapHana extension

### PR DESCRIPTION
**Pull request by PakDLiu**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by PakDLiu** [comment]
I don't quite understand the lint error, can someone from the CLI extension explain please?

**Comment by qwordy** [comment]
@PakDLiu
```
/home/vsts/.azure/cliextensions/sap-hana/azext_hanaonazure/commands.py:19:8: E5001: Show command must use show_command or custom_show_command. (show-command)
/home/vsts/.azure/cliextensions/sap-hana/azext_hanaonazure/commands.py:30:8: E5001: Show command must use show_command or custom_show_command. (show-command)
/home/vsts/.azure/cliextensions/sap-hana/azext_hanaonazure/commands.py:38:8: E5001: Show command must use show_command or custom_show_command. (show-command)
```
Refer to https://github.com/Azure/azure-cli/blob/373edd533933e2d115bb8eecab38642db4aea2e0/doc/command_guidelines.md#standard-command-types

**Review by qwordy — APPROVED** [review]

**Comment by PakDLiu** [comment]
Thanks for the approval! When can you merge?

**Comment by qwordy** [comment]
> 
> 
> Thanks for the approval! When can you merge?

Merged

**Pull request merged**
