### PR TITLE
{k8s-extension} fixes Azure/azure-cli-extensions#5384

### PR DESCRIPTION
**Pull request by navba-MSFT**
fixes Azure/azure-cli-extensions#5384

While running the CLi command:  az k8s-extension extension-types list   it fails with below error:

```
(NoRegisteredProviderFound) No registered resource provider found for location 'westeurope' and API version '2022-01-15-preview' for type 'connectedClusters'. The supported api-versions are '2020-01-01-preview, 2021-03-01, 2021-04-01-preview, 2021-10-01, 2022-05-01-preview'. The supported locations are 'westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, westus3, eastasia, canadacentral'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'westeurope' and API version '2022-01-15-preview' for type 'connectedClusters'. The supported api-versions are '2020-01-01-preview, 2021-03-01, 2021-04-01-preview, 2021-10-01, 2022-05-01-preview'. The supported locations are 'westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, westus3, eastasia, canadacentral'.

```
The api-version should be : 2022-04-02-preview 

Invoking the below with this api-version works fine: az rest --method GET --uri https://management.azure.com/subscriptions/XXXXX-XXX-XXXX-XXX/resourceGroups/MyRGName/providers/Microsoft.ContainerService/**MyClusterType**/MyClusterName/providers/Microsoft.KubernetesConfiguration/extensions?api-version=2022-04-02-preview

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
k8s-extension

**Comment by zhoxing-ms** [comment]
Do you need to upgrade the extension version to release the bug fix? If so, please also modify the `HISTORY.rst` and `setup.py`

**Review by zhoxing-ms — APPROVED** [review]

**Comment by navba-MSFT** [comment]
@zhoxing-ms Thanks for approving this. Could you also merge this once the tests have been successfully completed ?

**Pull request merged**
