### PR TITLE
Update version and history info for 'az quantum' extension

### PR DESCRIPTION
**Pull request by ricardo-espinoza**
Release pull request for version 0.2.0 of `quantum`  extension.

### CODE REVIEW

**Comment by yonzhan** [comment]
quantum

**Comment by qwordy** [comment]
Pending on other PRs.

**Comment by qwordy** [comment]
@ricardo-espinoza Is it ready to merge?

**Comment by ricardo-espinoza** [comment]
@qwordy : yes, we are ready to release now. Thanks for the help with this.

**Review by qwordy — APPROVED** [review]

**Pull request merged**
