### PR TITLE
Pipeline cli extension automation onboarding

### PR DESCRIPTION
**Pull request by tiramisuq**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by haroldrandom** [comment]
Context?

**Comment by haroldrandom** [comment]
better to list the background and usage in the file to inform people who don't know the context.
Besides, can you put into a folder like `scripts/ci/swagger`?

**Comment by tiramisuq** [comment]
Cli extension codegen intends to use pipeline to generate codes automatically and this file is used as configuration used in pipeline. For current work flow, it should reside in the direct folder under the repo.

**Comment by haroldrandom** [comment]
@jsntcy Please take a look

**Pull request merged**
