### PR TITLE
{CI} Use GitHub Actions to trigger the ADO OneBranch Extension Release Pipeline

### PR DESCRIPTION
**Pull request by wangzelin007**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
CI

**Comment by bebound** [comment]
Although this is the only solution to trigger ADO pipeline.
However, it lacks batch CI support, posing a risk of earlier commits task overwriting `index.json` from later ones.

**Comment by wangzelin007** [comment]
> Although this is the only solution to trigger ADO pipeline. However, it seems that it lacks batch CI support, posing a risk of earlier commits task overwriting `index.json` from later ones.
> 
> Can we use [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to eliminate the overwrite probability? For example, only one job can run, and after trigger ADO, it wait for several minutes?

Thank you!
This is exactly what I'm looking for~

**Review by bebound — APPROVED** [review]

**Comment by wangzelin007** [comment]
image

**Pull request merged**
