### PR TITLE
[Datadog] Add `datadog terms list` command

### PR DESCRIPTION
**Pull request by fengzhou-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Datadog

**Comment by yungezz** [comment]
hi @limingu could you pls help to review? thanks

**Review by yungezz — APPROVED** [review]

**Comment by qwordy** [comment]
Did you generate again?

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft, all the changes are auto-generated except the test code and api version, right?

Yes. The code is auto-generated with track 1. I used the latest version of autorest.az, there were some changes in other places as well, but I only picked up the changes for the `datadog terms list` command for this PR.

**Comment by fengzhou-msft** [comment]
> Did you generate again?

yes, for the new command.

**Review by qwordy — APPROVED** [review]

**Review by limingu — APPROVED** [review]

**Pull request merged**
