### PR TITLE
Add quantum version check

### PR DESCRIPTION
**Pull request by warren-jones**
Once per day, the Azure CLI quantum extension will perform a version check as part of any command.  If the latest available version of the extension is greater than the one installed, the user will see a yellow warning message in the following format:
```
Version 0.7.0 of the quantum extension is installed locally, but version 0.8.0 is now available.
You can use 'az extension update -n quantum' to upgrade.
```
If the latest available version number cannot be retrieved, or it matches the installed version, no message is shown. We won’t fail the command if we can’t get the most recent version, we’ll just proceed.  We won’t check again until the date changes or the context gets cleared.

This implementation will not cover commands that our extension does not handle directly, like “--help” calls, since they are directly responded by the ‘az’ tool.

### CODE REVIEW

**Comment by yonzhan** [comment]
quantum

**Review by kairu-ms — APPROVED** [review]

**Review by kairu-ms — CHANGES_REQUESTED** [review]
`__init__` function of `CommandLoader` will be run when any cli command is executed. Could you move version check logic in `load_arguments` function so that it only runs when Quantum command is executed.

**Comment by ricardo-espinoza** [comment]
> `__init__` function of `CommandLoader` will be run when any cli command is executed. Could you move version check logic in `load_arguments` function so that it only runs when Quantum command is executed.

Thanks @kairu-ms . Just one question... this change is only in the QuantumCommandLoader, why would this be executed if a non-quantum cli command is executed?

**Comment by warren-jones** [comment]
Moved version-check logic to load_arguments, as requested by @kairu-ms

**Review by ricardo-espinoza — APPROVED** [review]

**Comment by kairu-ms** [comment]
> > `__init__` function of `CommandLoader` will be run when any cli command is executed. Could you move version check logic in `load_arguments` function so that it only runs when Quantum command is executed.
> 
> Thanks @kairu-ms . Just one question... this change is only in the QuantumCommandLoader, why would this be executed if a non-quantum cli command is executed?

Because command loader will be create when CLI try to find a command, it can be any command.

**Comment by yonzhan** [comment]
Please fix the CI first.

**Comment by warren-jones** [comment]
Converted this PR to "Draft" until I finish adding the tests

**Comment by warren-jones** [comment]
Moved most of the version check logic to a helper module to facilitate unit tests.  Added unit tests.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
