### PR TITLE
[AKS] fix regression from ARM mgmt sdk change

### PR DESCRIPTION
**Pull request by marwanad**
---
PR: https://github.com/Azure/azure-cli/pull/14344 introduced a breaking change to azure-mgmt-resource which broke compatibility of  the AKS CLI-extension with the latest CLI core.

This is based off the changes to preserve backwards compatibility in PR: ttps://github.com/Azure/azure-cli/pull/14344

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by arrownj** [comment]
Add @zhoxing-ms who is responsible for `Resource` module to review this.

**Comment by zhoxing-ms** [comment]
@marwanad Hi, the code is fine, could you pelase re-run the deployment related tests in live mode? This can further ensure that the modification is correct

**Comment by marwanad** [comment]
I validated locally using:

```
az aks create --enable-addons monitoring
```

which was the command failing with latest CLI and extensions.

I don't think the existing live tests in extensions exercise that scenario.

**Comment by zhoxing-ms** [comment]
@marwanad We always re-record yaml file through live test when the code has some change in the logic. In addition, we also have regular live test tasks for the CLI main repo. 

If you can ensure that all the deployment related parts in this extension are modified correctly, it is feasible to supplement the relevant tests with a separate PR, so I think this PR can be passed~

**Pull request merged**
