### PR TITLE
[AKS] Support updating from SPN cluster to MSI cluster

### PR DESCRIPTION
**Pull request by norshtein**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by norshtein** [comment]
The job "Verify Extensions Index" failed with error:
```
======================================================================
FAIL: test_metadata (__main__.TestIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts/ci/test_index.py", line 139, in test_metadata
    self.whl_cache_dir, self.whl_cache)
  File "/home/vsts/work/1/s/scripts/ci/util.py", line 86, in get_whl_from_url
    assert r.status_code == 200, "Request to {} failed with {}".format(url, r.status_code)
AssertionError: Request to https://azurecliprod.blob.core.windows.net/cli-extensions/synapse-0.1.0-py2.py3-none-any.whl failed with 500
```

The extension the error referencing to is relevant to `aks-preview`, and I've run `python scripts/ci/test_index.py -q` locally and succeeded:
```
$ python scripts/ci/test_index.py -q
----------------------------------------------------------------------
Ran 9 tests in 0.014s

OK (skipped=2)
```

Anything I can do to fix the CI error?

**Review by arrownj — COMMENTED** [review]
Hi @norshtein , could you please also help add tests for these new parameters ?

**Comment by norshtein** [comment]
Hi @arrownj , could you add a "Do-Not-Merge" label for this PR? AKS have a server-side behavior change on this feature which will take effect in next week. I will add a recording after the server side change take effect.

**Comment by norshtein** [comment]
Hi @arrownj , I've added recording for this change and this PR is ready to be merged. Could you please help merge the PR?

By the way, I found in the recording file, the `secret` of service principal is also recorded as plain text, which might need some awareness. I've deleted affected service principal, but I think some fix in recording system is needed.

**Comment by arrownj** [comment]
> Hi @arrownj Xiaojian Xu FTE , I've added recording for this change and this PR is ready to be merged. Could you please help merge the PR?
> 
> By the way, I found in the recording file, the `secret` of service principal is also recorded as plain text, which might need some awareness. I've deleted affected service principal, but I think some fix in recording system is needed.

Hi @norshtein , actually we can add some custom replacer while initializing a `ScenarioTest`. The framework has define some common used Replacer, you can read [GraphClientPasswordReplacer](https://github.com/Azure/azure-cli/blob/34667d8d43f6083c3eba65aea10bdf2c78c533b7/src/azure-cli-testsdk/azure/cli/testsdk/utilities.py#L108) for example. It is used in the [`ScenarioTest` construct function](https://github.com/Azure/azure-cli/blob/34667d8d43f6083c3eba65aea10bdf2c78c533b7/src/azure-cli-testsdk/azure/cli/testsdk/base.py#L87). For your case, you can add a customized Replacer and add it in your `ScenarioTest` subclass. And if it is general enough, we can also consider add it in the test framework.

**Review by arrownj — APPROVED** [review]

**Comment by norshtein** [comment]
@arrownj thanks for the explanation, it helps!

**Pull request merged**
