### PR TITLE
Set version to 0.3.6

### PR DESCRIPTION
**Pull request by malachma**
This update is necessary for PR https://github.com/Azure/azure-cli-extensions/pull/3153

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
vm repair

**Comment by malachma** [comment]
There is the following buildlog error

-->
 azdev extension add vm-repair
2021-06-18T10:25:41.5079693Z azdev linter --include-whl-extensions vm-repair
2021-06-18T10:25:41.5080112Z Checking service name for internal extensions
2021-06-18T10:25:41.5080462Z FOUND 4 command(s) from the extension.
2021-06-18T10:25:41.5080792Z high_command_set:
2021-06-18T10:25:41.5081238Z {'vm'}
2021-06-18T10:25:41.5081573Z Verifying src/service_name.json
2021-06-18T10:25:41.5081882Z service_name_map:
2021-06-18T10:25:41.5090946Z {'account': 'Azure CLI', 'ai-examples': 'Microsoft AI', 'aks': 'Azure Kubernetes Service (AKS)', 'alias': 'Azure CLI', 'attestation': 'Azure Attestation', 'automation': 'Azure Automation', 'baremetalinstance': 'Microsoft Windows', 'blockchain': 'Azure Blockchain', 'blueprint': 'Azure Blueprint', 'cli-translator': 'Azure CLI', 'cloud-service': 'Azure Cloud Services (extended support)', 'codespace': 'Visual Studio', 'communication': 'Azure Communication Service', 'confluent': 'Microsoft Partner Services', 'connectedk8s': 'Azure Kubernetes Service (AKS)', 'connectedmachine': 'Azure Arc', 'costmanagement': 'Azure Cost Management + Billing', 'csvmware': 'Azure VMWare Solution', 'custom-providers': 'Azure Custom Providers', 'databox': 'Azure Databox', 'datadog': 'Microsoft Partner Services', 'databricks': 'Azure Databricks', 'datafactory': 'Azure Data Factory', 'datashare': 'Azure Data Share', 'disk-pool': 'Azure Disk Pool Service', 'dedicated-hsm': 'Azure Dedicated HSM', 'desktopvirtualization': 'Azure Virtual Machines', 'dms': 'Azure Database Migration Service', 'dnc': 'Delegated Network Controller', 'dt': 'Azure Digital Twins', 'footprint': 'Azure Monitor', 'fzf': 'Azure CLI', 'graph': 'Azure Resource Graph', 'guestconfig': 'Azure Policy', 'hack': 'Azure Lab Services', 'hanainstance': 'SAP HANA on Azure', 'healthbot': 'Azure Bot Service', 'healthcareapis': 'Azure API for FHIR', 'hpc-cache': 'Azure HPC Cache', 'image': 'Azure Virtual Machines', 'import-export': 'Azure Storage', 'interactive': 'Azure CLI', 'internet-analyzer': 'Azure Network', 'iot': 'Azure IoT', 'k8s-configuration': 'Azure Kubernetes Service (AKS)', 'k8sconfiguration': 'Azure Kubernetes Service (AKS)', 'k8s-extension': 'Azure Kubernetes Service (AKS)', 'logic': 'Azure Logic Apps', 'maintenance': 'Azure Virtual Machines', 'cosmosdb': 'Azure Cosmos DB', 'managed-cassandra': 'Azure Cosmos DB', 'managementpartner': 'Microsoft Partner Network', 'mesh': 'Azure Service Fabric Mesh', 'ml': 'Azure Machine Learning', 'monitor': 'Azure Monitor', 'mysql': 'Azure Database for MySQL', 'network': 'Azure Network', 'next': 'Azure CLI', 'notification-hub': 'Azure Notification Hubs', 'offazure': 'Azure Migrate', 'peering': 'Azure Network', 'portal': 'Azure Portal', 'postgres': 'Azure Database for PostgreSQL', 'powerbi': 'Power BI', 'providerhub': 'Azure Providers', 'quantum': 'Azure Quantum', 'redisenterprise': 'Azure Cache for Redis', 'remote-rendering-account': 'Azure Remote Rendering', 'resource-mover': 'Azure Resource Mover', 'sapmonitor': 'SAP HANA on Azure', 'sentinel': 'Azure Sentinel', 'spatial-anchors-account': 'Azure Spatial Anchors', 'spring-cloud': 'Azure Spring Cloud', 'sql': 'Azure SQL', 'ssh': 'Azure Virtual Machines', 'stack-hci': 'Azure Stack', 'storage': 'Azure Storage', 'storagesync': 'Azure File Sync', 'stream-analytics': 'Azure Stream Analytics', 'support': 'Azure Support', 'tsi': 'Azure Time Series Insights', 'vmware': 'Azure VMWare Solution', 'kusto': 'Azure Data Explorer', 'webpubsub': 'Azure Web PubSub', 'connectedvmware': 'Azure Arc', 'dataprotection': 'Azure Data Protection'}
2021-06-18T10:25:41.5100441Z Traceback (most recent call last):
2021-06-18T10:25:41.5101272Z   File "scripts/ci/verify_linter.py", line 223, in <module>
2021-06-18T10:25:41.5101929Z     main()
2021-06-18T10:25:41.5102710Z   File "scripts/ci/verify_linter.py", line 214, in main
2021-06-18T10:25:41.5103504Z     linter_on_internal_extension(modified_files)
2021-06-18T10:25:41.5104230Z   File "scripts/ci/verify_linter.py", line 191, in linter_on_internal_extension
2021-06-18T10:25:41.5104877Z     service_name.check()
2021-06-18T10:25:41.5105525Z   File "/home/vsts/work/1/s/scripts/ci/service_name.py", line 123, in check
2021-06-18T10:25:41.5106704Z     raise Exception('No entry of {} in service_name.json. Please add one to the file.'.format(high_command))
2021-06-18T10:25:41.5107607Z Exception: No entry of vm in service_name.json. Please add one to the file.
<--

which needs to be further investigated

**Comment by Juliehzl** [comment]
Please add entry for your extension commands in https://github.com/Azure/azure-cli-extensions/blob/9f0aa09e7652ee73b4d75fab064711e78fb99ab8/src/service_name.json.

And you need to update history.rst for release note

**Comment by malachma** [comment]
Service_name.py needs no change. Just added some line to the existing vm-repair extension.
history.rst is not defined in vm-repair. There is only the version variable/property defined which I altered. If history.rst is required please let me know where this has to be added for vm-repair extension.

**Comment by Juliehzl** [comment]
service_name.json is used to generate document, if you don't update it, CI will always fail

**Comment by zhoxing-ms** [comment]
@malachma Please add the description of your modification to `HISTORY.rst`.

**Comment by malachma** [comment]
HISTORY.rst is not used with vm-repair. If you look in setup.py you don't see it used compared with other extensions.

**Comment by zhoxing-ms** [comment]
@malachma Hi, in fact, `HISTORY.rst` is the release note (such as [link](https://github.com/Azure/azure-cli-extensions/blob/main/src/spring-cloud/HISTORY.md) ), we use it to tell users about the new features and changes introduced in each version. So without it, users will not know what updates and features are added in the new version.
Do you think this module needs to support `HISTORY.rst`?

**Comment by zhoxing-ms** [comment]
By the way, please also add the description of command `az vm` to `service_name.json` to fix the CI issue
Such as:
```json
{
    "Command": "az vm",
    "AzureServiceName": "Azure Virtual Machines",
    "URL": "https://docs.microsoft.com/en-us/azure/virtual-machines/"
}
```

**Comment by malachma** [comment]
This last update I do not understand. It looks to me that your have a general build issue which is not caused by this PR.
Compare this with this PR https://github.com/Azure/azure-cli-extensions/pull/3128/files
This PR had only two files changed . No HISTORY.rst file got added nor was there a need to add 
{
    "Command": "az vm",
    "AzureServiceName": "Azure Virtual Machines",
    "URL": "https://docs.microsoft.com/en-us/azure/virtual-machines/"
}
to the service_name.json.

**Comment by zhoxing-ms** [comment]
@malachma Add this just to let your PR pass CI
https://github.com/Azure/azure-cli-extensions/pull/3518#issuecomment-871444327

CI issue:
> Exception: No entry of vm in service_name.json. Please add one to the file.

**Comment by zhoxing-ms** [comment]
`HISTORY.rst` may not be added to this PR, but it is suggested to add `HISTORY.rst` if there is a new update in the future

**Comment by zhoxing-ms** [comment]
@malachma Any update?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
