### PR TITLE
[vm-repair] arm64 support And Bug Fix for telemetry

### PR DESCRIPTION
**Pull request by haagha**
This PR contains:

ARM64 VM's support for vm repair creation
Telemetry Fix for repair-and-restore command
Repair VM fix for gen1 VM attaching disk on SCSI controller, preventing nested VM from booting (by Ryan McCallum)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az vm repair create -g {rg} -n {vm}

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
vm-repair

**Comment by zhoxing-ms** [comment]
Could you add some test cases for this PR change?

**Comment by yanzhudd** [comment]
Please add more details (related commands and parameters) to the description.

**Comment by haagha** [comment]
@zhoxing-ms added a test case.

**Comment by haagha** [comment]
CI check failure seems unrelated to my changes.

**Review by zhoxing-ms — APPROVED** [review]

**Review by malachma — COMMENTED** [review]
The object/property command.message is populated with information about the fstab action which got executed. This looks to be like a generic message which may confuse people if a different action is used. Is there a condition I overlooked which is responsible for getting the message generated?

**Pull request merged**
