### PR TITLE
[Containerapp] `az containerapp create`: Fix Role assignment error when the default Azure Container Registry could not be found

### PR DESCRIPTION
**Pull request by Greedygre**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

Currently, when cx use command `az containerapp create --source/--artifact` without `--registry-server`, we will try to find the default ACR under the subscription. If the ACR not exists, it will throw error when the containerapp `version == 1.0.0b4`:
```
Role assignment failed with error message: "The resource with name 'caxxxxxxxxacr’ and type 'Microsoft.ContainerRegistry/registrys' could not be found in subscription 'xxxxxx' .
To add the role assignment manually, please run 'az role assignment create --assignee xxxxxxx --scope container-registry-resource-id> --role acrpull'.
You may have to restart the containerapp with 'az containerapp revision restart'.
- Running ..Failed to provision revision for container app 'xxxxx'. Error details: Cannot perform operation on container app xxxx' because another operation is in progress. Please retry the operation.
```

When the ACR not exists, it will not create acr, it will use local buildpacks or the Cloud Build.
So we should only backfill registry_server, registry_identity when the ACR existing

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by Juliehzl — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@Greedygre May I ask do you need to upgrade the extension version to release this fix?

**Comment by Greedygre** [comment]
> @Greedygre May I ask do you need to upgrade the extension version to release this fix?

We will release the next version on Nov 17th for ignite.
This issue cx can use workaround, for example use `az containerapp up` or use version <= 1.0.0b3

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
