### PR TITLE
Disable role assignment check for vnet for Azure Spring Cloud

### PR DESCRIPTION
**Pull request by gavinfish**
---

Disable role assignment check for vnet for Azure Spring Cloud. As checking role assignments for target VNet needs permissions to call AAD, this may block some customers in extreme circumstance when their az account does not have such permissions. 

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Spring Cloud

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to review? thanks.

**Comment by yungezz** [comment]
hi @gavinfish even removing the check in Azure CLI side, will there be authorization check at service side, such as NRP?

**Review by yungezz — APPROVED** [review]
LGTM

**Review by fengzhou-msft — APPROVED** [review]

**Comment by gavinfish** [comment]
> hi @gavinfish even removing the check in Azure CLI side, will there be authorization check at service side, such as NRP?

Yes, this will be checked from service side with specific SP.

**Pull request merged**
