### PR TITLE
Arc Appliance CLI 1.0.3 February Release

### PR DESCRIPTION
**Pull request by jake-billings**
This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [X] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by saisankargochhayat** [comment]
LGTM @kairu-ms @yonzhan please approve/merge when you can, thanks.

**Comment by jsntcy** [comment]
@jake-billings, please fix the CI error (metadata in wheel file is different from that in index.json) as shown in 
https://dev.azure.com/azclitools/5147fa83-336e-44ef-bbe0-c86b8ae86cbb/_apis/build/builds/133089/logs/53. 
Obviously the `requires` is different.

image

**Comment by jake-billings** [comment]
@jsntcy the error says it is from ml - is this a problem with this PR?

If so, how can we fix?

**Comment by jake-billings** [comment]
```
{
                "downloadUrl": "https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2-public/ml-2.23.0-py3-none-any.whl",
                "filename": "ml-2.23.0-py3-none-any.whl",
                "metadata": {
                    "azext.minCliCoreVersion": "2.15.0",
                    "classifiers": [
                        "Development Status :: 5 - Production/Stable",
                        "Intended Audience :: Developers",
                        "Intended Audience :: System Administrators",
                        "Environment :: Console",
                        "Programming Language :: Python",
                        "Programming Language :: Python :: 3",
                        "Programming Language :: Python :: 3.7",
                        "Programming Language :: Python :: 3.8",
                        "Programming Language :: Python :: 3.9",
                        "Programming Language :: Python :: 3.10",
                        "License :: OSI Approved :: MIT License"
                    ],
                    "description_content_type": "text/x-rst",
                    "extensions": {
                        "python.details": {
                            "contacts": [
                                {
                                    "email": "azuremlsdk@microsoft.com",
                                    "name": "Microsoft Corporation",
                                    "role": "author"
                                }
                            ],
                            "document_names": {
                                "description": "DESCRIPTION.rst"
                            },
                            "project_urls": {
                                "Home": "https://github.com/Azure/azureml-examples"
                            }
                        }
                    },
                    "extras": [],
                    "generator": "bdist_wheel (0.30.0)",
                    "license": "MIT",
                    "metadata_version": "2.0",
                    "name": "ml",
                    "run_requires": [
                        {
                            "requires": [
                                "azure-common (<2.0.0,>=1.1)",
                                "azure-common<2.0.0,>=1.1",
                                "azure-mgmt-resource (<23.0.0,>=3.0.0)",
                                "azure-mgmt-resource<23.0.0,>=3.0.0",
                                "azure-mgmt-resourcegraph (<9.0.0,>=2.0.0)",
                                "azure-mgmt-resourcegraph<9.0.0,>=2.0.0",
                                "azure-storage-blob (<13.0.0,>=12.10.0)",
                                "azure-storage-blob<13.0.0,>=12.10.0",
                                "azure-storage-file-datalake (<13.0.0)",
                                "azure-storage-file-datalake<13.0.0",
                                "azure-storage-file-share (<13.0.0)",
                                "azure-storage-file-share<13.0.0",
                                "colorama (<0.5.0)",
                                "colorama<0.5.0",
                                "cryptography",
                                "cryptography",
                                "docker",
                                "docker",
                                "isodate",
                                "isodate",
                                "jsonschema (<5.0.0,>=4.0.0)",
                                "jsonschema<5.0.0,>=4.0.0",
                                "marshmallow (<4.0.0,>=3.5)",
                                "marshmallow<4.0.0,>=3.5",
                                "opencensus-ext-azure (<2.0.0)",
                                "opencensus-ext-azure<2.0.0",
                                "pydash (<7.0.6,>=6.0.0)",
                                "pydash<7.0.6,>=6.0.0",
                                "pyjwt (<3.0.0)",
                                "pyjwt<3.0.0",
                                "strictyaml (<2.0.0)",
                                "strictyaml<2.0.0",
                                "tqdm (<5.0.0)",
                                "tqdm<5.0.0",
                                "typing-extensions (<5.0.0)",
                                "typing-extensions<5.0.0"
                            ]
                        }
                    ],
                    "summary": "Microsoft Azure Command-Line Tools AzureMachineLearningWorkspaces Extension",
                    "version": "2.23.0"
                },
                "sha256Digest": "c4cffb5dd82c8146d11c93330b6952933bbe6755cdf77e954cdf910717e65323"
            }
```

Link: https://raw.githubusercontent.com/Azure/azure-cli-extensions/c52a8910146f47b66cb7f931a33a1b6dab88f4e8/src/index.json

image

Link: https://dev.azure.com/azclitools/5147fa83-336e-44ef-bbe0-c86b8ae86cbb/_apis/build/builds/133089/logs/53

Based on the above, it looks like the ml package may have updated it's whl file.

Will a rerun help?

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
