### PR TITLE
{dataprotection} quickfix: making the `aaz_operations` folder a module

### PR DESCRIPTION
**Pull request by zubairabid**
---
Quickfix for issue that broke CI for Azure Help.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
dataprotection

**Review by evelyn-ys — COMMENTED** [review]
Do you need to release a new version? If so, don't forget to upgrade version in `setup.py` and `history.rst`

**Comment by zubairabid** [comment]
> Do you need to release a new version? If so, don't forget to upgrade version in `setup.py` and `history.rst`

@evelyn-ys I've updated the files, to version `0.8.2`

**Review by evelyn-ys — COMMENTED** [review]
I'm so surprised to find that your team has not changed the version in `setup.py` for a lot of versions. Have you confirmed if features in new versions can be used by customers????
https://github.com/Azure/azure-cli-extensions/blob/d7025bb650ba2b9c615739392cde700cda803cfd/src/datamigration/setup.py#L13

From what I can see, customers can only install old versions of datamigration extension:
```
> > az extension list-versions -n datamigration -o table
Compatible    Experimental    Installed    Name           Preview    Version
------------  --------------  -----------  -------------  ---------  ------------------------------
True          True            False        datamigration  False      0.1.0
True          True            False        datamigration  False      0.2.0
True          True            False        datamigration  False      0.3.0
True          True            False        datamigration  False      0.3.1
True          True            False        datamigration  False      0.4.0
True          True            False        datamigration  False      0.4.1
True          True            False        datamigration  False      0.5.0 (max compatible version)
```

**Comment by zubairabid** [comment]
> What I mean is the version here:
> 
> https://github.com/Azure/azure-cli-extensions/blob/398e8dec5063d1e00c9a7a452ea76d2ad45d34cf/src/dataprotection/setup.py#L13

Got it, I had made the change but staged/committed another file that wasn't changed. That has been updated now.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
