### PR TITLE
[AKS] Add the KataCcIsolation option to --workload-runtime 

### PR DESCRIPTION
**Pull request by fangluguomsft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az aks create \
  --name kata-cc-test \
  --resource-group fangluguo-hv \
  --os-sku Mariner \
  --node-vm-size Standard_DC4as_cc_v5 \
  --workload-runtime KataCcIsolation \
  --node-count 1 \
  --location eastus2euap

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
  - Yes. Many warnings but none of them are from my modification.
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
  - All good.

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — COMMENTED** [review]
lgtm

would be better to add a unit/live test for the change

**Comment by fangluguomsft** [comment]
I investigated the alert of Azure CLI Extensions Breaking Change Test. The alert is copied below. See the original bot output for a better formatted output. 

My conclusion is the alert is a false alarm. This PR didn't change spot_max_price at all. There is no link between this PR and spot_max_price. 

=====

rule | cmd_name | rule_message | suggest_message
-- | -- | -- | --
❌ 1010 - ParaPropUpdate | aks nodepool add | cmd aks nodepool add update parameter spot_max_price: updated property default from nan to nan | please change property default from nan to nan for parameter spot_max_price of cmd aks nodepool add

rule	cmd_name	rule_message	suggest_message
❌ [1010 - ParaPropUpdate](https://github.com/Azure/azure-cli/blob/dev/doc/breaking_change_rules/1010.md)	aks nodepool add	cmd aks nodepool add update parameter spot_max_price: updated property default from nan to nan	please change property default from nan to nan for parameter spot_max_price of cmd aks nodepool add

This

**Comment by fangluguomsft** [comment]
Live test:

az aks create \
  --name kata-cc-test2 \
  --resource-group fangluguo-hv \
  --os-sku Mariner \
  --node-vm-size Standard_DC4as_cc_v5 \
  --workload-runtime KataCcIsolation \
  --node-count 1 \
  --location eastus2euap

It works and creates a cluster with a node pool that support the new kata-cc feature.

**Comment by fangluguomsft** [comment]
Read live test doc: https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/358311/AZCLI-Coding-Handbook?anchor=live-test

The live test means differently from my previous post. Live test as defined in the wiki page is not possible because this is a preview feature and it is guarded by a preview flag. 

Reason as documented in the wiki: `The default subscription used by our pipelines and runner does not register any features other than AKSHTTPCustomFeatures, so test cases involving features that do not support feature validation by custom header cannot be executed in live mode. Please refer to section [Bypass Test Case](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/358312/AZCLI-AKS-Live-Unit-Test-Pipeline?anchor=bypass-test-case) to bypass the test case.`

**Comment by fangluguomsft** [comment]
Checked the unit test and found the workload_runtime was already properly tested at https://github.com/Azure/azure-cli-extensions/blob/e4fc6a908d406b508139f88b053d985b879d70f3/src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py#L611. There is no need to test individual option one by one.

As to the option list, it is only used in the arg config below. There is no precedence to test if every option in the list will work. 

https://github.com/Azure/azure-cli-extensions/blob/5a1872a19668a633b096a30af0ee48a764ae3257/src/aks-preview/azext_aks_preview/_params.py#L479

Since it is so trivial to just add the option to the list, it doesn't seem necessary to add a unit test. If there are examples, I will be happy to add the test.

**Comment by FumingZhang** [comment]
> Read live test doc: https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/358311/AZCLI-Coding-Handbook?anchor=live-test
> 
> The live test means differently from my previous post. Live test as defined in the wiki page is not possible because this is a preview feature and it is guarded by a preview flag.
> 
> Reason as documented in the wiki: `The default subscription used by our pipelines and runner does not register any features other than AKSHTTPCustomFeatures, so test cases involving features that do not support feature validation by custom header cannot be executed in live mode. Please refer to section [Bypass Test Case](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/358312/AZCLI-AKS-Live-Unit-Test-Pipeline?anchor=bypass-test-case) to bypass the test case.`

If rp supports bypassing the feature validation via the AKSHTTPCustomFeatures header, you could still test the new enum value. And I think it's ok to not add a new case in cli side if the scenario has been covered in rp e2e.

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by fangluguomsft** [comment]
Yes. e2e test enables the preview feature flag and we test it via e2e.

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@fangluguomsft Please resolve these conflicts

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
