### PR TITLE
[Release] Revert `confcom` 0.2.14

### PR DESCRIPTION
**Pull request by kairu-ms**
---

The `pydash` dependence is not compatible with typing_extensions==4.6.0, it causes CI issues when generate docs.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Release

**Comment by kairu-ms** [comment]
https://github.com/Azure/azure-cli-extensions/pull/6315

**Comment by jsntcy** [comment]
Could you please help add the reason why we need revert confcom 0.2.14 to help reviewers understand?

**Comment by kairu-ms** [comment]
> Could you please help add the reason why we need revert confcom 0.2.14 to help reviewers understand?

Updated in the description.

**Comment by jsntcy** [comment]
- Are there other extensions affected by this issue?
- Do we have any solution to fix this issue so that we can release `confcom` 0.2.14?

**Review by necusjz — APPROVED** [review]

**Pull request merged**
