### PR TITLE
Fix the version to 0.0.22 for draft update command. ☕️🚀

### PR DESCRIPTION
**Pull request by Tatsinnit**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

This Fix is done to keep the `1:1` mapping to `DRAFT Tool` version `0.0.22` **not** `23` why because in this PR. Why? because under this PR https://github.com/Azure/draft/pull/136 a new behaviour is added withouth thinking towards the consuming tool so lets unblock breaks for AZ-CLI until the right fix from Draft comes in.

Thanks and FYI: @karenychen , @gambtho , @FumingZhang , @imiller31 , @davidgamero , @qpetraroia , @sabbour, @bfoley13 ❤️🙏☕️

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Review by karenychen — APPROVED** [review]

**Review by davidgamero — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — COMMENTED** [review]
Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=60181714&view=results) to verify the fix.

**Comment by FumingZhang** [comment]
Found the error, the download URL (`url = f'https://github.com/Azure/draft/releases/latest/download/{filename}'`) in `src/aks-preview/azext_aks_preview/aks_draft/commands.py` was hardcoded. 

To fix it, need to change it to `url = f'https://github.com/Azure/draft/releases/download/{CONST_DRAFT_CLI_VERSION}/{filename}'`

**Comment by FumingZhang** [comment]
A new [run](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=60183305&view=results)

**Review by FumingZhang — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
