### PR TITLE
Resolve error when fetching Container App workflow name with 'up' command

### PR DESCRIPTION
**Pull request by cormacpayne**
Recently, the `workflowName` property was removed from the `/subscriptions/resourceGroups/providers/Microsoft.App/containerApps/sourcecontrols/current` API, which represented the name of the YAML workflow file created for the user via `containerapp up --source` (or through the _Continuous Deployment_ blade in the Azure Portal), which allowed users to build and deploy their application using GitHub Actions.

As a result of this property being removed, certain calls in the `up` flow when `--source` was provided (such as [here](https://github.com/Azure/azure-cli-extensions/blob/305c45f25c7ed1bcf567b892bcfd9eb50938afe4/src/containerapp/azext_containerapp/custom.py#L2825) and [here](https://github.com/Azure/azure-cli-extensions/blob/305c45f25c7ed1bcf567b892bcfd9eb50938afe4/src/containerapp/azext_containerapp/_up_utils.py#L1048)) are throwing exceptions when attempting to access the property in the API response.

With this PR, a new function is introduced, `get_workflow_name`, that will user the GitHub API (specifically, [this call](https://docs.github.com/en/rest/repos/contents#get-repository-content)) to fetch the files in given repository's branch, and see if any within the `.github/workflows` folder match the expected YAML file name (`{containerAppName}-AutoDeployTrigger-{guid}.yml`).

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

`az containerapp up`

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

~- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).~

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by zhoxing-ms** [comment]
Could you please add test case for this PR change

**Comment by cormacpayne** [comment]
@zhoxing-ms -- Hey Xing, for this specific flow that we're fixing, it relies on creating a workflow YAML file in a user's GitHub repository that then triggers a GitHub Action run. Creating a test for this would be tricky when it comes to maintaining the repository that the workflow is created in, managing the secrets to push to this repository, etc. Is there another route we can take for testing this flow that you have any guidance on? Thanks in advance.

**Comment by zhoxing-ms** [comment]
@cormacpayne I see, this is indeed difficult to create scenario tests, so manual testing can ensure that the process meets expectations. So I'll merge this PR first

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
