### PR TITLE
publish latest aks-preview extension 0.4.28

### PR DESCRIPTION
**Pull request by bingosummer**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by bingosummer** [comment]
@zikalino can you please have a review?

**Comment by yonzhan** [comment]
add to S165.

**Comment by arrownj** [comment]
Hi @bingosummer , do you miss to push the changes of vendored SDK ? I didn't see any file change for that except the version/history updated.

**Comment by bingosummer** [comment]
> Hi @bingosummer , do you miss to push the changes of vendored SDK ? I didn't see any file change for that except the version/history updated.

the changes are already merged in another PR.

**Comment by bingosummer** [comment]
Hi @arrownj, could you please review and merge the PR?

**Comment by arrownj** [comment]
Hi @zqingqing1 @zikalino , could you please help review this PR as you are the code owner of aks-preview. Thanks

**Pull request closed without merging**
