### PR TITLE
Offboard az adp (delete src/adp directory)

### PR DESCRIPTION
**Pull request by ohads-MSFT**
ADP service has been decommissioned

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
`az adp`

### General Guidelines
N/A - removing extension entirely

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by ohads-MSFT** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by ohads-MSFT** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by kairu-ms** [comment]
@ohads-MSFT, please revert the change in this commit as well https://github.com/Azure/azure-cli-extensions/commit/944134f9dab683134fd84d7db2520a1ddbec36fb

**Comment by ohads-MSFT** [comment]
> @ohads-MSFT, please revert the change in this commit as well [944134f](https://github.com/Azure/azure-cli-extensions/commit/944134f9dab683134fd84d7db2520a1ddbec36fb)

Done

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
