### PR TITLE
[rdbms-connect] remove preview tag for postgresql

### PR DESCRIPTION
**Pull request by DaeunYim**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
rdbms-connect

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
Hi @DaeunYim, to make changes really work in cli extension, you have to upgrade version in `setup.py` and update `HISTORY.rst` so that a new version will be released

**Comment by DaeunYim** [comment]
@evelyn-ys  It was very silly of me to miss that again... :( I'm submitting a PR right now.. Thank you a lot for letting me know!!

**Comment by DaeunYim** [comment]
https://github.com/Azure/azure-cli-extensions/pull/4178 Here!

**Pull request merged**
