### PR TITLE
[AKS] az aks create/update: Add LicenseType support for Windows

### PR DESCRIPTION
**Pull request by AbelHu**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by AbelHu** [comment]
> If this PR is for a new extension or change to an existing extension, use the following to try out the changes in this PR:
> 
> ```
> docker run -it microsoft/azure-cli:latest
> export EXT=<NAME>
> pip install --upgrade --target ~/.azure/cliextensions/$EXT "git+https://github.com/AbelHu/azure-cli-extensions.git@aks-win-ahub#subdirectory=src/$EXT&egg=$EXT"
> ```

```
docker run -it microsoft/azure-cli:latest
export EXT=aks-preview
pip install --upgrade --target ~/.azure/cliextensions/$EXT "git+https://github.com/AbelHu/azure-cli-extensions.git@aks-win-ahub#subdirectory=src/$EXT&egg=$EXT"
```
Result:
```
bash-5.0# export EXT=aks-preview
bash-5.0# pip install --upgrade --target ~/.azure/cliextensions/$EXT "git+https://github.com/AbelHu/azure-cli-extensions.git@aks-win-ahub#subdirectory=src/$EXT&egg=$EXT"
Collecting aks-preview
  Cloning https://github.com/AbelHu/azure-cli-extensions.git (to revision aks-win-ahub) to /tmp/pip-install-5h2373el/aks-preview
  Running command git clone -q https://github.com/AbelHu/azure-cli-extensions.git /tmp/pip-install-5h2373el/aks-preview
  Running command git checkout -b aks-win-ahub --track origin/aks-win-ahub
  Branch 'aks-win-ahub' set up to track remote branch 'aks-win-ahub' from 'origin'.
  Switched to a new branch 'aks-win-ahub'
Building wheels for collected packages: aks-preview
  Building wheel for aks-preview (setup.py) ... done
  Created wheel for aks-preview: filename=aks_preview-0.4.64-py2.py3-none-any.whl size=746657 sha256=ad71ddd5979ae54022b4c0a3dc237d8a97639d1c9827a8e94365a528e63d87ee
  Stored in directory: /tmp/pip-ephem-wheel-cache-sjwocxs1/wheels/b8/55/8a/2b48f57101bab2d0c3ac02c686f862859c4bdff0abc275d9c0
Successfully built aks-preview
Installing collected packages: aks-preview
Successfully installed aks-preview-0.4.64
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

**Comment by yonzhan** [comment]
AKS

**Comment by AbelHu** [comment]
ping @gtracer @zqingqing1 .

**Review by zqingqing1 — APPROVED** [review]
lgtm

**Comment by AbelHu** [comment]
Ping...

**Review by arrownj — APPROVED** [review]
LGTM

**Pull request merged**
