### PR TITLE
[TA] change rolebinding create command parameter roles to comma-seperated

### PR DESCRIPTION
**Pull request by YitongFeng-git**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`. 

### Test:
image

### CODE REVIEW

**Review by FumingZhang — APPROVED** [review]
LGTM

Please also update history.rst (and setup.py if you want to release a new version) and add some description about the change.

Also, since the feature is basically available, time to add a live test case for it?

**Comment by YitongFeng-git** [comment]
> 



> LGTM
> 
> Please also update history.rst (and setup.py if you want to release a new version) and add some description about the change.
> 
> Also, since the feature is basically available, time to add a live test case for it?

Updated history, and the tests will added in August.

**Comment by yonzhan** [comment]
AKS

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
