### PR TITLE
Publish aks-preview 5.2

### PR DESCRIPTION
**Pull request by JunSun17**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yungezz** [comment]
hi @JunSun17 we have automatic pipeline for extension releasing. Extension owners just need to bump extension versions in setup.py and history.rst. Could you pls share context why the manual releasing? add @fengzhou-msft

**Comment by JunSun17** [comment]
> hi @JunSun17 we have automatic pipeline for extension releasing. Extension owners just need to bump extension versions in setup.py and history.rst. Could you pls share context why the manual releasing? add @fengzhou-msft

Sure, no need to do this PR. The version numbers has been bumped already.

**Comment by JunSun17** [comment]
Actually I checked and do not see a new PR is being create to update src/index.json. aks-preview is still pinged to version 0.5.0, not 0.5.2, So probably we still need this PR or some other way to manually update the version number.

**Comment by fengzhou-msft** [comment]
@JunSun17 The release for 0.5.1 was labelled do-not-merge, we can release it or close it to release 0.5.2. https://github.com/Azure/azure-cli-extensions/pull/3053

**Comment by fengzhou-msft** [comment]
> @JunSun17 The release for 0.5.1 was labelled do-not-merge, we can release it or close it to release 0.5.2 directly. #3053

Let me release it to unblock follow-up releases of new versions.

**Comment by JunSun17** [comment]
> > @JunSun17 The release for 0.5.1 was labelled do-not-merge, we can release it or close it to release 0.5.2 directly. #3053
> 
> Let me release it to unblock follow-up releases of new versions.

Cool, thanks!

**Comment by JunSun17** [comment]
> > @JunSun17 The release for 0.5.1 was labelled do-not-merge, we can release it or close it to release 0.5.2 directly. #3053
> 
> Let me release it to unblock follow-up releases of new versions.

Do we still need this PR for manual bump of 0.5.2?

**Comment by fengzhou-msft** [comment]
No. I merged this auto-generated one https://github.com/Azure/azure-cli-extensions/pull/3094 for 0.5.2

**Pull request closed without merging**
