### PR TITLE
User/dhwanishah/updating index.json

### PR DESCRIPTION
**Pull request by djshah19**
Publishing azurestackhci cli version 0.2.4

### CODE REVIEW

**Comment by djshah19** [comment]
opening another PR

**Comment by yonzhan** [comment]
azurestackhci

**Review by JocelynBerrendonner — APPROVED** [review]
Looks good from an azurestackhci perspective

**Comment by kairu-ms** [comment]
@djshah19 and @JocelynBerrendonner. Please check the following examples in your extension.
image

**Comment by JocelynBerrendonner** [comment]
Thanks for updating the PR, @djshah19 !

@kairu-ms , just a heads up that the tests are passing now.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
