### PR TITLE
[dataprotection] AKS Hooks for backup and restore, time validation fix

### PR DESCRIPTION
**Pull request by zubairabid**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

`az dataprotection`
- Upgraded API version for Backup Instance CRUD operations, Restore Trigger, and Validate and Restore. TODO upgrade API version across the board
- Implemented `backup-hook-refs` and `restore-hook-refs` options for `initialize-backupconfig` and `initialize-restoreconfig` respectively
- Fixed bug with `datetime-type` validation - it works now instead of appending ".0000000Z" to any string it receives.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
dataprotection

**Review by evelyn-ys — COMMENTED** [review]
Please add tests for new command/parameter

**Comment by evelyn-ys** [comment]
If you want to release a new version, don't forget to update the version in `setup.py` and `history.rst`

**Comment by zubairabid** [comment]
> If you want to release a new version, don't forget to update the version in `setup.py` and `history.rst`

Added tests, and also updated the version.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
