### PR TITLE
[aks-preview] add universal back

### PR DESCRIPTION
**Pull request by arrownj**
Currently `az extension add` will skip whl which do not contain .py2. So the previous change will cause the extension can't be added.

Changes for `az extension add` are already submit by @fengzhou-msft in https://github.com/Azure/azure-cli/pull/12727. 

Here we add universal back and leave it when the new `az extension add` behavior go online.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S167

**Comment by haroldrandom** [comment]
Hi, I remove the Python 2 version limit on wheel name in CI. https://github.com/Azure/azure-cli-extensions/pull/1439. This won't be a problem I think.

**Comment by karataliu** [comment]
Do we need to increase package version for those changes?

The following blob seems already uploaded with the old config.
https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.38-py3-none-any.whl

**Comment by arrownj** [comment]
> Do we need to increase package version for those changes?
> The following blob seems already uploaded with the old config.
> https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.38-py3-none-any.whl

no need, the change in the index.json is not merged.

**Pull request merged**
