### PR TITLE
[Release] Update index.json for extension [ vm-repair ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ vm-repair ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=535394

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/c906263ddf2dab08a0a7355030b883b40d34aa11

### CODE REVIEW

**Comment by yonzhan** [comment]
vm-repair

**Comment by swbae31** [comment]
Why isn't the index.json updates getting merged automatically? The 0.3.3 changes fix a critical bug. Please get this merged. Thanks.

**Comment by yonzhan** [comment]
@fengzhou-msft  please help with this.

**Comment by qwordy** [comment]
@haroldrandom @fengzhou-msft

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
