### PR TITLE
{containerapp} Re-record failing source-to-cloud patch tests

### PR DESCRIPTION
**Pull request by cormacpayne**
The current set of patching tests that we have available for the source-to-cloud flow are currently failing as they default into our new cloud build service to build the provided application, when, for these patching tests, they should use the local builder flow. To enable this, we create an ACR instance before the `containerapp up` command is called, which signals to the flow that the cloud build service should be skipped (as it currently only runs when no container registry exists in the provided resource group). This then allows an application image to be built, pushed to the given ACR instance and able to be tested with for the existing `containerapp patch` commands.

In addition, a default location was being set before the `containerapp up` call was being called, which was affecting flow where ACA environments were previously created with one location, and the `up` flow expects it have been created with the default location that was set. This line was removed to avoid ambiguity with regards to the location that was observed as the default throughout the lifecycle of the test.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az containerapp patch

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
containerapp

**Review by Greedygre — APPROVED** [review]

**Comment by Greedygre** [comment]
Recommend Title:
{containerapp} Re-record failing source-to-cloud patch tests

Because this change will not impact customer, it should uses {}.

PR title guidance: https://github.com/Azure/azure-cli/blob/f9a4685d6bfee8bd5b8eff867f40a7d674515dae/doc/authoring_command_modules/README.md#format-pr-title

**Comment by cormacpayne** [comment]
@Greedygre thanks for the tip -- I just updated the title

**Review by Greedygre — APPROVED** [review]

**Comment by Greedygre** [comment]
Hi @zhoxing-ms @yanzhudd 

Could you please help to review and merge this PR? Thanks!

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
