### PR TITLE
fix no attribute 'gigabytes' error

### PR DESCRIPTION
**Pull request by takekazuomi**
### Related command

```sh
az containerapp compose create 
```

docker-compose.yaml

```yaml
services:
  helloworld:
    image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
    ports: 
     - 8080:80
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 0.5GB
```

### General Guidelines

- [x] Have you run `azdev stylepwd <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

### See

https://github.com/smurawski/docker-compose-examples/issues/1

### CODE REVIEW

**Review by smurawski — APPROVED** [review]
Great catch @takekazuomi 

Thanks!

**Comment by yonzhan** [comment]
containerapp

**Review by smurawski — APPROVED** [review]
Good catch.

**Comment by zhoxing-ms** [comment]
@takekazuomi @smurawski If you want to release a new version of extension for this change, please also modify the `HISTORY.rst` and `setup.py`, thanks

**Comment by smurawski** [comment]
@zhoxing-ms Not yet, I've got a new PR underway to add some more features and fix a bug.

This can be merged as is.

Thank you!

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
