### PR TITLE
Fix webapp remote-connection create fails if specifying --port

### LINKED ISSUE #268: webapp remote-connection create fails if specifying --port on version 0.2.7
### Extension name (the extension in question)
webapp

### Description of issue (in as much detail as possible)
The following command will fail when specifying --port after updating to version 0.2.7. Works fine in 0.2.6.
```
webapp remote-connection create --resource-group rg --name name --port xxx 
```
with the following message:
```
connect_ex() takes exactly one argument (2 given)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\custom.py", line 254, in create_tunnel
    tunnel_server = TunnelServer('', port, host_name, user_name, user_password)
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 42, in __init__
    if self.local_port != 0 and not self.is_port_open():
  File "C:\Users\xxx\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 69, in is_port_open
    if sock.connect_ex('', self.local_port) == 0:
TypeError: connect_ex() takes exactly one argument (2 given)
```
-----

### PR DESCRIPTION
**Pull request by patricklee2**
fixes #268 

I tested it and was able to open the port

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
Added the label to not merge based on your comment - let me know when this is ready for review.

**Comment by panchagnula** [comment]
@patricklee2  also let me know if we want to take this change as well https://github.com/Azure/azure-cli-extensions/pull/271

**Comment by patricklee2** [comment]
@panchagnula this is ready for review

**Comment by panchagnula** [comment]
@patricklee2 can you pull & rebase from master & push a change again? this should fix the Travis-ci

**Pull request merged**
