### PR TITLE
Kusto: releasing 2021-08-27 client

### PR DESCRIPTION
**Pull request by zoharHenMicrosoft**

### CODE REVIEW

**Comment by zoharHenMicrosoft** [comment]
@kairu-ms  @jsntcy 
Hi folks, I will appreciate your help with the failed tests above - everything passed locally so I'm not sure what is the issue here.
In addition - we are still getting the following alert: "The installed extension 'kusto' is experimental and not covered by customer support. Please use with discretion." - Can you please share which actions are required in order to be published it as GA?

**Comment by jsntcy** [comment]
> @kairu-ms Kai Ru FTE @jsntcy Yu Chen FTE Hi folks, I will appreciate your help with the failed tests above - everything passed locally so I'm not sure what is the issue here. In addition - we are still getting the following alert: "The installed extension 'kusto' is experimental and not covered by customer support. Please use with discretion." - Can you please share which actions are required in order to be published it as GA?

Remove `"azext.isExperimental": true,` in azext_metadata.json so that the alert will disappear.

**Comment by yonzhan** [comment]
Kusto

**Comment by zoharHenMicrosoft** [comment]
> > > > @kairu-ms Kai Ru FTE @jsntcy Yu Chen FTE Hi folks, I will appreciate your help with the failed tests above - everything passed locally so I'm not sure what is the issue here. In addition - we are still getting the following alert: "The installed extension 'kusto' is experimental and not covered by customer support. Please use with discretion." - Can you please share which actions are required in order to be published it as GA?
> > > 
> > > 
> > > 
> > > * Remove `"azext.isExperimental": true,` in azext_metadata.json so that the alert will disappear.
> > > * Regarding the CI failure, the error messages are obvious for you, you need fix them accordingly.
> > > 
> > > image
> > > image
> 
> @jsntcy sorry for being unclear, this is the error I can't solve. do you familiar with it? image

same issue :(, any additional tips?

**Pull request merged**
