### PR TITLE
Add azurestackhci cli extension

### PR DESCRIPTION
**Pull request by Arkanayan**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
azurestackhci

**Comment by JocelynBerrendonner** [comment]
The change looks good from my perspective (azurestackhci feature team)

**Review by JocelynBerrendonner — APPROVED** [review]
LGTM

**Comment by kairu-ms** [comment]
Please Fix CI issues. Thanks

**Comment by Arkanayan** [comment]
> Please Fix CI issues. Thanks

All checks have passed. Can you take a look, please?

**Review by kairu-ms — APPROVED** [review]

**Comment by Arkanayan** [comment]
Thanks, @kairu-ms

**Pull request merged**
