### PR TITLE
add aks update support for http proxy

### PR DESCRIPTION
**Pull request by alexeldeib**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
aks

**Comment by alexeldeib** [comment]
Seems like there is a regression from 2021-07-01 -> 2021-08-01 and later for RP serializing this field back to the user. Nice catch. Wish we realized sooner.

I'll probably have to fix the conversion logic for > 2021-08-01 in RP -> rollout -> circle back here..

**Comment by zhoxing-ms** [comment]
@alexeldeib Any update?

**Comment by alexeldeib** [comment]
something is still not quite right with the live tests, working on it...

**Comment by alexeldeib** [comment]
I'm going to revert this to a draft due to a variety of issues we're working through on the backend related to this feature. 

will circle back when everything is settled.

**Comment by alexeldeib** [comment]
ah, I guess there's no way to change it to a draft? I'll simply close for now.

**Pull request closed without merging**
