### PR TITLE
[Release] Update index.json for extension [ aks-preview ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ aks-preview ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=340888

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/28e108d2d4b06d13a9d3d282f021697a929a98f1

### CODE REVIEW

**Comment by marwanad** [comment]
@fengzhou-msft @haroldrandom this is ready to merge and release.

**Comment by yonzhan** [comment]
add to S168

**Comment by marwanad** [comment]
@qwordy @haroldrandom @arrownj - please ensure this gets merged as this is blocking certain customers scenarios.

**Comment by qwordy** [comment]
> 
> 
> @qwordy @haroldrandom @arrownj - please ensure this gets merged as this is blocking certain customers scenarios.

Done

**Pull request merged**
