### PR TITLE
update vmware extension entry to GA latest v0.7.0

### PR DESCRIPTION
**Pull request by gapariha**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by naman1901** [comment]
Please hold onto reviewing this PR until https://github.com/Azure/az-vmware-cli/pull/43 has completed.

**Comment by yonzhan** [comment]
vmware

**Comment by yungezz** [comment]
hi @arrownj @qwordy could you pls review this PR? thanks

**Comment by qwordy** [comment]
@fengzhou-msft @haroldrandom Do you think we should always use the auto-generated PR to ensure the format of index is correct and to ensure the package is in an unified location?

**Comment by ctaggart** [comment]
Please close and review #2546 instead.

**Comment by ctaggart** [comment]
It would also be great to find out the status on moving the vmware extension code to this repo. #2047

**Pull request closed without merging**
