### PR TITLE
Update image tag used for "no Dockerfile" containerapp up scenario

### PR DESCRIPTION
**Pull request by cormacpayne**
This PR aims to update the Oryx build image tag used by the `az containerapp up` command to construct a `Dockerfile` for the user when the provided `--source` code does not contain a `Dockerfile` itself.

The new image tag will enable the latest versions of supported Oryx platform binaries to be pulled down dynamically when building the `--source`, as well as enable telemetry on the Oryx end.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

`az containerapp up`

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

~- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).~

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by cormacpayne** [comment]
CC: @StrawnSC

**Comment by yonzhan** [comment]
containerapp

**Comment by StrawnSC** [comment]
Blocked until https://github.com/Azure/azure-cli-extensions/pull/5894 is merged

**Review by howang-ms — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@StrawnSC Since https://github.com/Azure/azure-cli-extensions/pull/5894 was merged, could we merge this PR now?

**Comment by StrawnSC** [comment]
@cormacpayne can we go ahead and close this since this change will go out in https://github.com/Azure/azure-cli-extensions/pull/5955?

**Comment by cormacpayne** [comment]
@StrawnSC thanks for the heads up! :shipit:

**Pull request closed without merging**
