### PR TITLE
[Log Analytics Solution] GA Log Analytics Solution

### PR DESCRIPTION
**Pull request by zhoxing-ms**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
log analytics solution

**Comment by kairu-ms** [comment]
Does your PR contains this issue https://github.com/Azure/azure-cli-extensions/issues/3316?

**Comment by zhoxing-ms** [comment]
> Does your PR contain this issue #3316?

Temporarily not. If there is any content that needs to be modified in CLI for this issue, I will add them into this PR.

**Comment by dougbrad** [comment]
Considering further - it is likely this RP will start deprecation process in next 6 months, the replacement functionality might GA in this time.  So it might be best to leave this as experimental.

**Comment by zhoxing-ms** [comment]
OK, we'll keep it as experimental, so I close it first.
If we need GA this PR in the future, I will reopen it~

**Pull request closed without merging**
