### PR TITLE
{AKS} Add delete step for all test cases

### PR DESCRIPTION
**Pull request by bingosummer**
This PR is to add the step to delete cluster for most test cases.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
Could we uniformly add the `aks delete --yes` command by overriding the `remove_resource` method in `AKSCustomResourceGroupPreparer`?

**Comment by zhoxing-ms** [comment]
By the way, could we uniformly add the `aks delete --yes` command by overriding the `remove_resource` method in `AKSCustomResourceGroupPreparer`?

**Comment by bingosummer** [comment]
@zhoxing-ms 
I didn't know ResourceGroupPreparer already has the logic of resource deletion. Then we don't need this PR, I think. Will close.

**Pull request closed without merging**
