### PR TITLE
[dev-spaces] Add deprecation info to dev-spaces extension

### PR DESCRIPTION
**Pull request by amsoedal**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/pull/15785

**Review by arrownj — COMMENTED** [review]
Please follow [this document ](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments)to deprecate command or argument.

**Comment by amsoedal** [comment]
Hi @arrownj can you let me know if it looks alright now?

**Review by arrownj — COMMENTED** [review]
Hi @amsoedal , why the PR title is [AKS] when the actual code change is in `dev-spaces` extension ? And usually we use a separated PR to release the extension (only update version and HISTORY in the PR).

**Comment by amsoedal** [comment]
> Hi @amsoedal , why the PR title is [AKS] when the actual code change is in `dev-spaces` extension ? And usually we use a separated PR to release the extension (only update version and HISTORY in the PR).

Okay, makes sense! I reverted the version change.  I put the as AKS because we belong to the aks command module, (e.g. "az aks use-dev-spaces").  But I will fix the title.

**Comment by amsoedal** [comment]
@arrownj Let me know if it looks good now! Thanks again for the help!

**Review by arrownj — APPROVED** [review]

**Pull request merged**
