### PR TITLE
Add the func list_cluster_monitoring_user_credentials in the vendored sdk for the version v2020_01_01

### PR DESCRIPTION
**Pull request by bingosummer**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by bingosummer** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/8103

**Comment by bingosummer** [comment]
@zqingqing1 Please have a review. Thanks!

**Comment by bingosummer** [comment]
@zqingqing1 / @MyronFanQiu could you please help approve/merge the PR?

**Comment by MyronFanQiu** [comment]
@bingosummer I'm ok with this PR since it doesn't change any CLI code. Do you need sign off from @zqingqing1 ? If you don't need I can merge this one.

**Comment by MyronFanQiu** [comment]
Besides, I'm curious about the purpose of this PR. Since it won't have any impact for customers.

**Comment by bingosummer** [comment]
@MyronFanQiu Without this PR, the function list_cluster_monitoring_user_credentials is missing. When customer runs the following command, he will get an error. Please help merge this PR directly. Thanks.

```
➜  ~ az aks get-credentials -g <resource-group-name> -n <resource-name> -u clusterMonitoringUser
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:

'ManagedClustersOperations' object has no attribute 'list_cluster_monitoring_user_credentials'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.78/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 490, in default_command_handler
    return op(**command_args)
  File "/Users/binxia/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1084, in aks_get_credentials
    credentialResults = client.list_cluster_monitoring_user_credentials(resource_group_name, name)
AttributeError: 'ManagedClustersOperations' object has no attribute 'list_cluster_monitoring_user_credentials'

To open an issue, please run: 'az feedback'
```

**Comment by MyronFanQiu** [comment]
@bingosummer I see. Merged.

**Pull request merged**
