### PR TITLE
[AKS] publishing aks-preview 0.4.35

### PR DESCRIPTION
**Pull request by xizhamsft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by xizhamsft** [comment]
can we re-run the pipeline? the error seems to be transient.

**Comment by xizhamsft** [comment]
@zikalino, @zqingqing1 could you guys take a look?

**Comment by yonzhan** [comment]
add to S167

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks.

**Comment by qwordy** [comment]
✔The file can be downloaded and sha256sum matches.

**Pull request merged**
