### PR TITLE
Support for bulk sim upload in Mobile Network.

### PR DESCRIPTION
**Pull request by rafaeldnferreira**
---

Background:

This adds support for the two bulk sim commands that were not included in the original implementation as the APIs were not implemented in our Resource Provider, this PR rectifies that.

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az mobile-network

https://github.com/Azure/aaz/pull/222

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by jsntcy** [comment]
@rafaeldnferreira,

- Did you update the code using the aaz-dev-tool?
- Did you create a PR in https://github.com/Azure/aaz/pulls to update the model as well?
- If you want to release a new version of extension, please update setup.py with new version and update HISTORY.rst with changes as well.

**Comment by rafaeldnferreira** [comment]
@necusjz : Please advise on the above point around the model changes on aaz repo? My workspace is clean, I'm not entirely sure if I've missed a step. The code has been generated after I have ticked the checkbox in the web ui:

image

**Comment by necusjz** [comment]
Above snapshot is about `generation page`, it's for generating the commands you want.

And aaz repo is associated with another page, i.e., `workspace page`. By clicking the EXPORT button, the changes will take effect on your local aaz folder. After that, you can push them on aaz repo https://github.com/Azure/aaz.

More detailed documentation: https://azure.github.io/aaz-dev-tools/.

**Comment by rafaeldnferreira** [comment]
@necusjz, thanks it did work as expected.
The confusion came from the fact that there was a model generated already, but not the code. I have corrected to have the proper names and that reflected in the generated code as well. The PR is here:

https://github.com/Azure/aaz/pull/222

**Comment by necusjz** [comment]
@rafaeldnferreira I saw there are some inconsistencies between command and changelog:
- bulk-delete-sims vs. bulk-sim-delete
- bulk-upload-sims vs. bulk-sim-upload

Should they be consistent?

**Comment by rafaeldnferreira** [comment]
@necusjz fixed, could you please approve?

**Review by necusjz — APPROVED** [review]

**Pull request merged**
