### PR TITLE
[ai-examples] Update the telemetry, README, and remove pruned responses 

### PR DESCRIPTION
**Pull request by mirdaki**
Updating the telemetry to follow our current pattern. Improve README to be more descriptive of the project. Remove pruned responses from the examples.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
ai-examples

**Comment by haroldrandom** [comment]
Could you fix test failure first?

**Comment by mirdaki** [comment]
@haroldrandom Yes, sorry. Other things came up and I missed seeing the failed tests. I will get the update in by EOD.

**Comment by mirdaki** [comment]
@haroldrandom looks good now! Please let me know if you have any other concerns.

**Comment by mirdaki** [comment]
@haroldrandom thank you for the approval! What needs to be done to merge it in?

**Pull request merged**
