### PR TITLE
Kusto | raise exception when getting ARM Error

### PR DESCRIPTION
**Pull request by zoharHenMicrosoft**
fix https://github.com/Azure/azure-cli-extensions/issues/4086

### CODE REVIEW

**Comment by yonzhan** [comment]
Kusto

**Comment by zoharHenMicrosoft** [comment]
@jsntcy @kairu-ms can you please review and approve?

**Comment by yonzhan** [comment]
We will review after public holiday (1.31-2.6) in China.

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
Hi @zoharHenMicrosoft, don't forget to update the version if you want to release it.

**Comment by zoharHenMicrosoft** [comment]
> Hi @zoharHenMicrosoft, don't forget to update the version if you want to release it.

thanks! fixed

**Comment by zoharHenMicrosoft** [comment]
@kairu-ms @yonzhan @jsntcy Hi folks, the integration tests are failing although it was OK a week ago and I don't think that this is related to any of my changes - it seems like there is a bug in azext_aks_preview/test_aks_create_and_update_outbound_ips test and a regression in the last version of Microsoft.network. 
may I ask for your help? it worked before.

**Comment by kairu-ms** [comment]
> @kairu-ms @yonzhan @jsntcy Hi folks, the integration tests are failing although it was OK a week ago and I don't think that this is related to any of my changes - it seems like there is a bug in azext_aks_preview/test_aks_create_and_update_outbound_ips test and a regression in the last version of Microsoft.network.
> may I ask for your help? it worked before.

Please pull the latest change of azure-cli and azure-cli-extension repos and record test again.

**Comment by zoharHenMicrosoft** [comment]
we will fix it in the next version which will be released very soon

**Pull request closed without merging**
