### PR TITLE
containerapp refactor containerapp auth show/update

### PR DESCRIPTION
**Pull request by Greedygre**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az containerapp auth show/update

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by Greedygre** [comment]
Need to add tests.

**Comment by Juliehzl** [comment]
add test

**Comment by Greedygre** [comment]
> Hi @Greedygre, Please write the description of changes which can be perceived by customers into HISTORY.rst. If you want to release a new extension version, please update the version in setup.py as well.

This pr's changes cannot be perceived by customers. So should not update the history.rst.

**Review by Juliehzl — APPROVED** [review]

**Comment by Greedygre** [comment]
Hi @zhoxing-ms 

This PR has been reviewed by zunli. 
Could you please help to review and merge it when you have chance? Thanks a lot.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
