### PR TITLE
containerapp-preview remove containerapp-preview extension

### PR DESCRIPTION
**Pull request by Greedygre**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by Juliehzl — COMMENTED** [review]
what about index.json?

**Comment by Greedygre** [comment]
> what about index.json?

Hi @zhoxing-ms 
We are going to remove `containerapp-preview` extension in this PR.
We also need to remove the released extension for `containerapp-preview`.
Should I update the `index.json` by myself? Or CLI teams member will help to do that?

Thanks a lot.

**Comment by zhoxing-ms** [comment]
> Should I update the index.json by myself?

@Greedygre Yes, please help submit a separate PR to remove it

**Comment by howang-ms** [comment]
> > Should I update the index.json by myself?
> 
> @Greedygre Yes, please help submit a separate PR to remove it. Additionally, if considering the possibility of a breaking change affecting customer automation scripts _(break the usage of `az extension add -n containerapp-preview)_ , we can consider removing it in the next breaking change window **(Ignite Sprint)**. If there are very few customers currently using it, then we can immediately remove it.

I think it is safe to move. The containerapp-preview just exist for short time and no document is relate to it.

**Comment by Juliehzl** [comment]
@wangzelin007 @zhoxing-ms please remove hack code for container-app-preview in cli core, too

**Review by Juliehzl — APPROVED** [review]

**Comment by Greedygre** [comment]
Hi @zhoxing-ms 
Could you help to review and approve this pr? Thanks.

**Comment by zhoxing-ms** [comment]
> please remove hack code for container-app-preview in cli core, too

Thank you for reminding us. There seems no hack code in our cli core, but may be some hack code for linter and test tasks in our extension CI pipeline.  @wangzelin007 Could you please help check it and remove these hack code?

**Review by zhoxing-ms — APPROVED** [review]

**Comment by wangzelin007** [comment]
> remove hack code for container-app-preview

Create #6616 to revert hack code for containerapp-preview.

**Review by wangzelin007 — APPROVED** [review]

**Comment by Greedygre** [comment]
Hi @zhoxing-ms 
Please help to merge this PR. Thanks.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
