### PR TITLE
IoT extension update 0.9.0 + re-branding to azure-iot

### PR DESCRIPTION
**Pull request by digimaun**
This is a re-branding/re-aliasing of the Azure CLI IoT extension. Instead of the old `azure-cli-iot-ext` the new alias is `azure-iot`. The old references are not removed yet because we don't want to break our users, and we need time to get various docs and script references updated. We'll get a deprecation timeline in play and remove the old alias after.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by blackchoey** [comment]
@digimaun @qwordy Can you please hold on merging this change? We have an Azure Pipelines task depending on this extension and will be impacted by this change. I'm working to update our task and expected to finish by tomorrow. Thank you very much!

**Comment by blackchoey** [comment]
Thanks @yungezz @digimaun @qwordy Please go ahead and merge this change.

**Comment by yungezz** [comment]
suggest to add descriptive information in existing extension to route user to the new extension.

**Comment by digimaun** [comment]
> suggest to add descriptive information in existing extension to route user to the new extension.

We were thinking of doing that after this merge in the following elements:
- IoT extension github readme with clear visible indicators
- Work with the docs team to replace `azure-cli-iot-ext` with `azure-iot` in all references
- Update of the IoT command module 'try out the extension' event handler (for the base CLI) to point to the new name
- Recording a Channel 9 video
- In various communication with users/stakeholders

We could update the existing/old extension information but keep in mind its the same code base and project. That would mean a new release of "v0.8.10" with the old alias and the primary change being to the package description (to state its deprecated).

With this PR, the old extension is not going away until the deprecation timeline ends. Because of this, I think we have more time/flexibility to remove the existing alias in a graceful manner. We just want to make sure the new alias is available on the index (first).

**Comment by yungezz** [comment]
thanks for the detail plan sharing.

**Comment by digimaun** [comment]
Bump. @qwordy , please let me know if you need anything else to merge.

**Pull request merged**
