### PR TITLE
[AKS] Update preview flag

### PR DESCRIPTION
**Pull request by karataliu**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
May I ask do you want to release a new extension version for this change? If so, please also modify `setup.py` and `HISTORY.rst`

**Comment by karataliu** [comment]
@zhoxing-ms this is non-important change, so it can go with other releases. no plan to update version.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
