### PR TITLE
remove azext.maxCliCoreVersion

### PR DESCRIPTION
**Pull request by fengzhou-msft**
We are going to release azure-cli version 2.2.0 on 03/10/2020. The metadata setting: `"azext.maxCliCoreVersion": "2.1.0"` will make extensions incompatible with this new azure cli version.

In this PR, I removed the maxCliCoreVersion settings.

I will upload the new wheels and update index.json later.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
Planned in S166.

**Comment by fengzhou-msft** [comment]
> In our index.json, we have other three extensions(batch-cli, hack and vmware-cs) with max version. I think we should inform them to remove this limitation.

I have informed them about three weeks ago.
Hack already has the PR: https://github.com/Azure/azure-cli-extensions/pull/1309
I will ping the other two teams again.

**Comment by haroldrandom** [comment]
Are you going to help them build and uplpad? Thinking about to leverage the release pipeline?

**Comment by fengzhou-msft** [comment]
> Are you going to help them build and uplpad? Thinking about to leverage the release pipeline?

Need to merge this PR before azure-cli release on Tuesday. Release pipeline is still in progress?

**Comment by haroldrandom** [comment]
> > Are you going to help them build and uplpad? Thinking about to leverage the release pipeline?
> 
> Need to merge this PR before azure-cli release on Tuesday. Release pipeline is still in progress?

Yeah. If that so, can't help here. :(

**Pull request merged**
