### PR TITLE
[Release] Update index.json for extension [ datadog ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ datadog ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=585733

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/e9e2c990833dca3d55f710471240ac4f4dd199cf

### CODE REVIEW

**Comment by yonzhan** [comment]
datadog

**Comment by yungezz** [comment]
hi @fengzhou-msft this will not be released but for build purpose only right?

**Comment by fengzhou-msft** [comment]
> hi @fengzhou-msft this will not be released but for build purpose only right?

Yes, hold off this PR until further notice from service team.

**Comment by fengzhou-msft** [comment]
Close as a new PR will be generated.

**Pull request closed without merging**
