### PR TITLE
{CI} Migrate azure cli extensions pipelines

### PR DESCRIPTION
**Pull request by wangzelin007**
Migrate Azure.azure-cli-extensions pipeline to azclitools org.
[Azure.azure-cli-extensions](https://dev.azure.com/azclitools/public/_build?definitionId=59)
[Azure CLI Extensions Release](https://dev.azure.com/azclitools/internal/_build?definitionId=197)
[Azure CLI Extensions Sync After Release](https://dev.azure.com/azclitools/internal/_build?definitionId=198)
[Azure CLI Extensions Sync to MicrosoftDocs](https://dev.azure.com/azclitools/internal/_build?definitionId=196)

image

### CODE REVIEW

**Comment by yonzhan** [comment]
CI

**Review by yonzhan — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Pull request merged**
