### PR TITLE
[SCVMM] Add support for latest API version

### PR DESCRIPTION
**Pull request by sidsinghms**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az scvmm --help

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
SCVMM

**Comment by sidsinghms** [comment]
> Hi @sidsinghms, Please write the description of changes which can be perceived by customers into HISTORY.rst. If you want to release a new extension version, please update the version in setup.py as well.

Sure.

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by AllyW** [comment]
> ⚠️Azure CLI Extensions Breaking Change Test
> > ⚠️scvmm
> > 
> > 
> > 
> > rule
> > cmd_name
> > rule_message
> > suggest_message
> > 
> > 
> > 
> > 
> > ⚠️ [1010 - ParaPropUpdate](https://github.com/Azure/azure-cli/blob/dev/doc/breaking_change_rules/1010.md)
> > scvmm vm disk add
> > cmd `scvmm vm disk add` update parameter `vhd_type`: updated property `choices` from `['Dynamic', 'Static']` to `['Dynamic', 'Fixed']`
> > 
> > 
> > 
> > ⚠️ [1010 - ParaPropUpdate](https://github.com/Azure/azure-cli/blob/dev/doc/breaking_change_rules/1010.md)
> > scvmm vm disk update
> > cmd `scvmm vm disk update` update parameter `vhd_type`: updated property `choices` from `['Dynamic', 'Static']` to `['Dynamic', 'Fixed']`

@sidsinghms  cmd arg property update count as interface change and please update version to be 1.1.0

**Comment by sidsinghms** [comment]
> Please fix CI issues

addressed👍

**Comment by sidsinghms** [comment]
@yonzhan  / @AllyW 
I have addressed pipeline failures and updated the versioning. 

Looking for the review and closure of this PR. 
Kindly let me know If you need anything else from me.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
