### PR TITLE
[Quantum] Handle more storage types during workspace creation

### PR DESCRIPTION
**Pull request by warren-jones**
If you create a workspace with a storage account that is not “Standard_LRS”, the role assignment fails.  **`az workspace create`** needs to work with more storage account SKUs.  

Restrictions imposed by the new code: 
Only the "Standard" SKU tier is supported.  The storage account Kind is restricted to either "Storage" or "StorageV2".

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

### CODE REVIEW

**Comment by warren-jones** [comment]
Adding test coverage

**Comment by yonzhan** [comment]
Quantum

**Review by vxfield — APPROVED** [review]

**Comment by warren-jones** [comment]
**Reverting to DRAFT status because of new comment on bug report:** 

> Per discussion, we still need to restrict certain storage account types due to known limitations.

**Pull request merged**
