### PR TITLE
Fix for event_system_properties description

### PR DESCRIPTION
**Pull request by navba-MSFT**
Fixes Azure/azure-cli#21849

This PR has the fix for the event_system_properties description and an example to provide multiple system properties

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
kusto

**Comment by navba-MSFT** [comment]
@kairu-ms @yonzhan @jsntcy Could you review this PR once you get a chance ?

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
BTW, if you went to release this update, you need to update the extension version and add release history.

**Comment by navba-MSFT** [comment]
@kairu-ms I didn't use any extensions as I did the changes directly from the github and created the Pull Request.

**Comment by navba-MSFT** [comment]
@kairu-ms @yonzhan @jsntcy Could you please merge this PR once you get a chance ? Awaiting your reply.

**Review by necusjz — APPROVED** [review]

**Pull request merged**
