### PR TITLE
Fix kollect bug with inconsistent container name for private clusters

### PR DESCRIPTION
**Pull request by peterbom**
This fixes a bug in which the storage container used to retrieve Periscope logs is not the same as the one they are uploaded to.

The change is to put all the logic for determining the container name into one function, rather than spreading it throughout the kollect function.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
Please add a description to the history notes `HISTORY.rst`. In addition, if you need to release a new version of extension for this change, please also modify `setup.py`

**Comment by peterbom** [comment]
> Please add a description to the history notes `HISTORY.rst`. In addition, if you need to release a new version of extension for this change, please also modify `setup.py`

Thanks, @zhoxing-ms! I've updated the history file. This bug has been around forever and there's no hurry for a release, so I'm leaving `setup.py` as it is, unless instructed otherwise.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
