### PR TITLE
Remove network security perimeter based access rule creation/updation

### PR DESCRIPTION
**Pull request by kaushal087**
Description:

There can be different types of access rules. e.g. addressPrefix, sms/email, link, nsp etc.

We have removed the support of creation/updation of nsp based access rules from the backend so we are removing the same from CLI as well.

Since our service is in private preview, we don't support multiple version as of now and we make the changes in the existing version even if it is breaking change. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

aaz PR: https://github.com/Azure/aaz/pull/252

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by necusjz** [comment]
@kaushal087 I understood your needs, but why there're so many codes affected? Even other modules, i.e., containerapp.

**Comment by kaushal087** [comment]
> @kaushal087 I understood your needs, but why there're so many codes affected? Even other modules, i.e., containerapp.

@necusjz Removed the other modules from the PR. These all code is part of "nsp" extension. These all were automatically generated when I checked the API commands and clicked on generate.

image

**Comment by necusjz** [comment]
@kaushal087

Thanks for removing `containerapp`. To continue narrow down its scope, you can refer to https://azure.github.io/aaz-dev-tools/pages/usage/cli-generator/#pick-commands.

It'll modify the commands you want, BTW, https://github.com/Azure/azure-cli-extensions/pull/6570#issuecomment-1653653919 is also required.

**Review by necusjz — APPROVED** [review]

**Pull request merged**
