### PR TITLE
aksarc 1.0.0b1 VMware support release

### PR DESCRIPTION
**Pull request by TheOnlyWei**
### Related command
az aksarc
https://learn.microsoft.com/en-us/cli/azure/aksarc?view=azure-cli-latest

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
**Note**: `azdev style <YOUR_EXT>` is not enforced currently for our extension in our private repository.
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### About Extension Publish
**Note that we are releasing an extension from a private repository and need to manually update the `src/index.json`!**

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by jsntcy — CHANGES_REQUESTED** [review]
The new version looks weird as the extension has already been released with version `1.0.0`, `1.0.2`, .....`1.1.1`, usually the next version should be larger than `1.1.1`.

image

**Comment by TheOnlyWei** [comment]
@jsntcy as mentioned in previous PR, we are trying to release an older version. Do you want us to change th version again? You said it should be 1.0.0 or 1.0.0b1.

**Comment by jsntcy** [comment]
> @jsntcy as mentioned in previous PR, we are trying to release an older version. Do you want us to change the version again? You said it should be 1.0.0 or 1.0.0b1. Our product is a special case currently, because our main branch, which are the stable releases, doesn't support the platform which our 1.0.0b1 release supports, and vice versa, the code in the specific release of our 1.0.0b1 extension doesn't have certain features that the stable release supports. So, we are kind of forced to release via an older version to preserve customer experience.
> 
> [#7409 (comment)](https://github.com/Azure/azure-cli-extensions/pull/7409#discussion_r1534999295)

As your source code is not in our extension repo, so it's a little difficult for us to know which versions you have released. In this review, I expanded and scrolled down index.json file and found you have already released 1.0.0, 1.0.2, .....1.1.1 before. But in last review https://github.com/Azure/azure-cli-extensions/pull/7409#discussion_r1534999295, you released as `0.2.0b1`, as a common sense of versioning, I supposed you never released version `1.x.x` before as we never release a new version with smaller number than before.

As your code is not in our repo, it's difficult for us to suggest a specific version for you as we don't know if the new version has breaking changes or not (or release it as preview or stable) , but we can suggest some versions per different scenarios:

- If this new version has breaking changes, you should release it as `2.0.0b1` (preview), or `2.0.0` (stable)
- If this new version has no breaking changes, you should release it as `1.2.0b1` (preview), or `1.2.0` (stable)
- If this new version is just a bug fix, you should release it as `1.1.2b1` (preview), or `1.1.2` (stable)

Actually based on our [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md), you can figure out the correct version yourself.

BTW, if possible, we suggest you move your source code to our extension repo, so that you can leverage our CI/CD including breaking change detection, version suggestion and etc.

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
