### PR TITLE
mesh 6.4 updates

### PR DESCRIPTION
**Pull request by jeffj6123**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by williexu** [comment]
Please fix the CI, the metadata added must match the METADATA.json from your wheel.
Also, please rebase from `master` to update this PR

**Comment by jeffj6123** [comment]
How can I add a do not merge tag? I wanted to get the PR ready but it might be a few days before it should get merged in.

**Comment by williexu** [comment]
@jeffj6123 done :)

**Comment by jeffj6123** [comment]
#signoff

**Pull request merged**
