### PR TITLE
[Quantum] Quantum CLI Extension Release, Version 1.0.0b4 

### PR DESCRIPTION
**Pull request by warren-jones**
Updated version number and release notes

---

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### CODE REVIEW

**Comment by yonzhan** [comment]
Quantum

**Comment by warren-jones** [comment]
I updated this PR to "ready for review" this morning, but then received an email about a minor change that has a 10/31/2024 deadline.  I converted the release PR back to a Draft so I can incorporate that new change in the release -- may delay the release a couple days.

**Comment by warren-jones** [comment]
Updated the release date in HISTORY.rst and submitted [PR 8113](https://github.com/Azure/azure-cli-extensions/pull/8113) to initiate the release process

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
