### PR TITLE
Stackhcivm 0.1.8

### PR DESCRIPTION
**Pull request by wyatt-troia-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
  - This command has never worked for us
- [X] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yonzhan** [comment]
Please fix the conflicting files

**Comment by wyatt-troia-msft** [comment]
> Please fix the conflicting files

Done. I had neglected to update my fork based on the upstream (this repo).

**Comment by kairu-ms** [comment]
There are some invalid examples in your code https://dev.azure.com/azclitools/public/_build/results?buildId=111708&view=logs&j=ccdac6d3-465a-5ada-8819-d5b4a6b3a631&t=0babf5d5-1acc-5198-6505-1f9f83b6d5c0&l=134

**Comment by kairu-ms** [comment]
BTW, the linter failed because of https://dev.azure.com/azclitools/public/_build/results?buildId=111708&view=logs&j=b121d099-c3c0-52ad-95f1-31c1567c9ad4&t=ca40adef-e63f-5fd5-f30e-e39a0bf0e914&l=358

**Comment by wyatt-troia-msft** [comment]
> BTW, the linter failed because of https://dev.azure.com/azclitools/public/_build/results?buildId=111708&view=logs&j=b121d099-c3c0-52ad-95f1-31c1567c9ad4&t=ca40adef-e63f-5fd5-f30e-e39a0bf0e914&l=358

I don't understand this error. I've compared the metadata for the new block I'm adding and the block for the last version of stack-hci-vm and they seem to be identical. How can we figure out what the problem is?

**Comment by kairu-ms** [comment]
> > BTW, the linter failed because of https://dev.azure.com/azclitools/public/_build/results?buildId=111708&view=logs&j=b121d099-c3c0-52ad-95f1-31c1567c9ad4&t=ca40adef-e63f-5fd5-f30e-e39a0bf0e914&l=358
> 
> I don't understand this error. I've compared the metadata for the new block I'm adding and the block for the last version of stack-hci-vm and they seem to be nearly identical. The error seems to be saying that the metadata for version 1.8 should say that its version is 1.5. Why would that be?

Can you verify the whl package in the download link is version 1.8?

**Comment by ggaurav10** [comment]
> > > BTW, the linter failed because of https://dev.azure.com/azclitools/public/_build/results?buildId=111708&view=logs&j=b121d099-c3c0-52ad-95f1-31c1567c9ad4&t=ca40adef-e63f-5fd5-f30e-e39a0bf0e914&l=358
> > 
> > 
> > I don't understand this error. I've compared the metadata for the new block I'm adding and the block for the last version of stack-hci-vm and they seem to be nearly identical. The error seems to be saying that the metadata for version 1.8 should say that its version is 1.5. Why would that be?
> 
> Can you verify the whl package in the download link is version 1.8?

@kairu-ms from the pipeline error logs, I see that the metadata shows version as 0.1.5 whereas the changes in the PR has it as 0.1.8
image
image

I have also verified from the file that the metadata version is indeed 0.1.8

image

Is there a different place from where the pipeline is picking up the version?

**Comment by ggaurav10** [comment]
@wyatt-troia-msft @Arkanayan do we need this kind of change before we build the whl file?
https://msazure.visualstudio.com/msk8s/_git/azstackhci-util/pullrequest/8265079

**Comment by Arkanayan** [comment]
We can close this as these changes are merged in https://github.com/Azure/azure-cli-extensions/pull/7052

**Pull request closed without merging**
