### PR TITLE
[AKS] Fix load balancer validation issue

### PR DESCRIPTION
**Pull request by FumingZhang**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

Fix [issue #20693](https://github.com/Azure/azure-cli/issues/20693).
Original [PR #4174](https://github.com/Azure/azure-cli-extensions/pull/4174).
[PR discussion](https://github.com/Azure/azure-cli-extensions/pull/4174#discussion_r763239398).

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by FumingZhang** [comment]
Before the fix
Screenshot 2021-12-13 133041

After the fix (the public ip resource does not meet the requirement, which is intended)
Screenshot 2021-12-13 132935

**Review by tyler-lloyd — APPROVED** [review]
~LGTM~ ... please see #4219

**Comment by wasker** [comment]
As much as I appreciate a quick fix for the issue, I'm surprised to not see any changes in test coverage. As a consumer of this functionality I shouldn't be the one to find a problem like that after what appears to be a significant refactoring (i.e. introducing support for dual-stack clusters). However, even after the issue _was_ found, it seems prudent to update unit tests to prevent such issues from happening ever again.

**Review by tyler-lloyd — CHANGES_REQUESTED** [review]
Please see #4219 for a more complete fix.

**Comment by FumingZhang** [comment]
> As much as I appreciate a quick fix for the issue, I'm surprised to not see any changes in test coverage. As a consumer of this functionality I shouldn't be the one to find a problem like that after what appears to be a significant refactoring (i.e. introducing support for dual-stack clusters). However, even after the issue _was_ found, it seems prudent to update unit tests to prevent such issues from happening ever again.

@wasker Thanks for your suggestions. We've got a more complete PR to fix this problem, which also includes more test cases to cover the dual stack scenario. It is expected that the fix version v0.5.48 will be available on 12.15.

**Pull request closed without merging**
