### PR TITLE
[Spring] Support managed component log stream

### PR DESCRIPTION
**Pull request by jiec-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az spring

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Spring

**Comment by zhoxing-ms** [comment]
@jiec-msft Could you please resolve these CI issues?

**Comment by jiec-msft** [comment]
> @jiec-msft Could you please resolve these CI issues?

@zhoxing-ms Fixed for the tests.

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@jiec-msft Please remember to submit a separate PR to fix these code style issues that are not related to this PR in the future, thanks

**Comment by jiec-msft** [comment]
> @jiec-msft Please remember to submit a separate PR to fix these code style issues that are not related to this PR in the future, thanks

Thanks! I'll work with this PR: https://github.com/Azure/azure-cli-extensions/pull/7116, will ping you later when it's ready for review.

**Pull request merged**
