### PR TITLE
[Spring-Cloud] Enable deployment input for az spring-cloud app logs

### PR DESCRIPTION
**Pull request by xinyi-joffre**
---

This PR addresses #2751.

It enables a deployment flag for the the command:

az spring-cloud app logs --deployment <staging slot name>

This is a huge quality of life improvement. Since we use staging slots, when new deployments go awry, we are often debugging the staging slot deployment, instead of the production one. This allows us to target the right deployment slot.

---
### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [N/A] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by xinyi-joffre** [comment]
This fixes issue #2751

**Comment by xinyi-joffre** [comment]
As FYI, I ran azdev style spring-cloud and it passed flake8, but pylint had many failures that were there before this PR.

**Comment by xinyi-joffre** [comment]
FYI, @selvasingh

**Comment by xinyi-joffre** [comment]
@fengzhou-msft

**Comment by yonzhan** [comment]
spring-cloud

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
@xinyi-joffre another version has been released first. Can you update the version and resolve conflicts?

**Comment by xinyi-joffre** [comment]
@fengzhou-msft, fixed the merge issues!

**Comment by sophiaso** [comment]
@xinyi-joffre Thank you for your PR, currently we are tracking this, may plan to future releases.

**Comment by fengzhou-msft** [comment]
@sophiaso when do you think this PR can be merged?

**Comment by sophiaso** [comment]
@xinyi-joffre Sorry for the late update, could you help the merge the conflict? We need some verification from our side, at the same time, is it possible we can add some test cases?

**Comment by sophiaso** [comment]
@fengzhou-msft OK to merge for me.

**Pull request merged**
