### PR TITLE
Fix Executable File Not Found Error

### PR DESCRIPTION
**Pull request by jmostella**
* storage-preview/azext_storage_preview/azcopy/util.py changed subprocess.call() param to array

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jmostella** [comment]
I found this issue when running the command: `az storage azcopy blob upload ...` on __Linux__

The issue is that the call to `subprocess.call()` with the `args` param as a `str` results in a `FileNotFoundError` error: 

```console
FileNotFoundError: [Errno 2] No such file or directory: '/home/__REDACTED__/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.3.1/azcopy copy dist/__REDACTED__/** https://__REDACTED__.blob.core.windows.net/$web/?se=2020-07-13T16%3A42%3A15Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=__REDACTED__%3D --recursive'
```
This DOES work on __Windows__ however on __*nix__, it treats the entire string as the executable name. The behavior of `subprocess.call()`, when passed a `str` is documented as platform-dependent (refer to this [StackOverflow answer](https://stackoverflow.com/a/15109975))

**Comment by yonzhan** [comment]
add to S173

**Comment by Juliehzl** [comment]
Hi @jmostella, thanks for your fix and I will help you merge the PR. In addition, for azcopy related commands, we already supported them in azure cli, e.g. `az storage blob sync`, `az storage copy`, `az storage remove` and you can have a try.

**Comment by jmostella** [comment]
@Juliehzl Thanks a lot! I'll have a look at those other commands as well. 

Basically our use case is that we want to upload a web app directory tree to blob storage. Since we are using [Static website hosting in Azure Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website).

**Pull request merged**
