### PR TITLE
{vm-repair} Fix public IP turn off option

### PR DESCRIPTION
**Pull request by Sandido**
---
Taking over this PR: https://github.com/Azure/azure-cli-extensions/pull/7866

This PR fixes a longstanding bug where the option to not create a public IP was broken and would just create a public IP with the name False. Now a private ip will be used if the --associate-public-ip parameter is not provided by the user.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yanzhudd** [comment]
please resolve code conflicts

**Comment by Sandido** [comment]
@yanzhudd please re-review!

**Comment by yonzhan** [comment]
This PR is still in draft status

**Comment by Sandido** [comment]
@yonzhan , temporarily in draft, please review.

**Comment by Sandido** [comment]
@yonzhan , was temporarily in draft, ready for re-review!

**Comment by yanzhudd** [comment]
it looks good to me.
but please note that Azure CLI is only responsible for code style and specification but not business logic, so it is better to involve service team to review it as well.

**Review by EdwinBernal1 — APPROVED** [review]

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
