### PR TITLE
[k8s-extension] Release for GA v1.0.0

### PR DESCRIPTION
**Pull request by jonathan-innis**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
> Could you add some new tests for the new command and new changes?

We have some E2E tests that we run locally which don't ship with the PR. Is there a good way to perform mocking on this call rather than a scenario test? Since the request/response will not be consistent for these update calls when operations are `InProgress`

**Comment by zhoxing-ms** [comment]
> Is there a good way to perform mocking on this call rather than a scenario test? Since the request/response will not be consistent for these update calls when operations are InProgress

@jonathan-innis  May I ask how long will those operations last in phase `InProgress`? If it doesn't take too long, could we wait for the completion of the operation through `az resource wait` or `time.sleep(xxx)`?

**Comment by zhoxing-ms** [comment]
@NarayanThiru Thank you for your detailed clarification. I would like to ask what problems will be caused by setting up a K8s cluster in the test?

**Comment by NarayanThiru** [comment]
> > Since we cannot set up a K8s cluster as part of the testing, we are not adding Patch scenario tests here.
> 
> @NarayanThiru Thank you for your detailed clarification. I would like to ask what problems will be caused by setting up a K8s cluster in the test?

Setting up a K8s cluster involves not just creating one, but also projecting it to Azure, which requires using another RP's CLI, which is an additional dependency.  In addition, this projection involves creating MSI Identity for the cluster, which can take up to 10 minutes to provision Certificate that is required for Authn.  After all of this is done, the Cluster should connect to our DataPlane and start heartbeating.  Only after this, can we create the Extension, which gets created only in the Service.  This then gets picked up by the Agent in the cluster and installed.  Then it sends back the status to the Service (DataPlane).  This can take multiple minutes depending on the connectivity and other delays.  But, most importantly these are all steps that are not under test.  This is why we have created a pipeline for all our CLI changes that exercises all these steps in our private fork.  It is only after it succeeds in that, do we push to main.   So, if you concern is that this is untested code, please rest assured, we test it thoroughly before pushing.  In addition, as I explained earlier, it continues to get tested in Production as well - as frequently as every 15 minutes.  I hope this gives details on why we don't want to do this.

**Pull request merged**
