### PR TITLE
Fix param name fix for disk override

### PR DESCRIPTION
**Pull request by nascarsayan**
Changes:
* Fix docs and help for vm creation from template with disk override.
* Convert any HCRP machine with empty kind to VMWare / AVS kind, while enabling vm from inventory.
* Password Reprompt fix for `vcenter connect`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yanzhudd** [comment]
please add test for the changes.

**Comment by yanzhudd** [comment]
Since Azure CLI team is only responsible for the code style and specifications but not the business logic, it is better to involve the relevant service team in reviewing the business logic for this PR as well.

**Comment by nascarsayan** [comment]
> please add test for the changes.

The changes are quite small and covers edge cases.

- Fix docs and help for vm creation from template with disk override.
  This is change for `--help`, and there is no testable code here.
- Convert any HCRP machine with empty kind to VMWare / AVS kind, while enabling vm from inventory.
  This is an edge case, where requiring agent install from an existing VM in onprem. Having a machine ready, and using that machine everytime for running UTs will be difficult (a manual step outside tests need to performed). We already have the test cases covering create machine + create VMInstance, where we create and delete all the resources.
- Password Reprompt fix for vcenter connect
  This is a reprompt for the user, it was a miss from before.

**Comment by yanzhudd** [comment]
> > please add test for the changes.
> 
> The changes are quite small and covers edge cases.
> 
> * Fix docs and help for vm creation from template with disk override.
>   This is change for `--help`, and there is no testable code here.
> * Convert any HCRP machine with empty kind to VMWare / AVS kind, while enabling vm from inventory.
>   This is an edge case, where requiring agent install from an existing VM in onprem. Having a machine ready, and using that machine everytime for running UTs will be difficult (a manual step outside tests need to performed). We already have the test cases covering create machine + create VMInstance, where we create and delete all the resources.
> * Password Reprompt fix for vcenter connect
>   This is a reprompt for the user, we are reprompting for empty value as password.

okay, how about rerunning the related test in live mode? Just make sure this change would not affect other normal logic.

**Comment by subbartt** [comment]
> Since Azure CLI team is only responsible for the code style and specifications but not the business logic, it is better to involve the relevant service team in reviewing the business logic for this PR as well.

LGTM, for some some reason I was not able to review, are there any groups I need to join?

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
