### PR TITLE
Vmware 4.0.0 publish

### PR DESCRIPTION
**Pull request by jonathanhe-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Review by cataggar — APPROVED** [review]
Thanks for adding the additional tests.

**Comment by jonathanhe-msft** [comment]
@zhoxing-ms please review. This is the final PR for the vmware 4.0.0 release. Thank you for the help!

**Comment by yonzhan** [comment]
Vmware

**Review by wangzelin007 — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by cataggar** [comment]
It looks like it was not published to the index.json yet. #4136

**Pull request merged**
