### PR TITLE
ArcAppliance July Release 0.2.25

### PR DESCRIPTION
**Pull request by saisankargochhayat**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Review by amanohar — APPROVED** [review]

**Comment by pkoushik** [comment]
Versions kept in index.json LGTM

**Comment by yonzhan** [comment]
ArcAppliance

**Comment by saisankargochhayat** [comment]
Please merge

**Comment by kairu-ms** [comment]
> Please merge

please fix ci issues,

**Comment by saisankargochhayat** [comment]
> > Please merge
> 
> please fix ci issues,

https://github.com/Azure/azure-cli-extensions/pull/5114/files
It seems to be unrelated to my PR - 
Traceback (most recent call last):
  File "/home/vsts/work/1/s/./scripts/ci/test_index.py", line 115, in test_checksums
    self.assertEqual(computed_hash, item['sha256Digest'],
AssertionError: 'e7f1b203399906812680aaed0e3f6e21000967e0699482d97e1c449035a8bc6a' != '4772faa76fb7516bd7cfbadd58cf20e63b43e49fdf93f019052f2e253cf99604'
- e7f1b203399906812680aaed0e3f6e21000967e0699482d97e1c449035a8bc6a
+ 4772faa76fb7516bd7cfbadd58cf20e63b43e49fdf93f019052f2e253cf99604
 : Computed e7f1b203399906812680aaed0e3f6e21000967e0699482d97e1c449035a8bc6a but found 4772faa76fb7516bd7cfbadd58cf20e63b43e49fdf93f019052f2e253cf99604 in index for aks_preview-0.5.89-py2.py3-none-any.whl
 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1706723&view=logs&j=b121d099-c3c0-52ad-95f1-31c1567c9ad4&t=ca40adef-e63f-5fd5-f30e-e39a0bf0e914&l=59

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
