### PR TITLE
Fix Azure Quantum CLI extension tests

### PR DESCRIPTION
**Pull request by vxfield**
This PR updates the test cases for the Azure Quantum CLI extension, removing references to the deprecated `Microsoft QIO` provider and replacing it with the `Microsoft QC` provider as needed.

It also updates the test recordings, to make sure they run properly.

**Note: this PR only changes the test logic and has no impact on the actual extension logic. We don't need a new release.** 

### Related command

`az quantum`

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by masenol — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by vxfield** [comment]
> Please fix CI issues.

@yonzhan ,

I can’t find the cause of the CI failure.
It seems to be related to the integration tests with some Python versions but they seem unrelated to my changes.

Could you double check this is not a pipeline issue?
Or give me some pointers on how I can fix it, as the error messages are too high level and apparently unrelated to the Quantum extension?

**Comment by kairu-ms** [comment]
> > Please fix CI issues.
> 
> @yonzhan ,
> 
> I can’t find the cause of the CI failure. It seems to be related to the integration tests with some Python versions but they seem unrelated to my changes.
> 
> Could you double check this is not a pipeline issue? Or give me some pointers on how I can fix it, as the error messages are too high level and apparently unrelated to the Quantum extension?

When you record tests, please make sure the latest change of `dev` branch of **azure-cli** has been synced to your local repo.
Developers will always encounter this issue when the tests passed locally but failed in CI. This is because the api versions used by commands of **azure-cli** can be changed in `dev` branch. When the tests recorded in your local may uses out of date azure-cli commands, the recording will be failed in CI. That's why we need to sync the latest change of `dev` branch of **azure-cli** before recording tests.

**Comment by vxfield** [comment]
@yonzhan, @kairu-ms,

I got the latest `dev` from Azure CLI repo and re-recorded the tests, and the CI is still failing.

I created another PR to show that the CI pipeline is probably broken and that is has nothing to do with the test recordings or changes in this PR.

#6544 has just a comment, and the CI pipeline fails on the same integration tests.

**Comment by wangzelin007** [comment]
Hi @vxfield,
Checking the error message of PR 6544, we can see that only one test test_workspace failed, and the reason for the failure was that the api-version was upgraded to 2022-09-01, but 2021-04-01 is still used in recording, so you need to re-run the live test and upload a new recording file, which has nothing to do with the reason for the failure of this PR.

### The reasons for the three test errors in this PR are as follows:
- test_jobs: The resource group used in the test code is [e2e-scenarios](https://github.com/Azure/azure-cli-extensions/blob/4766187a7734bb627dc7df728a385b9e131e2057/src/quantum/azext_quantum/tests/latest/utils.py#L7 ), the recording is azure-sdk-test-rg, so the verification fails.
- test_targets: The workspace used in the test code is [e2e-qsharp-tests](https://github.com/Azure/azure-cli-extensions/blob/4766187a7734bb627dc7df728a385b9e131e2057/src/quantum/azext_quantum/tests/latest/utils.py#L8 ), and the recording is azure-sdk-test-aqw, so the verification fails.
- test_workspace: The location used in the test code is [westus2](https://github.com/Azure/azure-cli-extensions/blob/4766187a7734bb627dc7df728a385b9e131e2057/src/quantum/azext_quantum/tests/latest/utils.py#L9 ), recording The file contains eastus, so the verification fails.
Please check again to ensure that the generated recording file is exactly the same as the test code.
image

**Comment by vxfield** [comment]
Thanks for the info on the errors, @wangzelin007 !

@yonzhan, @kairu-ms: I was able to fix the CI issues. Thank you for your patience.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
