### PR TITLE
{AKS} move KMS to GA

### PR DESCRIPTION
**Pull request by bingosummer**
* Do not backfill parameters in aks-preview
* Remove "is_preview=True" from KMS parameters
* Remove "--aks-custom-headers AKSHTTPCustomFeatures=Microsoft.ContainerService/AzureKeyVaultKmsPreview" from the test codes.

### CODE REVIEW

**Comment by bingosummer** [comment]
https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=58097337&view=results

**Comment by yonzhan** [comment]
AKS

**Comment by bingosummer** [comment]
https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=58143259&view=results

**Comment by bingosummer** [comment]
https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=58198057&view=results

**Review by FumingZhang — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
