### PR TITLE
[image-copy] Fix copying images created from a blob

### PR DESCRIPTION
**Pull request by tamirkamara**
The snapshot/create command now requires a storage-account-id parameter when creating snapshots from blob objects. This PR addresses that issue and fixes https://github.com/Azure/azure-cli/issues/12177.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

**Comment by qwordy** [comment]
Please modify setup.py. Remove Python2.
Example:
```
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
```

**Comment by tamirkamara** [comment]
I've remove the 2 line of python 2, but now the ci fails but it doesn't really output why.
Can you help @qwordy ?

**Comment by qwordy** [comment]
I pull your code and run `azdev linter image-copy`. There is no error.

**Comment by qwordy** [comment]
@haroldrandom Do you have method to show detailed error in pipeline. It only says exit with code 1.

**Pull request merged**
