### PR TITLE
[Release] Update index.json for extension [ k8s-extension ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ k8s-extension ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=1010584

Last commit against main: https://github.com/Azure/azure-cli-extensions/commit/12fca0873ce466a0e113a82f12ab885de3a699ba

### CODE REVIEW

**Comment by yonzhan** [comment]
k8s-extension

**Comment by jonathan-innis** [comment]
Hold this change, there is a fix that needs to go for this version

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@jonathan-innis Sorry, I didn't notice the information you mentioned above before. I reversed this PR merge, and you can still use this version to release fix

**Comment by jonathan-innis** [comment]
Hey @zhoxing-ms, since #3692 was merged. As long as the version released for v0.6.0 includes this change, we are good for release. Thanks

**Comment by zhoxing-ms** [comment]
That sounds good~

**Pull request merged**
