### PR TITLE
[ContainerApp] Fix #501: az containerapp create --allow-insecure: Add Flag to Allow Container App Insecure Ingress

### PR DESCRIPTION
**Pull request by Juancpani**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
ContainerApp

**Review by smzeng — COMMENTED** [review]
add a test? Not having a test might block you from getting merged. Or maybe just edit a current one since its a small change

**Review by smzeng — COMMENTED** [review]
is this just for create, we aren't adding it to update?

**Review by smzeng — COMMENTED** [review]
also update the src/containerapp/HISTORY.rst file with this change just for book keeping

**Comment by Juancpani** [comment]
Need to review functionality in ingress vs. egress contexts.

**Comment by Juancpani** [comment]
> is this just for create, we aren't adding it to update?

update already has it, just create was missing it.

**Comment by cormacpayne** [comment]
> > is this just for create, we aren't adding it to update?
> 
> update already has it, just create was missing it.

@Juancpani I see the `--allow-insecure` flag for the `az containerapp ingress update` command but not for `az containerapp update` -- just wanted to double-check if that's what we were expecting, or if it needed to be added to the latter command.

**Comment by Juancpani** [comment]
> > > is this just for create, we aren't adding it to update?
> > 
> > 
> > update already has it, just create was missing it.
> 
> @Juancpani I see the `--allow-insecure` flag for the `az containerapp ingress update` command but not for `az containerapp update` -- just wanted to double-check if that's what we were expecting, or if it needed to be added to the latter command.

Just realized my mistake, custom.py was `update_ingress` which functions as the ingress update function, but no `containerapp update` isn't used to update any of the previous ingress settings, so I doubt it will need this flag.

**Review by smzeng — COMMENTED** [review]
Not sure you did this already, but you can setup a storage account and upload a build of your cli environment as a whl using 
`azdev extension publish containerapp --storage-account STORAGE_ACCOUNT --storage-container STORAGE_CONTAINER --storage-account-key STORAGE_KEY`

then anyone can add that version of the cli with `az extension add --upgrade --source LINKTOWHL`

If you do that, leave a comment and then I can also help test out the changes that way

**Review by smzeng — APPROVED** [review]

**Comment by Juancpani** [comment]
@yonzhan this is ready to go!

**Review by zhoxing-ms — APPROVED** [review]

**Review by Greedygre — APPROVED** [review]

**Pull request merged**
