### PR TITLE
update remote connection

### PR DESCRIPTION
**Pull request by patricklee2**
merge after 5/6

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by patricklee2** [comment]
this is ready for review

**Comment by panchagnula** [comment]
Didn't you move  this to core already any reason you want the changes here in the extension as well?

**Comment by panchagnula** [comment]
Also been a while since I worked on extensions - do you not need to update the version # anymore for this to take effect?

**Comment by patricklee2** [comment]
I only really need the warning message, I fixed some bugs while I was here.
I added the versions update

**Comment by panchagnula** [comment]
@patricklee2  can you merge your branch to the latest & i can merge. Looks like the changes to cli-core are now live.

**Comment by panchagnula** [comment]
@patrick the new changes are missing the the version updates & the whl file updates? Di we not need that anymore?

**Comment by patricklee2** [comment]
oops removed them by accident, let me fix that

**Pull request merged**
