### PR TITLE
{AKS} Update version to 0.5.52

### PR DESCRIPTION
**Pull request by FumingZhang**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

Release version 0.5.52 for aks-preview.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by FumingZhang** [comment]
Please help merge this PR after [#4362](https://github.com/Azure/azure-cli-extensions/pull/4362) and [#4363](https://github.com/Azure/azure-cli-extensions/pull/4363) are merged, thanks!

**Comment by yonzhan** [comment]
AKS

**Comment by FumingZhang** [comment]
The failed test cases `test_aks_nodepool_update_taints_msi` and `test_aks_create_and_update_outbound_ips` in CI should be fixed in PR [#4393](https://github.com/Azure/azure-cli-extensions/pull/4393).

**Comment by FumingZhang** [comment]
The failed test case `test_aks_create_and_update_ipv6_count` in CI should be fixed in PR []().

**Review by wangzelin007 — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
