### PR TITLE
Fix the persicope version to always point to latest tag.

### PR DESCRIPTION
**Pull request by Tatsinnit**
---

Thanks @JunSun17 for discussion and please eyeball this PR.

* This PR will fix the exisitng issue folks are facing with respect to the broken functionality of periscope for any `aks cluster` above 1.14. The fix was checkin for `periscope` repo in march, but the issue was the wrong reference in the cli-extension to a release tag which is old.

* Discussed this and since we now have `latest` tag no more individual release of version update will be needed.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by Tatsinnit** [comment]
📓  /assign @JunSun17 -- context et. al. Thanks.

**Comment by JunSun17** [comment]
LGTM.

**Comment by yonzhan** [comment]
add to S169

**Comment by yungezz** [comment]
hi @arrownj could you pls review and take care of the PR? thanks

**Pull request merged**
