### PR TITLE
[Release] Update index.json for extension [ appservice-kube ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ appservice-kube ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=1386720

Last commit against main: https://github.com/Azure/azure-cli-extensions/commit/4fbcd8fcc049730f65d92a30da1eb8628559b76b

### CODE REVIEW

**Comment by yonzhan** [comment]
appservice-kube

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
CI has the following issue:
> ImportError: cannot import name '_FunctionAppStackRuntimeHelper' from 'azure.cli.command_modules.appservice.custom'

It is due to the introduction of PR https://github.com/Azure/azure-cli-extensions/pull/4384#discussion_r813646331 @StrawnSC Please take a look~

**Comment by StrawnSC** [comment]
@zhoxing-ms what version of the CLI does the CI use? 

This appservice-kube extension uses features that are set to be released with CLI version `2.34.0` (currently in the dev branch of the CLI). In the extension, I set the min CLI version to `2.34.0` so that users won't run into this incompatibility. Will this have to wait until that version is released?

**Comment by panchagnula** [comment]
> @zhoxing-ms what version of the CLI does the CI use?
> 
> This appservice-kube extension update uses features that are set to be released with CLI version `2.34.0` (currently in the dev branch of the CLI). In the extension, I set the min CLI version to `2.34.0` so that users won't run into this incompatibility. Will this have to wait until that version is released?

@StrawnSC the AppServicePlan-kube extension has an explicit import statement here for sporting file _FunctionAppStackRuntimeHelper - was this  removed in core-cli, which means once this releases, this extension will break. 
https://github.com/Azure/azure-cli-extensions/blob/da0dbf8cd9939c4b533bb166503856c6db94d192/src/appservice-kube/azext_appservice_kube/custom.py#L40

The CI/CD here might be using the latest available dev & hence catching this earlier. We should fix this soon.

**Comment by StrawnSC** [comment]
@panchagnula the class `_FunctionAppStackRuntimeHelper` was added recently by my runtime stacks update (not removed): https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3127 

It's not in a released version of the CLI yet though so the CI must be using the prod version of the CLI instead of building from dev

**Comment by StrawnSC** [comment]
@zhoxing-ms could we rerun the CI on March 1st when CLI version `2.34.0` is released?

**Comment by zhoxing-ms** [comment]
> could we rerun the CI on March 1st when CLI version 2.34.0 is released?

OK

**Comment by panchagnula** [comment]
> @panchagnula the class `_FunctionAppStackRuntimeHelper` was added recently by my runtime stacks update (not removed): https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3127
> 
> It's not in a released version of the CLI yet though so the CI must be using the prod version of the CLI instead of building from dev

Ah! I see so the extension was updated to use this import before the changes to core-cli was released to PROD? that explains the error - we should wait for the dependent changes to release then. In addition running the CI/CD pipeline, can we test the changes as well before we release the new extension?

**Comment by StrawnSC** [comment]
@panchagnula I manually tested the changes locally. I can go ahead and start adding some ScenarioTests too

**Comment by StrawnSC** [comment]
> > could we rerun the CI on March 1st when CLI version 2.34.0 is released?
> 
> OK

@zhoxing-ms can you rerun the CI. It looks like I don't have permissions to do so

**Comment by yonzhan** [comment]
Please resolve the conflicting files

**Comment by StrawnSC** [comment]
I'm tried to push a fix to the merge conflict here, but I don't have permissions to push to the `azclibot/azure-cli-extensions` repo

It's a pretty simple merge conflict. Could someone with permissions fix it or give me permissions to push?

**Comment by zhoxing-ms** [comment]
Replaced by #4481

**Comment by StrawnSC** [comment]
Thanks @zhoxing-ms!

**Pull request closed without merging**
