### PR TITLE
Codespaces CLI release v0.2.0

### PR DESCRIPTION
**Pull request by derekbekoe**
* Update to 2020-05-26 API version.
* Plan creation supports subnets.
* New `az codespace update` command.
* New `az codespace plan update` command.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [n/a] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Codespaces

**Comment by derekbekoe** [comment]
@fengzhou-msft as the pending reviewer, could you review this and merge if ready?

**Comment by derekbekoe** [comment]
@yonzhan @haroldrandom @fengzhou-msft ping on this.
It's been a week since the PR was first created. We'd like to have the new updates available to our users.

**Comment by yonzhan** [comment]
@fengzhou-msft will help you merge this PR.

**Comment by derekbekoe** [comment]
Ping on this again.

**Comment by fengzhou-msft** [comment]
Merged. Sorry for the delay.

**Pull request merged**
