### PR TITLE
[Release] Update index.json for extension [ appservice-kube ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ appservice-kube ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=1415742

Last commit against main: https://github.com/Azure/azure-cli-extensions/commit/f77b373146be6cb2f15b1cccec5311f161b23ce0

### CODE REVIEW

**Comment by yonzhan** [comment]
appservice-kube

**Review by wangzelin007 — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by StrawnSC** [comment]
@zhoxing-ms thanks for merging this. Do you know how long it generally takes after these release PRs get merged for the extension update to become available? When I try to install, it installs the old version (`0.1.4`)

**Comment by zhoxing-ms** [comment]
@StrawnSC There were some problems with the release pipeline, I have manually released it. Please try it again
Screenshot 2022-03-10 111452
~

**Comment by StrawnSC** [comment]
@zhoxing-ms it works now thank you!

**Pull request merged**
