### PR TITLE
fix tenant ID retrieval

### PR DESCRIPTION
**Pull request by TheOnlyWei**
### Related command
az connectedk8s

Try to merge the below PR first before this PR:
https://github.com/Azure/azure-cli-extensions/pull/7251

It seems the connectedk8s live test doesn't work properly, probably because the command is being run as a subprocess, since it passed when it should have failed: https://github.com/Azure/azure-cli-extensions/blob/06ad14fbbdd9328077170a1f2371c687847b95c2/src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py#L584
So, I did not catch the issue. Ideally, we have a fully automated test pipeline for connectedk8s, but currently we have to run a bunch of manual tests. Other teams seem to have better tests for connectedk8s than connectedk8s has for itself.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [X] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by yonzhan — APPROVED** [review]

**Comment by jsntcy** [comment]
@TheOnlyWei, please fix CI error first.

**Comment by TheOnlyWei** [comment]
> @TheOnlyWei, please fix CI error first.
Hi, this is an urgent bug fix. The connectedk8s team plans on a task to fix style issue in the future. These azdev style errors has always been there before my changes. I also verified that the azdev style pipeline to make sure my changes did not cause any new issues, so please ignore the azdev style pipeline.

**Comment by jsntcy** [comment]
> > @TheOnlyWei, please fix CI error first.
> 
> Hi @jsntcy, can you merge this PR first? It reverts the version with the bug from being downloaded by customers. #7251
> 
> Regarding the azdev style failure, the connectedk8s team plans on a separate task to fix azdev style issue in the future. These azdev style errors has always been there before my changes. I already verified in the azdev style pipeline that my changes did not cause any new issues, so please ignore the azdev style pipeline.

I saw this CI error existed for several months, please provide an ETA to fix it; otherwise "in the future" means never fixing.
 
https://github.com/Azure/azure-cli-extensions/pull/7103
https://github.com/Azure/azure-cli-extensions/pull/7111
https://github.com/Azure/azure-cli-extensions/pull/7139

**Comment by TheOnlyWei** [comment]
@jsntcy I would fix it myself, but I don't work on the team that owns connectedk8s. I am just contributing. I have pointed out this issue to the owners before. I can ping them here as well.

@NarayanThiru Do you have an ETA when the azdev style issues will be fixed?

**Comment by jsntcy** [comment]
> @jsntcy Yu Chen FTE I would fix it myself, but I don't work on the team that owns connectedk8s. I am just contributing. I have pointed out this issue to the owners before. I can ping them here as well.
> 
> @NarayanThiru Narayan Thiru FTE Do you have an ETA when the azdev style issues will be fixed?

Although the style issues don't block PR merge so far, we will change it to merge PR block in the future.

**Comment by TheOnlyWei** [comment]
@jsntcy Regardless, this change should go in before someone else makes a PR and merges into connectedk8s and reintroduces the reverted change from:
https://github.com/Azure/azure-cli-extensions/pull/7251
For azdev style issue, you should work with @NarayanThiru to get that resolved.

**Pull request merged**
