### PR TITLE
Update image-copy version

### PR DESCRIPTION
**Pull request by qwordy**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### CODE REVIEW

**Comment by tamirkamara** [comment]
@qwordy You're changing the location of the extension file. This means I'll have a harder time to publish it myself in the future... 
Would you like me to update and publish it myself (was meaning to do it anyway this week)?

**Comment by qwordy** [comment]
> 
> 
> @qwordy You're changing the location of the extension file. This means I'll have a harder time to publish it myself in the future...
> Would you like me to update and publish it myself (was meaning to do it anyway this week)?

Oh. Sorry. No problem. We can abandon this PR. Once it's published, let me know. Thanks.

**Comment by qwordy** [comment]
@tamirkamara Have you updated and published it?

**Comment by tamirkamara** [comment]
It's here: https://github.com/Azure/azure-cli-extensions/pull/1211

**Pull request closed without merging**
