### PR TITLE
containerapp refactor client

### PR DESCRIPTION
**Pull request by Greedygre**
---
We will have 2 extension: containerapp and containerapp-preview.
Generally, in containerapp extension we use stable api-version, in containerapp-preview extension we could use preview api-version.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by Greedygre** [comment]
Hi @zhoxing-ms 
The verify Ref Docs failed. error as following, is there any problem in test pipeline?

ERROR: test_ref_doc_partnercenter (__main__.IndexRefDocs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/./scripts/ci/index_ref_doc.py", line 65, in test
    raise e
  File "/mnt/vss/_work/1/s/./scripts/ci/index_ref_doc.py", line 62, in test
    check_call(script_args)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.10.12/x64/bin/python', '/mnt/vss/_work/1/s/scripts/refdoc/generate.py', '--extension-file', '/tmp/tmpj5ap7dr4/partnercenter-0.2.3-py3-none-any.whl', '--output-dir', '/tmp/tmp05876jq9/partnercenter']' returned non-zero exit status 1.

**Comment by zhoxing-ms** [comment]
@Greedygre This is a known issue related to `pydantic` https://github.com/pydantic/pydantic/issues/6361, we are tracking it

**Pull request closed without merging**
