### PR TITLE
[AKS]fix: don't update storageProfile if not set

### PR DESCRIPTION
**Pull request by andyzhangx**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

az aks update

This PR fixed the issue that CSI driver would be accidentally disabled when run `az aks update` command even `--disable-disk-driver --disable-file-driver` is not specified.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Review by FumingZhang — COMMENTED** [review]
LGTM

Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=55407851&view=results) to check the modified test cases.

**Review by FumingZhang — APPROVED** [review]
Live test passed. LGTM:shipit:

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
