### PR TITLE
[Spring Cloud] Support zone redundant while service instance creating

### PR DESCRIPTION
**Pull request by Descatles**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Spring Cloud

**Review by Caoxuyang — APPROVED** [review]

**Review by wangzelin007 — COMMENTED** [review]
Hi @Descatles,
If you want to release the new extension version, please write the description of changes into HISTORY.rst and update setup.py.

**Comment by Descatles** [comment]
> Hi @Descatles, If you want to release the new extension version, please write the description of changes into HISTORY.rst and update setup.py.

Hello, @wangzelin007 , This code change would release together with our enterprise tier cli,  we will upgrade the version right before the enterprise tier announcement on 2022/01/17 and release the CLI. 
I think we could merge this pr first.

**Review by wangzelin007 — APPROVED** [review]

**Comment by jsntcy** [comment]
Please add test to cover the new argument.

**Review by jsntcy — APPROVED** [review]

**Comment by yuwzho** [comment]
#4294

**Pull request merged**
