### PR TITLE
[AKS] Support IMDS restriction

### PR DESCRIPTION
**Pull request by norshtein**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by norshtein** [comment]
@FumingZhang @zhoxing-ms @yanzhudd could you please help a review? Thanks!

The CI is failing at [case "test_aks_create_with_pod_ip_allocation_mode_static_block"](https://dev.azure.com/azclitools/public/_build/results?buildId=174553&view=logs&j=2e66ce57-bcb2-51b3-abdd-698c078f35ff&t=16b5c26c-808a-5e55-7cf9-03cc11587706&l=2490), it seems to be irrelevant to this PR's change, @FumingZhang  do you have any idea, is this a known issue?

**Review by FumingZhang — COMMENTED** [review]
lgtm

Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=98790731&view=results) to validate the change.
- test_aks_enable_imds_restriction

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
