### PR TITLE
Fix issues of storage account name for az aks kollect

### PR DESCRIPTION
**Pull request by feiskyer**
Refer https://github.com/Azure/aks-periscope/pull/21: trailing dash "-" is not allowed in storage name, hence this PR removes the trailing dash and aligned the logic with https://github.com/Azure/aks-periscope/pull/21.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @Tatsinnit

**Comment by Tatsinnit** [comment]
LGTM.

**Comment by yonzhan** [comment]
add to S170

**Comment by feiskyer** [comment]
Rebased. @qwordy any chances to get this merged?

**Comment by feiskyer** [comment]
@qwordy thanks!

**Pull request merged**
