### PR TITLE
[ASA] Create workspace-based App Insights

### PR DESCRIPTION
**Pull request by domainname**
Create workspace-based App Insights during creating ASA instance.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by domainname** [comment]
> Please fix CI issues.

Sure. Fixed several minutes ago.

**Comment by zhoxing-ms** [comment]
@domainname Please add some test cases for this PR change?

**Comment by zhoxing-ms** [comment]
@yuwzho Could you please help review the Spring related PR?

**Review by yuwzho — APPROVED** [review]

**Comment by yuwzho** [comment]
LGTM

**Comment by domainname** [comment]
> @domainname Please add some test cases for this PR change?

@zhoxing-ms I added a UT.

**Comment by zhoxing-ms** [comment]
@domainname Could you please fix the CI issue?

**Comment by domainname** [comment]
> @domainname Could you please fix the CI issue?

Those style check failures are from existing code, not from changes introduced in my PR. :-)

**Comment by yonzhan** [comment]
Add @wangzelin007 to help with

**Comment by zhoxing-ms** [comment]
https://github.com/Azure/azure-cli-extensions/pull/6993#issuecomment-1809929865 Please take a look at this comment~

**Comment by domainname** [comment]
Attempted to rebase master branch. It rejected my push and asked me to merge instead. So I merged. That's why the commit history is so long. :-(

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
Please submit a separate new PR to address the style issue of the original code

**Pull request merged**
