### PR TITLE
Add Async support with new API version 2021-05-01-preview

### PR DESCRIPTION
**Pull request by NarayanThiru**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style k8s-extension` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
Can you please create the PR against the AzureArcForKubernetes:k8s-extension/public. This way, we release from this branch instead of directly from yours

**Comment by jonathan-innis** [comment]
Also, this way we have internal review before opening it up for review against upstream

**Comment by yonzhan** [comment]
k8s

**Comment by NarayanThiru** [comment]
Closing this, as I've created a PR for our Internal review

**Pull request closed without merging**
