### PR TITLE
[Release] Update index.json for extension [ alertsmanagement ] 

### PR DESCRIPTION
**Pull request by azclibot**
[Release] Update index.json for extension [ alertsmanagement ] 

 Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=346842

Last commit against master: https://github.com/Azure/azure-cli-extensions/commit/9796d838c2c071181669af1a6e9d7a1ed1690f3b

### CODE REVIEW

**Comment by yungezz** [comment]
h @qwordy @haroldrandom could you pls help to look at the CI failure?

**Comment by qwordy** [comment]
I run the failed command manually, it succeeds. (○´･д･)ﾉ
```
python scripts/refdoc/generate.py -e dist\alertsmanagement-0.1.0-py2.py3-none-any.whl
```

**Pull request closed without merging**
