### PR TITLE
[ArcAppliance] Add new WHL for SCVMM scenarios

### PR DESCRIPTION
**Pull request by pkoushik**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by pkoushik** [comment]
We are doing a follow up fix for version `0.1.46` (new version is `0.1.47`), we have a newer version of the extension `0.2.15` already released. We want `0.2.15` to remain the latest. Given the changes in `index.json` in the PR will that be the case?

**Comment by yonzhan** [comment]
ArcAppliance

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
> 0.2.15

Yes. 0.2.15 will still be the latest version to install.

**Comment by pkoushik** [comment]
Feel free to merge when you get a chance

**Pull request merged**
