### PR TITLE
{Containerapp} Update recording files

### PR DESCRIPTION
**Pull request by Greedygre**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

In azure-cli, the api-version has been upgraded to 2024-03-01, the azure-cli-extensions need to rerun and update recording files.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by yonzhan** [comment]
Containerapp

**Review by Moazzem-Hossain-pixel — CHANGES_REQUESTED** [review]
If you can help to resolve that will be appreciated.

**Comment by Greedygre** [comment]
> If you can help to resolve that will be appreciated.
Hi @zhoxing-ms 

We don't know this person, but he auto commented in all PRs.

**Comment by yonzhan** [comment]
I just reported abuse or spam for this person.

**Review by Moazzem-Hossain-pixel — CHANGES_REQUESTED** [review]
Please do the necessary changes

**Review by Juliehzl — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
